cmake_minimum_required(VERSION 3.20)
project(Boomify VERSION 0.0.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(Boomify WIN32 src/main.cpp)
target_compile_definitions(Boomify PRIVATE UNICODE _UNICODE NOMINMAX)
target_link_libraries(Boomify PRIVATE winmm)
