// Boomify V7 - native instruments per track
#define BOOMIFY_V7_INCLUDE
#define wWinMain wWinMain_v6_legacy
#include "main_v6.cpp"
#undef wWinMain
#undef BOOMIFY_V7_INCLUDE

namespace {
enum class NativeSound{Bass,Saw,Lead,Pluck,Pad};
std::array<NativeSound,V6_MAX_TRACKS> laneSound={NativeSound::Bass,NativeSound::Bass,NativeSound::Saw};
const wchar_t* soundName(NativeSound s){switch(s){case NativeSound::Bass:return L"BASS";case NativeSound::Saw:return L"SAW";case NativeSound::Lead:return L"LEAD";case NativeSound::Pluck:return L"PLUCK";default:return L"PAD";}}
struct Voice7{NativeSound sound;int note=60,age=0;double ph=0;};
double sample7(Voice7&v){double t=v.age/(double)SR,f=hz(v.note);v.ph+=f/SR;if(v.ph>=1)v.ph-=1;double si=sin(6.283185307179586*v.ph),saw=2*v.ph-1,sq=v.ph<.5?1.0:-1.0,o=0;switch(v.sound){case NativeSound::Bass:o=(saw*.55+si*.45)*exp(-t*2.8);break;case NativeSound::Saw:o=(saw*.72+si*.28)*exp(-t*1.7);break;case NativeSound::Lead:o=(sq*.35+si*.65)*exp(-t*1.25);break;case NativeSound::Pluck:o=(saw*.45+si*.55)*exp(-t*7.5);break;case NativeSound::Pad:o=(si*.7+saw*.18)*std::min(1.0,t*8.0)*exp(-t*.7);break;}v.age++;return o;}
bool alive7(const Voice7&v){double q=1;switch(v.sound){case NativeSound::Bass:q=.55;break;case NativeSound::Saw:q=.8;break;case NativeSound::Lead:q=.9;break;case NativeSound::Pluck:q=.32;break;case NativeSound::Pad:q=1.6;break;}return v.age<q*SR;}
void renderRangeV7(std::vector<int16_t>&out,int start){start=std::clamp(start,0,activeBars-1);int step=std::max(1,(int)(SR*60.0/bpm/4.0));size_t frames=(size_t)step*STEPS*(activeBars-start);out.assign(frames*2,0);std::vector<Voice> drumsV;std::vector<Voice7> notesV;bool anySolo=false;for(auto&l:lanes)if(l.solo)anySolo=true;for(size_t f=0;f<frames;f++){if(f%step==0){int g=(int)(f/step),b=start+g/STEPS,s=g%STEPS;if(!lanes.empty()&&!lanes[0].mute&&(!anySolo||lanes[0].solo))for(int r=0;r<DR;r++)if(drums[b][r][s])drumsV.push_back({r,0});for(int lane=1;lane<(int)lanes.size();lane++){if(lanes[lane].type==LaneType::Audio||lanes[lane].mute||(anySolo&&!lanes[lane].solo))continue;auto&clip=noteForLane(lane,b);int base=(laneSound[lane]==NativeSound::Bass)?47:71;for(int r=0;r<NOTES;r++)if(clip[r][s])notesV.push_back({laneSound[lane],base-r});}}double x=0;for(auto&q:drumsV)x+=sample(q);for(auto&q:notesV)x+=sample7(q);drumsV.erase(std::remove_if(drumsV.begin(),drumsV.end(),[](const Voice&q){return!alive(q);}),drumsV.end());notesV.erase(std::remove_if(notesV.begin(),notesV.end(),[](const Voice7&q){return!alive7(q);}),notesV.end());int16_t z=(int16_t)(std::clamp(x*.22*(master/100.0),-1.0,1.0)*32767);out[f*2]=out[f*2+1]=z;}}
void playV7(){if(playing){stopAudio();return;}playStartBar=cursorBar;renderRangeV7(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;MessageBoxW(win,L"Sortie audio Windows indisponible.",L"Boomify",MB_OK|MB_ICONERROR);return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void exportV7(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderRangeV7(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,align=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&align,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
void chooseSound(HWND h,int lane,POINT p){if(lane<=0||lane>=(int)lanes.size()||lanes[lane].type!=LaneType::Instrument)return;HMENU m=CreatePopupMenu();AppendMenuW(m,MF_STRING,64001,L"Bass");AppendMenuW(m,MF_STRING,64002,L"Saw");AppendMenuW(m,MF_STRING,64003,L"Lead");AppendMenuW(m,MF_STRING,64004,L"Pluck");AppendMenuW(m,MF_STRING,64005,L"Pad");ClientToScreen(h,&p);int cmd=TrackPopupMenu(m,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,h,nullptr);DestroyMenu(m);if(cmd>=64001&&cmd<=64005){laneSound[lane]=(NativeSound)(cmd-64001);InvalidateRect(h,nullptr,FALSE);}}
void drawSoundLabels(HDC d){for(int i=1;i<(int)lanes.size();i++)if(lanes[i].type==LaneType::Instrument)label(d,soundName(laneSound[i]),74,laneHeadR[i].top+22,8,RGB(211,104,76),FW_BOLD);}
LRESULT CALLBACK proc_v7(HWND h,UINT m,WPARAM wp,LPARAM lp){if(m==WM_RBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};for(int i=1;i<(int)lanes.size();i++)if(inside(laneHeadR[i],p)&&p.x<194){chooseSound(h,i,p);return 0;}}if(m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(inside(playR,p)){playV7();return 0;}if(inside(wavR,p)){exportV7();return 0;}}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);drawV6(mem,c);drawSoundLabels(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}return proc_v6(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v7;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV7";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 4 - Native Instruments",WS_OVERLAPPEDWINDOW,0,0,1500,920,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();laneSound[1]=NativeSound::Bass;laneSound[2]=NativeSound::Saw;layoutV6(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
