// Boomify Alpha 5 - Studio workflow layer
#define BOOMIFY_V12_INCLUDE
#include "main_v11.cpp"
#undef BOOMIFY_V12_INCLUDE

namespace {
struct Clip12{int lane=0,off=0;LaneType type=LaneType::Instrument;DrumClip drum{};NoteClip note{};};
std::vector<Clip12> clip12;
bool range12=false; POINT r0{},r1{}; int anchorL=-1,anchorB=-1,drag12=0,dragFx=-1;
RECT master12{},nav12{},thumb12{},zminus12{},zplus12{},add8_12{},home12{},stop12{},dupli12{};

std::vector<BlockRef> selected12(){if(!multiSelection.empty())return multiSelection;if(laneSelected>=0&&laneSelected<(int)lanes.size())return{{laneSelected,selectedBar}};return{};}
void copy12(){auto a=selected12();clip12.clear();if(a.empty())return;int mb=MAX_BARS;for(auto&q:a)mb=std::min(mb,q.bar);for(auto&q:a){if(q.track<0||q.track>=(int)lanes.size()||q.bar<0||q.bar>=MAX_BARS)continue;Clip12 s{};s.lane=q.track;s.off=q.bar-mb;s.type=lanes[q.track].type;if(s.type==LaneType::Drums)s.drum=drumForLane11(q.track,q.bar);else if(s.type==LaneType::Instrument)s.note=noteForLane(q.track,q.bar);clip12.push_back(s);}}
void write12(const std::vector<Clip12>&a,int base){clearMulti();int first=MAX_BARS;for(auto&s:a){int b=base+s.off;if(b<0||b>=MAX_BARS||s.lane<0||s.lane>=(int)lanes.size())continue;if(b>=activeBars)activeBars=b+1;if(s.type==LaneType::Drums&&lanes[s.lane].type==LaneType::Drums)drumForLane11(s.lane,b)=s.drum;else if(s.type==LaneType::Instrument&&lanes[s.lane].type==LaneType::Instrument)noteForLane(s.lane,b)=s.note;addMulti(s.lane,b);first=std::min(first,b);}if(first<MAX_BARS){selectedBar=first;ensureVisible(first);}layout11(win);InvalidateRect(win,nullptr,FALSE);}
void paste12(int b=-1){if(clip12.empty())return;if(b<0)b=selectedBar;write12(clip12,std::clamp(b,0,MAX_BARS-1));}
void duplicate12(){auto a=selected12();if(a.empty())return;int lo=MAX_BARS,hi=-1;for(auto&q:a){lo=std::min(lo,q.bar);hi=std::max(hi,q.bar);}std::vector<Clip12>s;for(auto&q:a){if(q.track<0||q.track>=(int)lanes.size())continue;Clip12 x{};x.lane=q.track;x.off=q.bar-lo;x.type=lanes[q.track].type;if(x.type==LaneType::Drums)x.drum=drumForLane11(q.track,q.bar);else if(x.type==LaneType::Instrument)x.note=noteForLane(q.track,q.bar);s.push_back(x);}write12(s,hi+1);}
void erase12(){for(auto&q:selected12()){if(q.track<0||q.track>=(int)lanes.size()||q.bar<0||q.bar>=MAX_BARS)continue;if(lanes[q.track].type==LaneType::Drums){auto&d=drumForLane11(q.track,q.bar);for(auto&r:d)r.fill(false);}else if(lanes[q.track].type==LaneType::Instrument)clearNote(noteForLane(q.track,q.bar));}clearMulti();InvalidateRect(win,nullptr,FALSE);}
void pick12(int l,int b,bool add,bool ext){l=std::clamp(l,0,(int)lanes.size()-1);b=std::clamp(b,0,activeBars-1);if(ext&&anchorL>=0){clearMulti();for(int y=std::min(anchorL,l);y<=std::max(anchorL,l);y++)for(int x=std::min(anchorB,b);x<=std::max(anchorB,b);x++)addMulti(y,x);}else{if(!add)clearMulti();bool has=false;for(auto&q:multiSelection)if(q.track==l&&q.bar==b)has=true;if(add&&has)multiSelection.erase(std::remove_if(multiSelection.begin(),multiSelection.end(),[&](const BlockRef&q){return q.track==l&&q.bar==b;}),multiSelection.end());else addMulti(l,b);anchorL=l;anchorB=b;}laneSelected=l;selectedTrack=std::min(TRACKS-1,l);selectedBar=b;}
void rangeSelect12(){clearMulti();RECT rr{std::min(r0.x,r1.x),std::min(r0.y,r1.y),std::max(r0.x,r1.x)+1,std::max(r0.y,r1.y)+1};for(int l=0;l<(int)lanes.size();l++)for(int v=0;v<visibleBars;v++){int b=scrollBar+v;if(b>=activeBars)continue;RECT q=cell11(l,v),z{};if(IntersectRect(&z,&rr,&q))addMulti(l,b);}if(!multiSelection.empty()){laneSelected=multiSelection.front().track;selectedBar=multiSelection.front().bar;anchorL=laneSelected;anchorB=selectedBar;}}
void cursor12(POINT p){int w=std::max(1,(int)(timeline10.right-timeline10.left));int v=std::clamp((int)((long long)(p.x-(int)timeline10.left)*visibleBars/w),0,visibleBars-1);cursorBar=std::clamp(scrollBar+v,0,activeBars-1);}
int playBar12(){if(!playing||!wave)return cursorBar;MMTIME t{};t.wType=TIME_SAMPLES;if(waveOutGetPosition(wave,&t,sizeof(t))!=MMSYSERR_NOERROR)return cursorBar;double sec=(double)t.u.sample/SR,bar=(60.0/std::max(1,bpm))*4.0;return std::clamp(playStartBar+(int)(sec/bar),0,activeBars-1);}
void masterSet12(int x){int w=std::max(1,(int)(master12.right-master12.left));master=std::clamp((x-(int)master12.left)*100/w,0,100);InvalidateRect(win,nullptr,FALSE);}
void navSet12(int x){int ms=std::max(0,activeBars-visibleBars),tw=std::max(1,(int)(thumb12.right-thumb12.left)),travel=std::max(1,(int)(nav12.right-nav12.left)-tw);scrollBar=ms?std::clamp((int)((long long)std::clamp(x-(int)nav12.left-tw/2,0,travel)*ms/travel),0,ms):0;InvalidateRect(win,nullptr,FALSE);}
RECT fxBar12(int i){RECT q=fxRects11[(size_t)i];return{q.left+13,q.top+30,q.right-13,q.top+47};}
void fxSet12(int i,int x){int real=fxScroll11+i;if(laneSelected<0||laneSelected>=(int)lanes.size()||real<0||real>=(int)rack11[laneSelected].size())return;RECT r=fxBar12(i);rack11[laneSelected][real].amount=std::clamp((x-(int)r.left)*100/std::max(1,(int)(r.right-r.left)),0,100);InvalidateRect(win,nullptr,FALSE);}
void menu12(HWND h,POINT p,int l,int b){pick12(l,b,false,false);HMENU m=CreatePopupMenu();AppendMenuW(m,MF_STRING,72001,L"Copier\tCtrl+C");AppendMenuW(m,MF_STRING,72002,L"Coller\tCtrl+V");AppendMenuW(m,MF_STRING,72003,L"Dupliquer\tCtrl+D");AppendMenuW(m,MF_SEPARATOR,0,nullptr);AppendMenuW(m,MF_STRING,72004,L"Vider\tSuppr");POINT s=p;ClientToScreen(h,&s);int c=TrackPopupMenu(m,TPM_RETURNCMD|TPM_RIGHTBUTTON,s.x,s.y,0,h,nullptr);DestroyMenu(m);if(c==72001)copy12();else if(c==72002)paste12(b);else if(c==72003)duplicate12();else if(c==72004)erase12();}
void overlay12(HDC d){RECT c;GetClientRect(win,&c);fill(d,{0,70,c.right,114},RGB(17,19,24));home12={310,78,346,106};stop12={352,78,392,106};dupli12={398,78,468,106};for(RECT r:{home12,stop12,dupli12})fill(d,r,RGB(43,46,55));label(d,L"|<",321,86,8,RGB(225,227,232),FW_BOLD);label(d,L"STOP",357,86,7,RGB(225,227,232),FW_BOLD);label(d,L"DUPLI",410,86,7,RGB(225,227,232),FW_BOLD);
int bar=playBar12();if(bar>=scrollBar&&bar<scrollBar+visibleBars){int w=std::max(1,(int)(timeline10.right-timeline10.left)),x=(int)timeline10.left+(int)((long long)(bar-scrollBar)*w/visibleBars);line(d,x,(int)timeline10.top,x,(int)timeline10.bottom,RGB(255,103,72),3);RECT t{(LONG)x,timeline10.top,(LONG)std::min((int)timeline10.right,x+40),(LONG)((int)timeline10.top+21)};fill(d,t,RGB(235,103,74));std::wstring s=L"M"+std::to_wstring(bar+1);label(d,s.c_str(),x+6,(int)timeline10.top+5,7,RGB(255,255,255),FW_BOLD);}
master12={(LONG)std::max(920,(int)c.right-330),24,(LONG)std::max(1040,(int)c.right-190),35};label(d,L"MASTER",master12.left-60,24,7,RGB(150,154,164),FW_BOLD);fill(d,master12,RGB(34,37,44));RECT mf=master12;mf.right=mf.left+(mf.right-mf.left)*master/100;fill(d,mf,RGB(235,103,74));std::wstring mv=std::to_wstring(master)+L"%";label(d,mv.c_str(),master12.right+7,22,7,RGB(210,212,218),FW_BOLD);
int nx=488,nr=(int)timeline10.right-20;nav12={(LONG)nx,89,(LONG)nr,99};fill(d,nav12,RGB(31,34,41));int width=std::max(1,nr-nx),tw=std::clamp((int)((long long)width*visibleBars/std::max(1,activeBars)),36,width),ms=std::max(0,activeBars-visibleBars),travel=std::max(0,width-tw),tx=nx+(ms?scrollBar*travel/ms:0);thumb12={(LONG)tx,85,(LONG)(tx+tw),103};fill(d,thumb12,RGB(105,111,124));zminus12={(LONG)(nr-112),76,(LONG)(nr-84),106};zplus12={(LONG)(nr-80),76,(LONG)(nr-52),106};add8_12={(LONG)(nr-48),76,(LONG)nr,106};for(RECT r:{zminus12,zplus12,add8_12})fill(d,r,RGB(46,49,58));label(d,L"-",zminus12.left+10,85,9,RGB(230,232,236),FW_BOLD);label(d,L"+",zplus12.left+9,84,9,RGB(230,232,236),FW_BOLD);label(d,L"+8",add8_12.left+14,84,8,RGB(230,232,236),FW_BOLD);
if(laneSelected>=0&&laneSelected<(int)lanes.size()){std::wstring s=lanes[laneSelected].name+L"  /  mesure "+std::to_wstring(selectedBar+1)+L"  /  "+std::to_wstring(multiSelection.size())+L" selection(s)";label(d,s.c_str(),18,(int)c.bottom-22,7,RGB(132,137,148));}if(range12){RECT q{std::min(r0.x,r1.x),std::min(r0.y,r1.y),std::max(r0.x,r1.x),std::max(r0.y,r1.y)};line(d,q.left,q.top,q.right,q.top,RGB(245,245,245),2);line(d,q.left,q.bottom,q.right,q.bottom,RGB(245,245,245),2);line(d,q.left,q.top,q.left,q.bottom,RGB(245,245,245),2);line(d,q.right,q.top,q.right,q.bottom,RGB(245,245,245),2);}}
LRESULT CALLBACK proc_v12(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);overlay12(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_TIMER&&w==1){InvalidateRect(h,nullptr,FALSE);return proc_v11(h,m,w,l);}if(m==WM_RBUTTONDOWN&&inside(timeline10,p)){int a=-1,b=-1;if(hitTimeline11(p,a,b)){menu12(h,p,a,b);return 0;}}if(m==WM_LBUTTONDOWN){if(inside(home12,p)){if(playing)stopAudio();cursorBar=scrollBar=0;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(stop12,p)){if(playing)stopAudio();return 0;}if(inside(dupli12,p)){duplicate12();return 0;}if(inside(master12,p)){drag12=1;masterSet12(p.x);SetCapture(h);return 0;}if(inside(nav12,p)||inside(thumb12,p)){drag12=2;navSet12(p.x);SetCapture(h);return 0;}if(inside(zminus12,p)){zoom(-1);return 0;}if(inside(zplus12,p)){zoom(1);return 0;}if(inside(add8_12,p)){addBars();layout11(h);return 0;}for(int i=0;i<(int)fxRects11.size();i++)if(inside(fxBar12(i),p)){drag12=3;dragFx=i;fxSet12(i,p.x);SetCapture(h);return 0;}if(inside(timeline10,p)){int a=-1,b=-1;if(hitTimeline11(p,a,b)){cursor12(p);bool ct=(GetKeyState(VK_CONTROL)&0x8000)!=0,sh=(GetKeyState(VK_SHIFT)&0x8000)!=0;pick12(a,b,ct,sh);if(!ct&&!sh){range12=true;r0=r1=p;SetCapture(h);}InvalidateRect(h,nullptr,FALSE);return 0;}}}if(m==WM_MOUSEMOVE){if(drag12==1&&(w&MK_LBUTTON)){masterSet12(p.x);return 0;}if(drag12==2&&(w&MK_LBUTTON)){navSet12(p.x);return 0;}if(drag12==3&&(w&MK_LBUTTON)){fxSet12(dragFx,p.x);return 0;}if(range12){r1=p;InvalidateRect(h,nullptr,FALSE);return 0;}}if(m==WM_LBUTTONUP){if(drag12){drag12=0;dragFx=-1;if(GetCapture()==h)ReleaseCapture();return 0;}if(range12){r1=p;if(std::abs(r1.x-r0.x)>5||std::abs(r1.y-r0.y)>5)rangeSelect12();range12=false;if(GetCapture()==h)ReleaseCapture();InvalidateRect(h,nullptr,FALSE);return 0;}}if(m==WM_KEYDOWN){bool ct=(GetKeyState(VK_CONTROL)&0x8000)!=0;if(ct&&w=='C'){copy12();return 0;}if(ct&&w=='V'){paste12();return 0;}if(ct&&w=='D'){duplicate12();return 0;}if(w==VK_DELETE){erase12();return 0;}if(w==VK_HOME){cursorBar=scrollBar=0;InvalidateRect(h,nullptr,FALSE);return 0;}if(w==VK_ESCAPE){clearMulti();range12=false;InvalidateRect(h,nullptr,FALSE);return 0;}}return proc_v11(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v12;wc.hInstance=hi;wc.lpszClassName=L"BoomifyStudio";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 5 - Studio",WS_OVERLAPPEDWINDOW,0,0,1600,960,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;layout11(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
