// Boomify V5 - project hub + multi-block timeline editing
#define BOOMIFY_V4_NO_ENTRY
#include "main_v4.cpp"
#undef BOOMIFY_V4_NO_ENTRY

namespace {
struct BlockRef{int track=0,bar=0;}; struct BlockData{int track=0,offset=0;DrumClip drum{};NoteClip note{};};
std::vector<BlockRef> multiSelection;std::vector<BlockData> multiClipboard;bool selectingRange=false;POINT rangeStart{},rangeNow{};int rangeStartTrack=-1,rangeStartBar=-1;
bool isSelectedMulti(int t,int b){for(auto&q:multiSelection)if(q.track==t&&q.bar==b)return true;return false;}void clearMulti(){multiSelection.clear();}void addMulti(int t,int b){if(!isSelectedMulti(t,b))multiSelection.push_back({t,b});}
void selectRectCells(POINT a,POINT b){clearMulti();RECT rr{std::min(a.x,b.x),std::min(a.y,b.y),std::max(a.x,b.x)+1,std::max(a.y,b.y)+1};for(int t=0;t<TRACKS;t++)for(int v=0;v<visibleBars;v++){int bar=scrollBar+v;if(bar>=activeBars)continue;RECT q=clipR[t][v],inter{};if(IntersectRect(&inter,&rr,&q))addMulti(t,bar);}if(!multiSelection.empty()){selectedTrack=multiSelection.front().track;selectedBar=multiSelection.front().bar;}InvalidateRect(win,nullptr,FALSE);}
void copyMulti(){if(multiSelection.empty()){copyClip();return;}multiClipboard.clear();int minB=MAX_BARS;for(auto&q:multiSelection)minB=std::min(minB,q.bar);for(auto&q:multiSelection){BlockData d;d.track=q.track;d.offset=q.bar-minB;if(q.track==0)d.drum=drums[q.bar];else d.note=q.track==1?bass[q.bar]:melody[q.bar];multiClipboard.push_back(d);}copied=true;}
void pasteMultiAt(int anchor){if(multiClipboard.empty()){pasteClip();return;}auto data=multiClipboard;clearMulti();for(auto&d:data){int b=anchor+d.offset;if(b<0||b>=MAX_BARS)continue;if(b>=activeBars)activeBars=b+1;if(d.track==0)drums[b]=d.drum;else if(d.track==1)bass[b]=d.note;else melody[b]=d.note;addMulti(d.track,b);}selectedBar=anchor;ensureVisible(anchor);layout(win);InvalidateRect(win,nullptr,FALSE);}void pasteMulti(){pasteMultiAt(selectedBar);}
void duplicateMulti(){
    if(multiSelection.empty()){duplicateClip();return;}
    auto src=multiSelection;
    int minB=MAX_BARS,maxB=-1;
    for(const auto&q:src){minB=std::min(minB,q.bar);maxB=std::max(maxB,q.bar);}
    // Duplicate the whole selected time span immediately after itself.
    // Destination = original bar + selection width. This preserves every block,
    // including adjacent blocks (1,2 -> 3,4) and gaps (1,3 -> 4,6).
    int span=maxB-minB+1;
    std::vector<BlockData> snap;
    snap.reserve(src.size());
    for(const auto&q:src){BlockData d;d.track=q.track;d.offset=q.bar;if(q.track==0)d.drum=drums[q.bar];else d.note=q.track==1?bass[q.bar]:melody[q.bar];snap.push_back(d);}
    clearMulti();
    int firstDest=MAX_BARS;
    for(const auto&d:snap){int b=d.offset+span;if(b<0||b>=MAX_BARS)continue;firstDest=std::min(firstDest,b);if(b>=activeBars)activeBars=b+1;if(d.track==0)drums[b]=d.drum;else if(d.track==1)bass[b]=d.note;else melody[b]=d.note;addMulti(d.track,b);}
    if(firstDest<MAX_BARS){selectedBar=firstDest;ensureVisible(firstDest);}layout(win);InvalidateRect(win,nullptr,FALSE);
}
void clearMultiBlocks(){if(multiSelection.empty()){clearCell(selectedTrack,selectedBar);return;}for(auto&q:multiSelection)clearCell(q.track,q.bar);InvalidateRect(win,nullptr,FALSE);}
void paintSelectionOverlay(HDC d){for(auto&q:multiSelection){if(q.bar<scrollBar||q.bar>=scrollBar+visibleBars)continue;RECT r=clipR[q.track][q.bar-scrollBar];line(d,r.left+1,r.top+1,r.right-1,r.top+1,RGB(255,255,255),3);line(d,r.left+1,r.bottom-2,r.right-1,r.bottom-2,RGB(255,255,255),3);line(d,r.left+1,r.top+1,r.left+1,r.bottom-1,RGB(255,255,255),3);line(d,r.right-2,r.top+1,r.right-2,r.bottom-1,RGB(255,255,255),3);}if(selectingRange){RECT r{std::min(rangeStart.x,rangeNow.x),std::min(rangeStart.y,rangeNow.y),std::max(rangeStart.x,rangeNow.x),std::max(rangeStart.y,rangeNow.y)};line(d,r.left,r.top,r.right,r.top,RGB(210,210,210));line(d,r.left,r.bottom,r.right,r.bottom,RGB(210,210,210));line(d,r.left,r.top,r.left,r.bottom,RGB(210,210,210));line(d,r.right,r.top,r.right,r.bottom,RGB(210,210,210));}}
const int HUB_NEW=51001,HUB_OPEN=51002,HUB_QUIT=51003;HWND hub=nullptr;int hubChoice=0;
LRESULT CALLBACK hubProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CREATE){CreateWindowW(L"STATIC",L"BOOMIFY",WS_CHILD|WS_VISIBLE,28,24,250,30,h,nullptr,nullptr,nullptr);CreateWindowW(L"STATIC",L"Que veux-tu faire ?",WS_CHILD|WS_VISIBLE,28,58,260,24,h,nullptr,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Nouveau projet",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,28,100,290,44,h,(HMENU)(INT_PTR)HUB_NEW,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Ouvrir un projet existant",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,28,154,290,44,h,(HMENU)(INT_PTR)HUB_OPEN,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Quitter",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,28,218,290,34,h,(HMENU)(INT_PTR)HUB_QUIT,nullptr,nullptr);return 0;}if(m==WM_CTLCOLORSTATIC){HDC dc=(HDC)w;SetTextColor(dc,RGB(235,235,238));SetBkColor(dc,RGB(31,32,36));static HBRUSH br=CreateSolidBrush(RGB(31,32,36));return(LRESULT)br;}if(m==WM_ERASEBKGND){RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(31,32,36));FillRect((HDC)w,&r,b);DeleteObject(b);return 1;}if(m==WM_COMMAND){int id=LOWORD(w);if(id==HUB_NEW||id==HUB_OPEN||id==HUB_QUIT){hubChoice=id;DestroyWindow(h);return 0;}}if(m==WM_CLOSE){hubChoice=HUB_QUIT;DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);}int startupHub(HINSTANCE hi){WNDCLASSW wc{};wc.lpfnWndProc=hubProc;wc.hInstance=hi;wc.lpszClassName=L"BoomifyProjectHub";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);hubChoice=0;hub=CreateWindowExW(WS_EX_TOPMOST,wc.lpszClassName,L"Boomify",WS_POPUP|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,360,300,nullptr,nullptr,hi,nullptr);RECT r;GetWindowRect(hub,&r);SetWindowPos(hub,nullptr,(GetSystemMetrics(SM_CXSCREEN)-(r.right-r.left))/2,(GetSystemMetrics(SM_CYSCREEN)-(r.bottom-r.top))/2,0,0,SWP_NOSIZE|SWP_NOZORDER);ShowWindow(hub,SW_SHOW);UpdateWindow(hub);MSG msg{};while(IsWindow(hub)&&GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return hubChoice;}
LRESULT CALLBACK proc_v5(HWND h,UINT m,WPARAM wp,LPARAM lp){if(m==WM_KEYDOWN){bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0;if(ctrl&&wp=='C'){copyMulti();return 0;}if(ctrl&&wp=='V'){pasteMulti();return 0;}if(ctrl&&wp=='D'){duplicateMulti();return 0;}if(wp==VK_DELETE&&!(GetKeyState(VK_SHIFT)&0x8000)){clearMultiBlocks();return 0;}if(wp==VK_ESCAPE){clearMulti();InvalidateRect(h,nullptr,FALSE);return 0;}}
if(m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(inside(dupR,p)){duplicateMulti();return 0;}if(inside(newR,p)||inside(openR,p)||inside(saveR,p)||inside(wavR,p)||inside(addR,p)||inside(insertR,p)||inside(deleteR,p)||inside(zoomOutR,p)||inside(zoomInR,p)||inside(editorR,p)||inside(playR,p)||inside(minusR,p)||inside(plusR,p)||inside(volR,p))return proc_v4(h,m,wp,lp);int tr,b;if(hitClipAt(p,tr,b)){bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0,shift=(GetKeyState(VK_SHIFT)&0x8000)!=0;if(ctrl){if(isSelectedMulti(tr,b))multiSelection.erase(std::remove_if(multiSelection.begin(),multiSelection.end(),[&](const BlockRef&q){return q.track==tr&&q.bar==b;}),multiSelection.end());else addMulti(tr,b);selectedTrack=tr;selectedBar=b;InvalidateRect(h,nullptr,FALSE);return 0;}if(shift){int from=std::min(selectedBar,b),to=std::max(selectedBar,b);clearMulti();for(int x=from;x<=to;x++)addMulti(tr,x);selectedTrack=tr;InvalidateRect(h,nullptr,FALSE);return 0;}clearMulti();addMulti(tr,b);selectedTrack=tr;selectedBar=b;selectingRange=true;rangeStart=rangeNow=p;rangeStartTrack=tr;rangeStartBar=b;SetCapture(h);InvalidateRect(h,nullptr,FALSE);return 0;}else{RECT c;GetClientRect(h,&c);int bottom=editorOpen?std::max(455,(int)(c.bottom*.64)):c.bottom-45;if(p.x>=180&&p.x<c.right-20&&p.y>=126&&p.y<bottom){clearMulti();selectingRange=true;rangeStart=rangeNow=p;rangeStartTrack=-1;rangeStartBar=-1;SetCapture(h);return 0;}}}
if(m==WM_MOUSEMOVE&&selectingRange&&(wp&MK_LBUTTON)){rangeNow={GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(abs(rangeNow.x-rangeStart.x)>3||abs(rangeNow.y-rangeStart.y)>3)selectRectCells(rangeStart,rangeNow);return 0;}if(m==WM_LBUTTONUP&&selectingRange){rangeNow={GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};bool moved=abs(rangeNow.x-rangeStart.x)>3||abs(rangeNow.y-rangeStart.y)>3;if(moved)selectRectCells(rangeStart,rangeNow);else if(rangeStartTrack>=0){clearMulti();addMulti(rangeStartTrack,rangeStartBar);selectedTrack=rangeStartTrack;selectedBar=rangeStartBar;}selectingRange=false;rangeStartTrack=rangeStartBar=-1;ReleaseCapture();InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);paint(mem,c);paintSelectionOverlay(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}return proc_v4(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){int choice=startupHub(hi);if(choice==HUB_QUIT||choice==0)return 0;WNDCLASSW wc{};wc.lpfnWndProc=proc_v5;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV5";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 2 - Project Workspace",WS_OVERLAPPEDWINDOW,0,0,1500,920,nullptr,nullptr,hi,nullptr);if(!win)return 1;freshEmpty();layout(win);if(choice==HUB_OPEN)openProject();ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
