// Boomify V15 - Alpha 6 independent panel architecture
#define BOOMIFY_V15_INCLUDE
#define proc_v14 proc_v14_base15
#include "main_v14.cpp"
#undef proc_v14
#undef BOOMIFY_V15_INCLUDE
#include <cmath>
namespace {
struct Sample15{std::wstring path;int bar=-1;std::vector<int16_t> pcm;};
struct Kick15{bool enabled=false;int pitch=42,decay=38,punch=42,drive=22;};
struct Panels15{RECT tracks{},timeline{},inspector{};int rowH=48;};
std::array<Sample15,V6_MAX_TRACKS> samples15{};std::array<Kick15,V6_MAX_TRACKS> kicks15{};std::array<COLORREF,V6_MAX_TRACKS> colors15{};
RECT import15{},boom15{},master15{};std::array<RECT,V6_MAX_TRACKS> colorHit15{},nameHit15{};RECT kpMinus15{},kpPlus15{},kdMinus15{},kdPlus15{},kuMinus15{},kuPlus15{},krMinus15{},krPlus15{};bool masterOn15=true;
int audioSelected15=-1;bool audioDrag15=false;int audioDragX15=0,audioDragBar15=0;Panels15 panels15{};
COLORREF defaultColor15(int i){static COLORREF c[]={RGB(220,96,69),RGB(69,132,210),RGB(162,93,205),RGB(62,169,126),RGB(220,154,55),RGB(205,76,118),RGB(70,170,181),RGB(130,139,151)};return c[i%8];}
void layoutPanels15(HWND h){RECT c{};GetClientRect(h,&c);int top=(int)timeline10.top,bottom=(int)timeline10.bottom;if(bottom<=top){top=116;bottom=std::max(top+160,(int)c.bottom-286);}int trackW=230,inspectW=std::clamp((int)(c.right*0.20),260,340);panels15.tracks={0,(LONG)top,(LONG)trackW,(LONG)bottom};panels15.inspector={(LONG)std::max(trackW+320,(int)c.right-inspectW),(LONG)top,c.right,(LONG)bottom};panels15.timeline={(LONG)trackW,(LONG)top,panels15.inspector.left,(LONG)bottom};int avail=std::max(1,bottom-top);panels15.rowH=std::clamp(avail/std::max(1,(int)lanes.size()),34,58);}
RECT row15(int lane){int y=(int)panels15.timeline.top+lane*panels15.rowH;return{panels15.timeline.left,(LONG)y,panels15.timeline.right,(LONG)std::min((int)panels15.timeline.bottom,y+panels15.rowH)};}
RECT trackRow15(int lane){RECT r=row15(lane);return{panels15.tracks.left,r.top,panels15.tracks.right,r.bottom};}
RECT cell15(int lane,int visible){RECT r=row15(lane);int w=std::max(1,(int)(panels15.timeline.right-panels15.timeline.left));int x0=(int)panels15.timeline.left+(int)((long long)visible*w/std::max(1,visibleBars));int x1=(int)panels15.timeline.left+(int)((long long)(visible+1)*w/std::max(1,visibleBars));return{(LONG)x0,r.top,(LONG)x1,r.bottom};}
bool loadWav15(const std::wstring&p,std::vector<int16_t>&out){std::ifstream f(p,std::ios::binary);if(!f)return false;char id[4];uint32_t n=0;f.read(id,4);f.read((char*)&n,4);f.read(id,4);if(!f||std::string(id,4)!="WAVE")return false;uint16_t fmt=0,ch=0,bits=0;uint32_t rate=0;std::vector<char> data;while(f.read(id,4)){uint32_t sz=0;f.read((char*)&sz,4);if(!f)break;if(std::string(id,4)=="fmt "){uint16_t al=0;uint32_t br=0;f.read((char*)&fmt,2);f.read((char*)&ch,2);f.read((char*)&rate,4);f.read((char*)&br,4);f.read((char*)&al,2);f.read((char*)&bits,2);if(sz>16)f.seekg(sz-16,std::ios::cur);}else if(std::string(id,4)=="data"){data.resize(sz);f.read(data.data(),sz);}else f.seekg(sz,std::ios::cur);if(sz&1)f.seekg(1,std::ios::cur);}if(fmt!=1||bits!=16||(ch!=1&&ch!=2)||rate!=SR||data.empty())return false;const int16_t*s=(const int16_t*)data.data();size_t frames=data.size()/(2*ch);out.resize(frames*2);for(size_t i=0;i<frames;i++){int16_t a=s[i*ch],b=ch==2?s[i*ch+1]:a;out[i*2]=a;out[i*2+1]=b;}return true;}
double sampleBars15(const Sample15&s){if(s.pcm.empty())return 0.0;double sec=(double)(s.pcm.size()/2)/SR;double secBar=240.0/std::max(60,bpm);return sec/secBar;}
void ensureRenderLength15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);size_t baseFrames=(size_t)(secBar*SR)*std::max(1,activeBars-startBar),need=baseFrames*2;for(int l=0;l<(int)lanes.size();++l){auto&s=samples15[l];if(s.bar<startBar||s.pcm.empty())continue;size_t dst=(size_t)((s.bar-startBar)*secBar*SR)*2;need=std::max(need,dst+s.pcm.size());}if(a.size()<need)a.resize(need,0);}
void mixSample15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);long long bf=(long long)(secBar*SR);for(int l=0;l<(int)lanes.size();l++){auto&s=samples15[l];if(s.bar<0||s.pcm.empty()||lanes[l].mute)continue;long long dst=((long long)s.bar-startBar)*bf;if(dst<0)continue;double g=lanes[l].volume/100.0;for(size_t k=0;k+1<s.pcm.size();k+=2){size_t j=(size_t)(dst+(long long)k/2)*2;if(j+1>=a.size())break;for(int c=0;c<2;c++)a[j+c]=(int16_t)std::clamp((int)a[j+c]+(int)(s.pcm[k+c]*g),-32768,32767);}}}
void mixBoom15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);long long bf=(long long)(secBar*SR),sf=bf/STEPS;for(int l=0;l<(int)lanes.size();l++){if(!kicks15[l].enabled||lanes[l].mute||lanes[l].type!=LaneType::Drums)continue;auto&k=kicks15[l];for(int b=startBar;b<activeBars;b++){auto&d=drumForLane11(l,b);for(int s=0;s<STEPS;s++)if(d[0][s]){long long st=((long long)b-startBar)*bf+(long long)s*sf;long long wanted=(long long)(SR*(0.050+k.decay*0.0028));long long len=std::max<long long>(256,std::min<long long>(wanted,sf-8));long long fadeLen=std::min<long long>((long long)(SR*0.015),len/2);double ph=0;for(long long q=0;q<len;q++){double t=(double)q/SR;double env=std::exp(-t*(18.0+(100-k.decay)*0.14));double hz=38.0+k.pitch*0.82+(70.0*k.punch/100.0)*std::exp(-t*50.0);ph+=6.283185307179586*hz/SR;double body=std::sin(ph)*env*(0.44+0.15*k.punch/100.0);double attack=std::min(1.0,(double)q/std::max<long long>(1,(long long)(SR*0.0007)));double drv=1.0+k.drive/60.0;double x=(std::tanh(body*drv)/std::tanh(drv))*attack;if(q>=len-fadeLen){double u=(double)(len-q)/std::max<long long>(1,fadeLen);x*=u*u*(3.0-2.0*u);}size_t j=(size_t)(st+q)*2;if(j+1>=a.size())break;int add=(int)(x*9000.0*lanes[l].volume/100.0);for(int c=0;c<2;c++)a[j+c]=(int16_t)std::clamp((int)a[j+c]+add,-32768,32767);}}}}}
void masterBus15(std::vector<int16_t>&a){double outGain=std::clamp(master,0,100)/100.0;if(!masterOn15){for(auto&v:a)v=(int16_t)std::lrint(v*outGain);return;}double env=0;for(auto&v:a){double x=v/32768.0;env=std::max(std::abs(x),env*0.9993);double cg=env>0.55?std::pow(0.55/env,0.30):1.0;x*=cg*1.12;x=std::tanh(x*1.08)/std::tanh(1.08);x*=outGain;v=(int16_t)std::lrint(std::clamp(x,-0.94,0.94)*32767.0);}}
void render15(std::vector<int16_t>&a,int start){std::array<bool,V6_MAX_TRACKS> oldMute{};for(int i=0;i<(int)lanes.size();++i){oldMute[i]=lanes[i].mute;if(kicks15[i].enabled)lanes[i].mute=true;}renderRange11(a,start);for(int i=0;i<(int)lanes.size();++i)lanes[i].mute=oldMute[i];ensureRenderLength15(a,start);mixSample15(a,start);mixBoom15(a,start);masterBus15(a);}
void play15(){if(playing){stopAudio();return;}playStartBar=cursorBar;render15(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export15(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;render15(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*sizeof(int16_t)),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
std::wstring editText15(HWND owner,const std::wstring&initial){HINSTANCE hi=(HINSTANCE)GetWindowLongPtrW(owner,GWLP_HINSTANCE);static std::wstring result;result=initial;static HWND ed=nullptr;static bool reg=false;if(!reg){WNDCLASSW wc{};wc.hInstance=hi;wc.lpszClassName=L"BoomifyRename15";wc.lpfnWndProc=[](HWND h,UINT m,WPARAM w,LPARAM l)->LRESULT{if(m==WM_CREATE){ed=CreateWindowW(L"EDIT",result.c_str(),WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,14,14,280,26,h,(HMENU)1,nullptr,nullptr);CreateWindowW(L"BUTTON",L"OK",WS_CHILD|WS_VISIBLE,218,48,76,26,h,(HMENU)2,nullptr,nullptr);SetFocus(ed);SendMessageW(ed,EM_SETSEL,0,-1);return 0;}if(m==WM_COMMAND&&LOWORD(w)==2){wchar_t b[128]{};GetWindowTextW(ed,b,128);result=b;DestroyWindow(h);return 0;}if(m==WM_CLOSE){result.clear();DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);};RegisterClassW(&wc);reg=true;}HWND q=CreateWindowExW(WS_EX_TOPMOST,L"BoomifyRename15",L"Renommer la piste",WS_POPUP|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,325,115,owner,nullptr,hi,nullptr);EnableWindow(owner,FALSE);ShowWindow(q,SW_SHOW);MSG msg{};while(IsWindow(q)&&GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}EnableWindow(owner,TRUE);SetForegroundWindow(owner);return result;}
void renameLane15(int l){if(l<0||l>=(int)lanes.size())return;auto s=editText15(win,lanes[l].name);if(!s.empty())lanes[l].name=s;InvalidateRect(win,nullptr,FALSE);}
void cycleColorLane15(int l){if(l<0||l>=(int)lanes.size())return;static int ci[V6_MAX_TRACKS]{};colors15[l]=defaultColor15(++ci[l]+l);InvalidateRect(win,nullptr,FALSE);}
void importSample15(){int targetBar=std::clamp(selectedBar,0,MAX_BARS-1);if(laneSelected<0||laneSelected>=(int)lanes.size()||lanes[laneSelected].type!=LaneType::Audio){if((int)lanes.size()>=V6_MAX_TRACKS){MessageBoxW(win,L"Nombre maximum de pistes atteint.",L"Boomify",MB_OK);return;}lanes.push_back({L"Audio",LaneType::Audio,false,false,90});laneSelected=(int)lanes.size()-1;colors15[laneSelected]=defaultColor15(laneSelected);layout11(win);layoutPanels15(win);}auto p=dialog(false,L"WAV PCM 16-bit 44.1 kHz\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t> pcm;if(!loadWav15(p,pcm)){MessageBoxW(win,L"WAV PCM 16-bit 44.1 kHz requis pour cette Alpha.",L"Boomify",MB_OK);return;}samples15[laneSelected]={p,targetBar,std::move(pcm)};audioSelected15=laneSelected;size_t slash=p.find_last_of(L"\\/");std::wstring fn=slash==std::wstring::npos?p:p.substr(slash+1);size_t dot=fn.find_last_of(L'.');if(dot!=std::wstring::npos)fn=fn.substr(0,dot);if(!fn.empty())lanes[laneSelected].name=fn;double bars=sampleBars15(samples15[laneSelected]);activeBars=std::min(MAX_BARS,std::max(activeBars,targetBar+(int)std::ceil(bars)));layout11(win);layoutPanels15(win);InvalidateRect(win,nullptr,FALSE);}
void addBoom15(){if((int)lanes.size()>=V6_MAX_TRACKS)return;lanes.push_back({L"BoomBox Kick",LaneType::Drums,false,false,82});laneSelected=(int)lanes.size()-1;kicks15[laneSelected].enabled=true;colors15[laneSelected]=RGB(225,88,62);layout11(win);layoutPanels15(win);InvalidateRect(win,nullptr,FALSE);}
void adj15(int&v,int d){v=std::clamp(v+d,0,100);InvalidateRect(win,nullptr,FALSE);}
bool selectedCell15(int l,int b){for(auto&q:multiSelection)if(q.track==l&&q.bar==b)return true;return multiSelection.empty()&&laneSelected==l&&selectedBar==b;}
RECT audioRect15(int l){RECT z{0,0,0,0};if(l<0||l>=(int)lanes.size()||samples15[l].pcm.empty()||samples15[l].bar<0||visibleBars<1)return z;double st=(double)samples15[l].bar,en=st+sampleBars15(samples15[l]);double vs=std::max(st,(double)scrollBar),ve=std::min(en,(double)(scrollBar+visibleBars));if(ve<=vs)return z;RECT rr=row15(l);int w=std::max(1,(int)(panels15.timeline.right-panels15.timeline.left));LONG left=(LONG)(panels15.timeline.left+(vs-scrollBar)*w/std::max(1,visibleBars));LONG right=(LONG)(panels15.timeline.left+(ve-scrollBar)*w/std::max(1,visibleBars));return{left+3,rr.top+5,right-3,rr.bottom-5};}
void drawWave15(HDC d,const RECT&r,const Sample15&s,COLORREF c){fill(d,r,c);int mid=(int)((r.top+r.bottom)/2),hh=std::max(2,(int)((r.bottom-r.top)/2-4)),ww=std::max(1,(int)(r.right-r.left));if(ww>8&&!s.pcm.empty()){HPEN pen=CreatePen(PS_SOLID,1,RGB(238,238,242));auto op=SelectObject(d,pen);size_t frames=s.pcm.size()/2;for(int x=3;x<ww-3;x+=2){size_t i=std::min(frames-1,(size_t)((double)x/ww*frames));int v=std::abs((int)s.pcm[i*2]);int a=std::max(1,(int)((double)v/32768.0*hh));MoveToEx(d,r.left+x,mid-a,nullptr);LineTo(d,r.left+x,mid+a);}SelectObject(d,op);DeleteObject(pen);}line(d,r.left,r.top,r.right,r.top,RGB(245,245,248));}
void drawTracks15(HDC d){fill(d,panels15.tracks,RGB(24,26,31));for(int l=0;l<(int)lanes.size();++l){RECT r=trackRow15(l);if(r.bottom<=r.top)continue;fill(d,r,l==laneSelected?RGB(39,42,50):((l&1)?RGB(27,29,35):RGB(30,32,38)));line(d,r.left,r.bottom-1,r.right,r.bottom-1,RGB(47,50,58));COLORREF c=colors15[l]?colors15[l]:defaultColor15(l);RECT stripe{r.left,r.top,r.left+5,r.bottom};fill(d,stripe,c);nameHit15[l]={r.left+14,r.top+6,r.right-42,r.top+28};colorHit15[l]={r.right-29,r.top+11,r.right-13,r.top+27};label(d,lanes[l].name.c_str(),nameHit15[l].left,nameHit15[l].top+3,8,RGB(232,234,239),l==laneSelected?FW_BOLD:FW_NORMAL);fill(d,colorHit15[l],c);std::wstring meta=(lanes[l].type==LaneType::Drums?L"DRUM":lanes[l].type==LaneType::Audio?L"AUDIO":L"INST");meta+=L"   "+std::to_wstring(lanes[l].volume)+L"%";label(d,meta.c_str(),r.left+14,r.bottom-18,6,RGB(132,137,148));}line(d,panels15.tracks.right-1,panels15.tracks.top,panels15.tracks.right-1,panels15.tracks.bottom,RGB(66,70,80),2);}
void drawTimeline15(HDC d){int saved=SaveDC(d);IntersectClipRect(d,panels15.timeline.left,panels15.timeline.top,panels15.timeline.right,panels15.timeline.bottom);fill(d,panels15.timeline,RGB(19,21,26));for(int l=0;l<(int)lanes.size();++l){for(int v=0;v<visibleBars;++v){int b=scrollBar+v;if(b>=MAX_BARS)break;RECT r=cell15(l,v);fill(d,r,(l&1)?RGB(22,24,29):RGB(24,26,31));line(d,r.right-1,r.top,r.right-1,r.bottom,RGB(48,52,61));line(d,r.left,r.bottom-1,r.right,r.bottom-1,RGB(42,46,54));if(b<activeBars&&lanes[l].type!=LaneType::Audio&&laneUsed11(l,b)){COLORREF c=colors15[l]?colors15[l]:defaultColor15(l);RECT q{r.left+4,r.top+5,r.right-4,r.bottom-5};fill(d,q,c);if(selectedCell15(l,b)){line(d,q.left,q.top,q.right,q.top,RGB(255,255,255),2);line(d,q.left,q.bottom-1,q.right,q.bottom-1,RGB(255,255,255),2);line(d,q.left,q.top,q.left,q.bottom,RGB(255,255,255),2);line(d,q.right-1,q.top,q.right-1,q.bottom,RGB(255,255,255),2);}}}if(lanes[l].type==LaneType::Audio){RECT ar=audioRect15(l);if(ar.right>ar.left){COLORREF c=colors15[l]?colors15[l]:defaultColor15(l);drawWave15(d,ar,samples15[l],c);if(audioSelected15==l){line(d,ar.left,ar.top,ar.right,ar.top,RGB(255,255,255),2);line(d,ar.left,ar.bottom-1,ar.right,ar.bottom-1,RGB(255,255,255),2);line(d,ar.left,ar.top,ar.left,ar.bottom,RGB(255,255,255),2);line(d,ar.right-1,ar.top,ar.right-1,ar.bottom,RGB(255,255,255),2);}label(d,lanes[l].name.c_str(),ar.left+7,ar.top+6,7,RGB(250,250,252),FW_BOLD);}}}RestoreDC(d,saved);}
int hitAudio15(POINT p){if(!inside(panels15.timeline,p))return-1;for(int l=0;l<(int)lanes.size();++l)if(lanes[l].type==LaneType::Audio){RECT r=audioRect15(l);if(r.right>r.left&&inside(r,p))return l;}return-1;}
bool hitCell15(POINT p,int&lane,int&bar){if(!inside(panels15.timeline,p))return false;for(int l=0;l<(int)lanes.size();++l){if(lanes[l].type==LaneType::Audio)continue;RECT rr=row15(l);if(p.y<rr.top||p.y>=rr.bottom)continue;int w=std::max(1,(int)(panels15.timeline.right-panels15.timeline.left));int v=std::clamp((int)((long long)(p.x-panels15.timeline.left)*visibleBars/w),0,visibleBars-1);int b=scrollBar+v;if(b>=0&&b<activeBars){lane=l;bar=b;return true;}}return false;}
void draw15(HDC d){for(int i=0;i<V6_MAX_TRACKS;i++){colorHit15[i]={0,0,0,0};nameHit15[i]={0,0,0,0};}drawTracks15(d);RECT ir=panels15.inspector;int ix=(int)ir.left+18,iw=std::max(110,(int)ir.right-ix-18);import15={ix,ir.top+18,ix+iw,ir.top+48};boom15={ix,ir.top+54,ix+iw,ir.top+84};master15={ix,ir.top+90,ix+iw,ir.top+120};if(ir.right>ir.left){fill(d,ir,RGB(24,26,31));line(d,ir.left,ir.top,ir.left,ir.bottom,RGB(66,70,80),2);label(d,L"INSPECTOR / FX",ix,ir.top+4,8,RGB(232,234,239),FW_BOLD);button(d,import15,L"IMPORTER WAV / + AUDIO");button(d,boom15,L"+ PISTE BOOMBOX");fill(d,master15,masterOn15?RGB(62,128,93):RGB(42,44,49));std::wstring mt=L"MASTER FX  |  VOLUME "+std::to_wstring(master)+L"%";label(d,mt.c_str(),master15.left+10,master15.top+10,7,RGB(235,237,241),FW_BOLD);label(d,L"Piste selectionnee",ix,ir.top+136,7,RGB(140,145,156));if(laneSelected>=0&&laneSelected<(int)lanes.size())label(d,lanes[laneSelected].name.c_str(),ix,ir.top+154,8,RGB(235,126,99),FW_BOLD);}if(laneSelected>=0&&laneSelected<(int)lanes.size()&&kicks15[laneSelected].enabled&&ir.right>ir.left){auto&k=kicks15[laneSelected];int y=(int)ir.top+188;label(d,L"BOOMBOX / KICK DESIGNER",ix,y,8,RGB(235,126,99),FW_BOLD);auto row=[&](const wchar_t*n,int v,int yy,RECT&mn,RECT&pl){label(d,n,ix,yy+7,7,RGB(205,208,215),FW_BOLD);std::wstring z=std::to_wstring(v);label(d,z.c_str(),ix+86,yy+7,7,RGB(240,240,243),FW_BOLD);mn={ix+122,yy,ix+150,yy+26};pl={ix+156,yy,ix+184,yy+26};fill(d,mn,RGB(43,46,54));fill(d,pl,RGB(43,46,54));label(d,L"-",mn.left+10,mn.top+6,8,RGB(235,235,240),FW_BOLD);label(d,L"+",pl.left+9,pl.top+6,8,RGB(235,235,240),FW_BOLD);};row(L"PITCH",k.pitch,y+24,kpMinus15,kpPlus15);row(L"DECAY",k.decay,y+56,kdMinus15,kdPlus15);row(L"PUNCH",k.punch,y+88,kuMinus15,kuPlus15);row(L"DRIVE",k.drive,y+120,krMinus15,krPlus15);}}
LRESULT CALLBACK proc_v15(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_SIZE){LRESULT r=proc_v14_base15(h,m,w,l);layoutPanels15(h);return r;}if(m==WM_PAINT){layoutPanels15(h);PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);drawV13Chrome(mem);drawV14(mem);drawTimeline15(mem);draw15(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDBLCLK){for(int i=0;i<(int)lanes.size();i++)if(inside(nameHit15[i],p)){laneSelected=i;renameLane15(i);return 0;}}if(m==WM_LBUTTONDOWN){int al=hitAudio15(p);if(al>=0){audioSelected15=al;laneSelected=selectedTrack=al;selectedBar=samples15[al].bar;cursorBar=selectedBar;audioDrag15=true;audioDragX15=p.x;audioDragBar15=samples15[al].bar;SetCapture(h);InvalidateRect(h,nullptr,FALSE);return 0;}int cl=-1,cb=-1;if(hitCell15(p,cl,cb)){audioSelected15=-1;bool ct=(GetKeyState(VK_CONTROL)&0x8000)!=0,sh=(GetKeyState(VK_SHIFT)&0x8000)!=0;pick12(cl,cb,ct,sh);cursorBar=cb;InvalidateRect(h,nullptr,FALSE);return 0;}audioSelected15=-1;for(int i=0;i<(int)lanes.size();i++)if(inside(colorHit15[i],p)){laneSelected=i;cycleColorLane15(i);return 0;}if(inside(playR,p)){play15();return 0;}if(inside(wavR,p)){export15();return 0;}if(inside(import15,p)){importSample15();return 0;}if(inside(boom15,p)){addBoom15();return 0;}if(inside(master15,p)){masterOn15=!masterOn15;InvalidateRect(h,nullptr,FALSE);return 0;}if(laneSelected>=0&&laneSelected<(int)lanes.size()&&kicks15[laneSelected].enabled){auto&k=kicks15[laneSelected];if(inside(kpMinus15,p)){adj15(k.pitch,-2);return 0;}if(inside(kpPlus15,p)){adj15(k.pitch,2);return 0;}if(inside(kdMinus15,p)){adj15(k.decay,-5);return 0;}if(inside(kdPlus15,p)){adj15(k.decay,5);return 0;}if(inside(kuMinus15,p)){adj15(k.punch,-5);return 0;}if(inside(kuPlus15,p)){adj15(k.punch,5);return 0;}if(inside(krMinus15,p)){adj15(k.drive,-5);return 0;}if(inside(krPlus15,p)){adj15(k.drive,5);return 0;}}}if(m==WM_MOUSEMOVE&&audioDrag15&&audioSelected15>=0){int cw=std::max(1,(int)(panels15.timeline.right-panels15.timeline.left)/std::max(1,visibleBars));int delta=(int)std::lround((double)(p.x-audioDragX15)/cw);int nb=std::clamp(audioDragBar15+delta,0,MAX_BARS-1);if(samples15[audioSelected15].bar!=nb){samples15[audioSelected15].bar=nb;selectedBar=cursorBar=nb;activeBars=std::min(MAX_BARS,std::max(activeBars,nb+(int)std::ceil(sampleBars15(samples15[audioSelected15]))));InvalidateRect(h,nullptr,FALSE);}return 0;}if(m==WM_LBUTTONUP&&audioDrag15){audioDrag15=false;ReleaseCapture();return 0;}return proc_v14_base15(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int){for(int i=0;i<V6_MAX_TRACKS;i++)colors15[i]=defaultColor15(i);v6Fresh();editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;master=100;WNDCLASSW wc{};wc.lpfnWndProc=proc_v15;wc.hInstance=hi;wc.lpszClassName=L"BoomifyAlpha6";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);wc.style=CS_DBLCLKS;RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Studio - Alpha 6 Panels",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1440,900,nullptr,nullptr,hi,nullptr);if(!win)return 1;layout11(win);layoutPanels15(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wParam;}
