// Boomify V17 navigation/audio layer. Keeps V17 as the single application entry point.
#include <windows.h>
LRESULT CALLBACK proc_v17_nav(HWND,UINT,WPARAM,LPARAM);
static ATOM RegisterClassW_nav(const WNDCLASSW* src){WNDCLASSW wc=*src;wc.lpfnWndProc=proc_v17_nav;return ::RegisterClassW(&wc);}
#define RegisterClassW RegisterClassW_nav
#include "main_v17.cpp"
#undef RegisterClassW

namespace {
RECT zoomOutNavR{},zoomInNavR{},fitNavR{},loopNavR{},setLoopNavR{};
std::array<RECT,V6_MAX_TRACKS> muteNavR{},soloNavR{};
bool loopOnNav=false;int loopStartNav=0,loopEndNav=3;

void relayoutNav(){layout11(win);sync16(win);InvalidateRect(win,nullptr,FALSE);}
void scrollTimelineNav(int dir){if(!dir)return;int step=std::max(1,visibleBars/4);if(dir>0){int wanted=scrollBar+step,needed=std::min(MAX_BARS,wanted+visibleBars);if(needed>activeBars)activeBars=needed;scrollBar=std::min(wanted,std::max(0,MAX_BARS-visibleBars));}else scrollBar=std::max(0,scrollBar-step);cursorBar=std::clamp(cursorBar,scrollBar,std::min(MAX_BARS-1,scrollBar+visibleBars-1));relayoutNav();}
void zoomNav(int dir){int old=visibleBars;if(dir>0)visibleBars=std::max(4,visibleBars/2);else visibleBars=std::min(MAX_BARS,std::max(visibleBars+1,visibleBars*2));if(dir<0&&visibleBars>activeBars)visibleBars=std::min(MAX_BARS,std::max(activeBars,4));if(old==visibleBars)return;scrollBar=std::clamp(scrollBar,0,std::max(0,MAX_BARS-visibleBars));if(cursorBar<scrollBar)scrollBar=cursorBar;if(cursorBar>=scrollBar+visibleBars)scrollBar=std::max(0,cursorBar-visibleBars+1);relayoutNav();}
void fitTimelineNav(){visibleBars=std::clamp(activeBars,4,MAX_BARS);scrollBar=0;relayoutNav();}
void setLoopNavFromSelection(){int lo=MAX_BARS,hi=-1;for(auto&q:multiSelection){lo=std::min(lo,q.bar);hi=std::max(hi,q.bar);}if(hi<0){lo=std::clamp(selectedBar,0,std::max(0,activeBars-1));hi=std::min(activeBars-1,lo+3);}loopStartNav=std::clamp(lo,0,std::max(0,activeBars-1));loopEndNav=std::clamp(std::max(loopStartNav,hi),loopStartNav,std::max(loopStartNav,activeBars-1));loopOnNav=true;InvalidateRect(win,nullptr,FALSE);}
void drawTrackButtonsNav(HDC d){for(auto&r:muteNavR)r={0,0,0,0};for(auto&r:soloNavR)r={0,0,0,0};for(int l=0;l<(int)lanes.size();++l){RECT r=trackRow15(l);r.left+=12;r.right-=12;r.top+=4;r.bottom-=4;if(r.bottom-r.top<34)continue;LONG y=r.top+7;muteNavR[l]={r.right-62,y,r.right-38,y+22};soloNavR[l]={r.right-34,y,r.right-10,y+22};COLORREF cc=colors15[l]?colors15[l]:defaultColor15(l);pill16(d,muteNavR[l],L"M",cc,lanes[l].mute);pill16(d,soloNavR[l],L"S",RGB(232,184,68),lanes[l].solo);}}
void drawNavTools(HDC d){RECT p=panels15.timeline;LONG y=p.top+13;setLoopNavR={p.right-350,y,p.right-275,y+27};loopNavR={p.right-269,y,p.right-205,y+27};fitNavR={p.right-199,y,p.right-145,y+27};zoomOutNavR={p.right-139,y,p.right-97,y+27};zoomInNavR={p.right-91,y,p.right-49,y+27};pill16(d,setLoopNavR,L"SET LOOP",CYAN16);pill16(d,loopNavR,L"LOOP",PINK16,loopOnNav);pill16(d,fitNavR,L"FIT",PURPLE16);pill16(d,zoomOutNavR,L"-",PURPLE16);pill16(d,zoomInNavR,L"+",PURPLE16);if(loopOnNav){int left=(int)p.left+15,right=(int)p.right-15,width=std::max(1,right-left),a=loopStartNav-scrollBar,b=loopEndNav-scrollBar+1;if(b>0&&a<visibleBars){a=std::clamp(a,0,visibleBars);b=std::clamp(b,0,visibleBars);LONG x0=left+(LONG)((long long)a*width/std::max(1,visibleBars)),x1=left+(LONG)((long long)b*width/std::max(1,visibleBars));RECT r{x0,p.top+38,x1,p.top+43};fill(d,r,PINK16);}}drawTrackButtonsNav(d);}

void clearLaneStorageNav(int lane){if(lane<0||lane>=V6_MAX_TRACKS)return;samples15[lane]={};kicks15[lane]={};colors15[lane]=defaultColor15(lane);rack11[lane].clear();for(int b=0;b<MAX_BARS;++b)fine16[lane][b].clear();if(lane>=3){int idx=lane-3;if(idx>=0&&idx<V6_MAX_TRACKS-3){for(auto&c:extraNotes[idx])clearNote(c);for(auto&c:extraDrums11[idx])for(auto&r:c)r.fill(false);}}}
void addTrackNav(HWND h,POINT client){if((int)lanes.size()>=V6_MAX_TRACKS){MessageBoxW(h,L"Nombre maximum de pistes atteint.",L"Boomify",MB_OK|MB_ICONINFORMATION);return;}HMENU menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,PICK_DRUM,L"Drums / Batterie");AppendMenuW(menu,MF_STRING,PICK_INST,L"Instrument / Bass / Synth");AppendMenuW(menu,MF_STRING,PICK_AUDIO,L"Audio / Sample WAV");POINT s=client;ClientToScreen(h,&s);int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_RIGHTBUTTON,s.x,s.y,0,h,nullptr);DestroyMenu(menu);if(cmd!=PICK_DRUM&&cmd!=PICK_INST&&cmd!=PICK_AUDIO)return;LaneType t=cmd==PICK_DRUM?LaneType::Drums:cmd==PICK_AUDIO?LaneType::Audio:LaneType::Instrument;int count=1;for(auto&x:lanes)if(x.type==t)count++;std::wstring name=t==LaneType::Drums?L"Drums "+std::to_wstring(count):t==LaneType::Audio?L"Audio "+std::to_wstring(count):L"Instrument "+std::to_wstring(count);int n=(int)lanes.size();clearLaneStorageNav(n);lanes.push_back({name,t,false,false,80});laneSelected=n;selectedTrack=std::min(TRACKS-1,n);selectedBar=std::clamp(selectedBar,0,std::max(0,activeBars-1));clearMulti();if(t==LaneType::Instrument)sound9[n]=Sound9::SawLead;layout11(h);layoutPanels15(h);sync16(h);InvalidateRect(h,nullptr,FALSE);}
void removeTrackNav(){if(laneSelected<0||laneSelected>=(int)lanes.size())return;if(laneSelected<3){MessageBoxW(win,L"Les trois pistes de base restent verrouillees pour cette Alpha.",L"Boomify",MB_OK|MB_ICONINFORMATION);return;}int old=laneSelected,n=(int)lanes.size();for(int lane=old;lane<n-1;++lane){samples15[lane]=std::move(samples15[lane+1]);kicks15[lane]=kicks15[lane+1];colors15[lane]=colors15[lane+1];rack11[lane]=std::move(rack11[lane+1]);sound9[lane]=sound9[lane+1];fine16[lane]=std::move(fine16[lane+1]);}int idx=old-3;for(int k=idx;k<V6_MAX_TRACKS-4;++k){extraNotes[k]=std::move(extraNotes[k+1]);extraDrums11[k]=std::move(extraDrums11[k+1]);}for(auto&c:extraNotes[V6_MAX_TRACKS-4])clearNote(c);for(auto&c:extraDrums11[V6_MAX_TRACKS-4])for(auto&r:c)r.fill(false);clearLaneStorageNav(n-1);lanes.erase(lanes.begin()+old);laneSelected=std::min(old,(int)lanes.size()-1);selectedTrack=std::min(TRACKS-1,laneSelected);selectedBar=std::clamp(selectedBar,0,std::max(0,activeBars-1));audioSelected15=-1;fineClipboard17.clear();clip12.clear();clearMulti();layout11(win);layoutPanels15(win);sync16(win);InvalidateRect(win,nullptr,FALSE);}

// Render the basic kick ourselves instead of cutting the complete master buffer at 300 ms.
// This keeps kick and bass on the exact same sample and gives the kick a true zero-ending envelope.
void renderNav(std::vector<int16_t>&a,int start){
    struct Hit{int lane,bar,step;};std::vector<Hit> hits;
    bool anySolo=false;for(auto&ln:lanes)if(ln.solo)anySolo=true;
    for(int l=0;l<(int)lanes.size();++l){if(lanes[l].type!=LaneType::Drums||kicks15[l].enabled||lanes[l].mute||(anySolo&&!lanes[l].solo))continue;for(int b=std::max(0,start);b<activeBars;++b){auto&d=drumForLane11(l,b);for(int s=0;s<STEPS;++s)if(d[0][s]){hits.push_back({l,b,s});d[0][s]=false;}}}
    render16(a,start);
    for(auto&h:hits)drumForLane11(h.lane,h.bar)[0][h.step]=true;
    if(a.empty()||hits.empty())return;
    const int bpmNow=std::max(60,(int)bpm);const long long stepFrames=std::max<long long>(1,(long long)(SR*60.0/bpmNow/4.0));const long long barFrames=stepFrames*STEPS;const long long kickFrames=(long long)(0.30*SR);const long long fadeFrames=std::max<long long>(1,(long long)(0.020*SR));
    for(auto&h:hits){long long st=((long long)h.bar-start)*barFrames+(long long)h.step*stepFrames;if(st<0)continue;double ph=0.0,vol=lanes[h.lane].volume/100.0;for(long long q=0;q<kickFrames;++q){size_t j=(size_t)(st+q)*2;if(j+1>=a.size())break;double t=(double)q/SR,f=48.0+110.0*std::exp(-t*35.0);ph+=2.0*PI*f/SR;double attack=std::min(1.0,(double)q/std::max<long long>(1,(long long)(0.0015*SR)));double tail=q<kickFrames-fadeFrames?1.0:(double)(kickFrames-q)/fadeFrames;tail=std::clamp(tail,0.0,1.0);tail=tail*tail*(3.0-2.0*tail);double body=std::sin(ph)*std::exp(-t*16.0);double click=.12*std::sin(2.0*PI*900.0*t)*std::exp(-t*90.0);double x=(body+click)*attack*tail*0.20*vol;int add=(int)std::lrint(x*32767.0);a[j]=(int16_t)std::clamp((int)a[j]+add,-32768,32767);a[j+1]=(int16_t)std::clamp((int)a[j+1]+add,-32768,32767);}}
}
void playNav(){if(playing){stopAudio();return;}int start=loopOnNav?loopStartNav:cursorBar;start=std::clamp(start,0,std::max(0,activeBars-1));playStartBar=start;renderNav(playBuffer,start);if(loopOnNav){int bpmNow=std::max(60,(int)bpm);double secBar=240.0/(double)bpmNow;size_t frames=(size_t)(secBar*SR)*std::max(1,loopEndNav-loopStartNav+1),samples=frames*2;if(playBuffer.size()>samples)playBuffer.resize(samples);}WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);if(loopOnNav){waveHdr.dwFlags=WHDR_BEGINLOOP|WHDR_ENDLOOP;waveHdr.dwLoops=0xFFFFFFFFu;}if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void exportNav(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderNav(a,0);if(a.empty()){MessageBoxW(win,L"Rien a exporter.",L"Boomify",MB_OK|MB_ICONWARNING);return;}std::ofstream o(p,std::ios::binary);if(!o){MessageBoxW(win,L"Impossible de creer le WAV.",L"Boomify",MB_OK|MB_ICONERROR);return;}uint32_t ds=(uint32_t)(a.size()*sizeof(int16_t)),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);o.close();MessageBoxW(win,L"Export WAV termine.",L"Boomify",MB_OK|MB_ICONINFORMATION);}
}

LRESULT CALLBACK proc_v17_nav(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_PAINT){LRESULT r=proc_v17(h,m,w,l);HDC d=GetDC(h);if(d){drawNavTools(d);ReleaseDC(h,d);}return r;}if(m==WM_MOUSEWHEEL||m==WM_MOUSEHWHEEL){POINT q{GET_X_LPARAM(l),GET_Y_LPARAM(l)};ScreenToClient(h,&q);if(inside(timeline10,q)){short delta=GET_WHEEL_DELTA_WPARAM(w);bool ctrl=(GET_KEYSTATE_WPARAM(w)&MK_CONTROL)!=0;if(ctrl)zoomNav(delta>0?1:-1);else scrollTimelineNav(delta<0?1:-1);return 0;}}if(m==WM_LBUTTONDOWN){for(int i=0;i<(int)lanes.size();++i){if(inside(muteNavR[i],p)){lanes[i].mute=!lanes[i].mute;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(soloNavR[i],p)){lanes[i].solo=!lanes[i].solo;InvalidateRect(h,nullptr,FALSE);return 0;}}if(inside(addTrack15,p)){addTrackNav(h,p);return 0;}if(inside(removeTrack15,p)){removeTrackNav();return 0;}if(inside(playR,p)){playNav();return 0;}if(inside(wavR,p)){exportNav();return 0;}if(inside(setLoopNavR,p)){setLoopNavFromSelection();return 0;}if(inside(loopNavR,p)){if(loopOnNav)loopOnNav=false;else setLoopNavFromSelection();InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(fitNavR,p)){fitTimelineNav();return 0;}if(inside(zoomOutNavR,p)){zoomNav(-1);return 0;}if(inside(zoomInNavR,p)){zoomNav(1);return 0;}}if(m==WM_KEYDOWN){bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0;if(w==VK_SPACE){playNav();return 0;}if(ctrl&&w=='L'){if(loopOnNav)loopOnNav=false;else setLoopNavFromSelection();InvalidateRect(h,nullptr,FALSE);return 0;}if(ctrl&&(w==VK_OEM_PLUS||w==VK_ADD)){zoomNav(1);return 0;}if(ctrl&&(w==VK_OEM_MINUS||w==VK_SUBTRACT)){zoomNav(-1);return 0;}}return proc_v17(h,m,w,l);}
