// Boomify V17 - Alpha 6 persistence layer
#define BOOMIFY_V16_NO_ENTRY
#include "main_v16.cpp"
#undef BOOMIFY_V16_NO_ENTRY

namespace {
void writeString17(std::ofstream& o,const std::wstring& s){std::string n=narrowName(s);o<<n.size()<<' ';o.write(n.data(),(std::streamsize)n.size());o<<'\n';}
bool readString17(std::ifstream& i,std::wstring& s){size_t n=0;if(!(i>>n)||n>4096)return false;i.get();std::string z(n,' ');if(n)i.read(&z[0],(std::streamsize)n);i.ignore(4096,'\n');s=widenName(z);return(bool)i;}
void save17(){auto p=dialog(true,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return;std::ofstream o(p,std::ios::binary);if(!o){MessageBoxW(win,L"Impossible d'enregistrer le projet.",L"Boomify",MB_OK|MB_ICONERROR);return;}o<<"BOOMIFY17\n"<<bpm<<' '<<master<<' '<<masterOn15<<' '<<activeBars<<' '<<lanes.size()<<'\n';for(int l=0;l<(int)lanes.size();++l){o<<(int)lanes[l].type<<' '<<lanes[l].mute<<' '<<lanes[l].solo<<' '<<lanes[l].volume<<' '<<(int)sound9[l]<<' '<<(unsigned long)colors15[l]<<'\n';writeString17(o,lanes[l].name);o<<kicks15[l].enabled<<' '<<kicks15[l].pitch<<' '<<kicks15[l].decay<<' '<<kicks15[l].punch<<' '<<kicks15[l].drive<<'\n';o<<rack11[l].size()<<'\n';for(auto&f:rack11[l])o<<(int)f.type<<' '<<f.on<<' '<<f.amount<<'\n';o<<samples15[l].bar<<' ';writeString17(o,samples15[l].path);}for(int l=0;l<(int)lanes.size();++l)for(int b=0;b<activeBars;++b){if(lanes[l].type==LaneType::Drums)writeDrum14(o,drumForLane11(l,b));else if(lanes[l].type==LaneType::Instrument)writeBits14(o,noteForLane(l,b));}for(int l=0;l<(int)lanes.size();++l)for(int b=0;b<activeBars;++b){auto&v=fine16[l][b];o<<v.size();for(auto&n:v)o<<' '<<n.row<<' '<<n.start<<' '<<n.dur;o<<'\n';}MessageBoxW(win,L"Projet enregistre.",L"Boomify",MB_OK|MB_ICONINFORMATION);}
bool open17(){auto p=dialog(false,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return false;std::ifstream i(p,std::ios::binary);std::string magic;if(!(i>>magic)||magic!="BOOMIFY17"){MessageBoxW(win,L"Ce projet n'utilise pas le nouveau format Boomify Alpha 6.",L"Boomify",MB_OK|MB_ICONWARNING);return false;}int nl=0,on=1;if(!(i>>bpm>>master>>on>>activeBars>>nl)||nl<1||nl>V6_MAX_TRACKS||activeBars<1||activeBars>MAX_BARS){MessageBoxW(win,L"Projet endommage.",L"Boomify",MB_OK|MB_ICONERROR);return false;}masterOn15=on!=0;stopAudio();lanes.clear();for(auto&r:rack11)r.clear();for(auto&s:samples15)s=Sample15{};for(auto&k:kicks15)k=Kick15{};for(auto&c:colors15)c=0;for(auto&byLane:fine16)for(auto&v:byLane)v.clear();for(int b=0;b<MAX_BARS;++b){clearDrum(b);clearNote(bass[b]);clearNote(melody[b]);}for(auto&a:extraNotes)for(auto&c:a)clearNote(c);for(auto&a:extraDrums11)for(auto&c:a)for(auto&r:c)r.fill(false);for(int l=0;l<nl;++l){int ty=1,mu=0,so=0,vol=100,snd=3,ke=0;unsigned long col=0;if(!(i>>ty>>mu>>so>>vol>>snd>>col))return false;std::wstring name;if(!readString17(i,name))return false;lanes.push_back({name,(LaneType)std::clamp(ty,0,2),mu!=0,so!=0,std::clamp(vol,0,100)});sound9[l]=(Sound9)std::clamp(snd,0,14);colors15[l]=(COLORREF)col;if(!(i>>ke>>kicks15[l].pitch>>kicks15[l].decay>>kicks15[l].punch>>kicks15[l].drive))return false;kicks15[l].enabled=ke!=0;int nf=0;if(!(i>>nf))return false;nf=std::clamp(nf,0,64);for(int f=0;f<nf;++f){int t=0,fo=1,am=50;i>>t>>fo>>am;rack11[l].push_back({(FxType11)std::clamp(t,0,12),fo!=0,std::clamp(am,0,100)});}int sb=-1;if(!(i>>sb))return false;std::wstring sp;if(!readString17(i,sp))return false;samples15[l].bar=sb;samples15[l].path=sp;if(sb>=0&&!sp.empty())loadWav15(sp,samples15[l].pcm);}for(int l=0;l<nl;++l)for(int b=0;b<activeBars;++b){if(lanes[l].type==LaneType::Drums)readDrum14(i,drumForLane11(l,b));else if(lanes[l].type==LaneType::Instrument)readBits14(i,noteForLane(l,b));}for(int l=0;l<nl;++l)for(int b=0;b<activeBars;++b){size_t n=0;if(!(i>>n)||n>4096)return false;for(size_t q=0;q<n;++q){FineNote16 x{};if(!(i>>x.row>>x.start>>x.dur))return false;x.row=std::clamp(x.row,0,NOTES-1);x.start=std::clamp(x.start,0,FINE_TICKS16-1);x.dur=std::clamp(x.dur,1,FINE_TICKS16-x.start);fine16[l][b].push_back(x);}}laneSelected=selectedTrack=selectedBar=scrollBar=cursorBar=0;audioSelected15=-1;layout11(win);layoutPanels15(win);sync16(win);InvalidateRect(win,nullptr,FALSE);return true;}
void export17(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;render16(a,0);if(a.empty()){MessageBoxW(win,L"Rien a exporter.",L"Boomify",MB_OK|MB_ICONWARNING);return;}std::ofstream o(p,std::ios::binary);if(!o){MessageBoxW(win,L"Impossible de creer le WAV.",L"Boomify",MB_OK|MB_ICONERROR);return;}uint32_t ds=(uint32_t)(a.size()*sizeof(int16_t)),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);o.close();MessageBoxW(win,L"Export WAV termine.",L"Boomify",MB_OK|MB_ICONINFORMATION);}
void refreshModernHitRects17(HWND h){sync16(h);RECT c{};GetClientRect(h,&c);HDC screen=GetDC(h);if(!screen)return;HDC d=CreateCompatibleDC(screen);HBITMAP bm=CreateCompatibleBitmap(screen,std::max<LONG>(1,c.right),std::max<LONG>(1,c.bottom));HGDIOBJ old=SelectObject(d,bm);header16(d,c);tracks16(d);inspector16(d);editorFrame16(d,c);drawFineEditor16(d);SelectObject(d,old);DeleteObject(bm);DeleteDC(d);ReleaseDC(h,screen);}
// Canonical drum hit-test: use the exact geometry formula used by drawEditor11 instead of stale dp[] rectangles.
bool drumHit17(POINT p,int&row,int&step){if(!editorOpen||laneSelected<0||laneSelected>=(int)lanes.size()||lanes[laneSelected].type!=LaneType::Drums)return false;const int gridTop=(int)editorArea11.top+42,gridBottom=(int)editorArea11.bottom-12,labelW=86;const int gridRight=(int)editorArea11.right-14;if(gridRight<=labelW||gridBottom<=gridTop||p.x<labelW||p.x>=gridRight||p.y<gridTop||p.y>=gridBottom)return false;const int rh=std::max(12,(gridBottom-gridTop)/std::max(1,DR));const int cw=std::max(8,((int)editorArea11.right-labelW-14)/STEPS);row=(p.y-gridTop)/rh;step=(p.x-labelW)/cw;if(row<0||row>=DR||step<0||step>=STEPS)return false;RECT exact{(LONG)(labelW+step*cw),(LONG)(gridTop+row*rh),(LONG)(labelW+(step+1)*cw-1),(LONG)std::min(gridBottom,gridTop+(row+1)*rh-1)};return inside(exact,p);}
LRESULT CALLBACK proc_v17(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_LBUTTONDOWN||m==WM_RBUTTONDOWN)refreshModernHitRects17(h);if(m==WM_LBUTTONDOWN){if(inside(save14,p)){save17();return 0;}if(inside(open14,p)){open17();return 0;}if(inside(wavR,p)){export17();return 0;}int dr=-1,ds=-1;if(drumHit17(p,dr,ds)){auto&clip=drumForLane11(laneSelected,std::clamp(selectedBar,0,MAX_BARS-1));clip[dr][ds]=!clip[dr][ds];InvalidateRect(h,nullptr,FALSE);return 0;}}if(m==WM_KEYDOWN&&(GetKeyState(VK_CONTROL)&0x8000)){if(w=='S'){save17();return 0;}if(w=='O'){open17();return 0;}}return proc_v16(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int){for(int i=0;i<V6_MAX_TRACKS;i++)colors15[i]=defaultColor15(i);v6Fresh();editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;master=100;WNDCLASSW wc{};wc.lpfnWndProc=proc_v17;wc.hInstance=hi;wc.lpszClassName=L"BoomifyAlpha6Persist";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);wc.style=CS_DBLCLKS;RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Studio - Alpha 6 Neon",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1440,900,nullptr,nullptr,hi,nullptr);if(!win)return 1;sync16(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wParam;}
