// Boomify Alpha 5 - modern functional DAW workspace + native FX rack
#define BOOMIFY_V11_INCLUDE
#include "main_v10.cpp"
#undef BOOMIFY_V11_INCLUDE

namespace {
enum class FxType11{SoftClip,HardClip,Overdrive,Saturation,Wavefold,Bitcrush,Compressor,Limiter,Transient,LowPass,HighPass,Delay,Reverb};
struct Fx11{FxType11 type=FxType11::SoftClip;bool on=true;int amount=50;};
struct DrumVoice11{int lane=0;Voice voice{};};
std::array<std::vector<Fx11>,V6_MAX_TRACKS> rack11;
std::array<std::array<DrumClip,MAX_BARS>,V6_MAX_TRACKS-3> extraDrums11{};
std::vector<RECT> fxRects11; RECT addFx11{}; int fxScroll11=0; RECT editorArea11{};
DrumClip& drumForLane11(int lane,int bar){if(lane==0)return drums[bar];return extraDrums11[std::clamp(lane-3,0,V6_MAX_TRACKS-4)][std::clamp(bar,0,MAX_BARS-1)];}
bool laneUsed11(int lane,int bar){if(lane<0||lane>=(int)lanes.size()||bar<0||bar>=MAX_BARS)return false;if(lanes[lane].type==LaneType::Drums){auto&c=drumForLane11(lane,bar);for(auto&r:c)for(bool x:r)if(x)return true;return false;}if(lanes[lane].type==LaneType::Audio)return false;return usedNote(noteForLane(lane,bar));}
const wchar_t* fxName11(FxType11 t){switch(t){case FxType11::SoftClip:return L"Soft Clip";case FxType11::HardClip:return L"Hard Clip";case FxType11::Overdrive:return L"Overdrive";case FxType11::Saturation:return L"Saturation";case FxType11::Wavefold:return L"Wavefold";case FxType11::Bitcrush:return L"Bitcrush";case FxType11::Compressor:return L"Compressor";case FxType11::Limiter:return L"Limiter";case FxType11::Transient:return L"Transient";case FxType11::LowPass:return L"Low-pass";case FxType11::HighPass:return L"High-pass";case FxType11::Delay:return L"Delay";default:return L"Reverb";}}
COLORREF fxColor11(FxType11 t){int v=(int)t;return v<=5?RGB(236,103,73):v<=8?RGB(75,164,219):v<=10?RGB(70,195,151):RGB(167,104,226);}
void layout11(HWND h){layoutV6(h);RECT c;GetClientRect(h,&c);int right=std::max(860,(int)c.right-330);int editorH=editorOpen?std::clamp((int)(c.bottom*.34),260,390):0;int editorTop=editorOpen?std::max(360,(int)c.bottom-editorH):(int)c.bottom;trackList10={0,116,220,(LONG)editorTop};timeline10={220,116,(LONG)right,(LONG)editorTop};inspector10={(LONG)right,70,c.right,c.bottom};browser10={0,(LONG)editorTop,(LONG)right,c.bottom};editorArea11={0,(LONG)editorTop,(LONG)right,c.bottom};int n=std::max(1,(int)lanes.size()),avail=std::max(1,editorTop-118),rh=std::max(42,std::min(78,avail/n));for(int i=0;i<V6_MAX_TRACKS;i++){laneHeadR[i]={0,0,0,0};laneMuteR[i]={0,0,0,0};soloR[i]={0,0,0,0};laneVolR[i]={0,0,0,0};}for(int i=0;i<n;i++){int y=118+i*rh;laneHeadR[i]={8,(LONG)y,212,(LONG)std::min(editorTop,y+rh-2)};laneMuteR[i]={150,(LONG)(y+8),174,(LONG)(y+30)};soloR[i]={180,(LONG)(y+8),204,(LONG)(y+30)};laneVolR[i]={18,(LONG)std::max(y+33,y+rh-13),132,(LONG)std::max(y+39,y+rh-7)};}addTrackR={12,78,104,108};removeTrackR={110,78,194,108};renameTrackR={200,78,294,108};}
double processFx11(double x,const Fx11&f,double&state){if(!f.on)return x;double a=f.amount/100.0;switch(f.type){case FxType11::SoftClip:return tanh(x*(1+a*8));case FxType11::HardClip:{double l=1-a*.9;return std::clamp(x,-l,l)/std::max(.1,l);}case FxType11::Overdrive:return atan(x*(1+a*14))*.75;case FxType11::Saturation:return x/(1+std::abs(x)*(a*5));case FxType11::Wavefold:return sin(x*(1+a*8)*2.2);case FxType11::Bitcrush:{double lv=std::max(4.0,260.0*(1-a));return floor(x*lv)/lv;}case FxType11::Compressor:{double th=.8-a*.6,ax=std::abs(x);if(ax>th)x=(x<0?-1:1)*(th+(ax-th)*(.5-a*.4));return x;}case FxType11::Limiter:{double l=.95-a*.45;return std::clamp(x,-l,l);}case FxType11::Transient:return x*(1+a*.8);case FxType11::LowPass:{double k=.02+(1-a)*.45;state+=k*(x-state);return state;}case FxType11::HighPass:{double k=.02+(1-a)*.45;state+=k*(x-state);return x-state;}case FxType11::Delay:{double y=x+state*a*.7;state=state*.997+x*.003;return y;}case FxType11::Reverb:{double y=x+state*a*.5;state=state*.993+x*.007;return y;}}return x;}
void renderRange11(std::vector<int16_t>&out,int start){start=std::clamp(start,0,activeBars-1);int step=std::max(1,(int)(SR*60.0/bpm/4.0));size_t frames=(size_t)step*STEPS*(activeBars-start);out.assign(frames*2,0);std::vector<DrumVoice11>dv;std::vector<Voice9>nv;std::array<std::array<double,16>,V6_MAX_TRACKS>st{};bool solo=false;for(auto&l:lanes)if(l.solo)solo=true;for(size_t f=0;f<frames;f++){if(f%step==0){int g=(int)(f/step),b=start+g/STEPS,s=g%STEPS;for(int l=0;l<(int)lanes.size();l++){if(lanes[l].mute||(solo&&!lanes[l].solo)||lanes[l].type==LaneType::Audio)continue;if(lanes[l].type==LaneType::Drums){auto&clip=drumForLane11(l,b);for(int r=0;r<DR;r++)if(clip[r][s])dv.push_back({l,{r,0}});}else{auto&clip=noteForLane(l,b);int base=familyOf(sound9[l])==Family9::Bass?47:71;for(int r=0;r<NOTES;r++)if(clip[r][s])nv.push_back({sound9[l],l,base-r});}}}std::array<double,V6_MAX_TRACKS>mix{};for(auto&q:dv)if(q.lane>=0&&q.lane<(int)lanes.size())mix[q.lane]+=sample(q.voice);for(auto&q:nv)if(q.lane>=0&&q.lane<(int)lanes.size())mix[q.lane]+=sample9(q);double mm=0;for(int l=0;l<(int)lanes.size();l++){if(lanes[l].mute||(solo&&!lanes[l].solo))continue;double y=mix[l]*(lanes[l].volume/100.0);for(size_t j=0;j<rack11[l].size();j++)y=processFx11(y,rack11[l][j],st[l][std::min<size_t>(j,15)]);mm+=y;}dv.erase(std::remove_if(dv.begin(),dv.end(),[](const DrumVoice11&q){return!alive(q.voice);}),dv.end());nv.erase(std::remove_if(nv.begin(),nv.end(),[](const Voice9&q){return!alive9(q);}),nv.end());int16_t z=(int16_t)(std::clamp(mm*.20*(master/100.0),-1.0,1.0)*32767);out[f*2]=out[f*2+1]=z;}}
void play11(){if(playing){stopAudio();return;}playStartBar=cursorBar;renderRange11(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutWrite(wave,&waveHdr,sizeof(waveHdr));playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export11(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderRange11(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
void addFxMenu11(HWND h,POINT p){if(laneSelected<0||laneSelected>=(int)lanes.size())return;HMENU root=CreatePopupMenu();for(int i=0;i<13;i++)AppendMenuW(root,MF_STRING,67001+i,fxName11((FxType11)i));POINT s=p;ClientToScreen(h,&s);int cmd=TrackPopupMenu(root,TPM_RETURNCMD|TPM_RIGHTBUTTON,s.x,s.y,0,h,nullptr);DestroyMenu(root);if(cmd>=67001&&cmd<67014){rack11[laneSelected].push_back({(FxType11)(cmd-67001),true,50});InvalidateRect(h,nullptr,FALSE);}}
void drawTop11(HDC d,RECT c){fill(d,{0,0,c.right,70},RGB(15,17,21));label(d,L"BOOMIFY",18,16,17,RGB(244,245,247),FW_BOLD);label(d,L"ALPHA 5",20,42,7,RGB(237,105,75),FW_BOLD);RECT play{(LONG)(c.right/2-42),14,(LONG)(c.right/2+42),54};fill(d,play,RGB(235,103,74));label(d,playing?L"STOP":L"PLAY",play.left+23,play.top+13,10,RGB(255,255,255),FW_BOLD);playR=play;std::wstring b=L"BPM  "+std::to_wstring(bpm);label(d,b.c_str(),c.right/2+62,29,9,RGB(190,193,200),FW_BOLD);wavR={c.right-118,18,c.right-18,52};fill(d,wavR,RGB(36,39,46));label(d,L"EXPORT WAV",wavR.left+14,wavR.top+11,8,RGB(220,222,226),FW_BOLD);line(d,0,69,c.right,69,RGB(40,43,50));}
void drawTracks11(HDC d){fill(d,trackList10,RGB(22,24,29));for(int i=0;i<(int)lanes.size();i++){RECT r=laneHeadR[i];if(r.bottom<=r.top)continue;COLORREF col=lanes[i].type==LaneType::Drums?RGB(68,201,158):i==1?RGB(83,139,226):RGB(235,111,78);fill(d,r,i==laneSelected?RGB(36,39,46):RGB(27,29,35));fill(d,{r.left,r.top,r.left+4,r.bottom},col);label(d,lanes[i].name.c_str(),r.left+12,r.top+9,9,RGB(238,239,242),FW_BOLD);if(lanes[i].type==LaneType::Instrument)label(d,soundName9(sound9[i]),r.left+12,r.top+26,7,col,FW_BOLD);else if(lanes[i].type==LaneType::Drums)label(d,L"Drum Rack",r.left+12,r.top+26,7,col,FW_BOLD);fill(d,laneMuteR[i],lanes[i].mute?col:RGB(42,45,52));label(d,L"M",laneMuteR[i].left+8,laneMuteR[i].top+6,7,RGB(230,231,234),FW_BOLD);fill(d,soloR[i],lanes[i].solo?RGB(229,184,65):RGB(42,45,52));label(d,L"S",soloR[i].left+8,soloR[i].top+6,7,RGB(230,231,234),FW_BOLD);fill(d,laneVolR[i],RGB(14,16,20));RECT q=laneVolR[i];q.right=q.left+(q.right-q.left)*lanes[i].volume/100;fill(d,q,col);}}
RECT cell11(int lane,int v){int w=std::max(1,(int)(timeline10.right-timeline10.left));int x1=(int)timeline10.left+(int)((long long)v*w/visibleBars),x2=(int)timeline10.left+(int)((long long)(v+1)*w/visibleBars);return{(LONG)x1,laneHeadR[lane].top,(LONG)std::max(x1+1,x2-1),laneHeadR[lane].bottom};}
void drawTimeline11(HDC d){fill(d,timeline10,RGB(20,22,27));int w=std::max(1,(int)(timeline10.right-timeline10.left));for(int v=0;v<visibleBars;v++){int b=scrollBar+v,x=(int)timeline10.left+(int)((long long)v*w/visibleBars);line(d,x,timeline10.top,x,timeline10.bottom,RGB(43,46,53));if(b<activeBars){std::wstring n=std::to_wstring(b+1);label(d,n.c_str(),x+7,timeline10.top+7,7,RGB(107,111,120));}}for(int i=0;i<(int)lanes.size();i++){line(d,timeline10.left,laneHeadR[i].bottom,timeline10.right,laneHeadR[i].bottom,RGB(39,42,49));for(int v=0;v<visibleBars;v++){int b=scrollBar+v;if(b>=activeBars)continue;RECT r=cell11(i,v);if(laneUsed11(i,b)){COLORREF col=lanes[i].type==LaneType::Drums?RGB(55,157,126):i==1?RGB(65,111,181):RGB(195,91,64);RECT clip{r.left+3,r.top+6,r.right-3,r.bottom-6};fill(d,clip,col);}}}for(auto&q:multiSelection){if(q.track<0||q.track>=(int)lanes.size()||q.bar<scrollBar||q.bar>=scrollBar+visibleBars)continue;RECT r=cell11(q.track,q.bar-scrollBar);line(d,r.left+2,r.top+2,r.right-2,r.top+2,RGB(255,255,255),2);line(d,r.left+2,r.bottom-3,r.right-2,r.bottom-3,RGB(255,255,255),2);line(d,r.left+2,r.top+2,r.left+2,r.bottom-2,RGB(255,255,255),2);line(d,r.right-3,r.top+2,r.right-3,r.bottom-2,RGB(255,255,255),2);}}
void drawInspector11(HDC d){fill(d,inspector10,RGB(20,22,27));int x=(int)inspector10.left+18;label(d,L"INSPECTEUR",x,91,7,RGB(118,122,131),FW_BOLD);if(laneSelected<0||laneSelected>=(int)lanes.size())return;label(d,lanes[laneSelected].name.c_str(),x,112,15,RGB(242,243,245),FW_BOLD);int y=148;if(lanes[laneSelected].type==LaneType::Instrument){instrument10={(LONG)x,(LONG)y,inspector10.right-18,(LONG)(y+48)};fill(d,instrument10,RGB(31,34,40));label(d,L"INSTRUMENT",x+12,y+8,7,RGB(115,120,129),FW_BOLD);label(d,soundName9(sound9[laneSelected]),x+12,y+26,10,RGB(235,111,78),FW_BOLD);y+=66;}else instrument10={0,0,0,0};label(d,L"CHAINE D'EFFETS",x,y,7,RGB(118,122,131),FW_BOLD);y+=20;fxRects11.clear();auto&r=rack11[laneSelected];for(int i=fxScroll11;i<(int)r.size()&&y+58<(int)inspector10.bottom-52;i++){RECT q{(LONG)x,(LONG)y,inspector10.right-18,(LONG)(y+54)};fxRects11.push_back(q);COLORREF col=fxColor11(r[i].type);fill(d,q,RGB(31,34,40));fill(d,{q.left,q.top,q.left+4,q.bottom},r[i].on?col:RGB(70,73,80));label(d,fxName11(r[i].type),q.left+13,q.top+9,9,RGB(237,238,241),FW_BOLD);RECT bar{q.left+13,q.top+34,q.right-13,q.top+41};fill(d,bar,RGB(13,15,19));RECT f=bar;f.right=f.left+(f.right-f.left)*r[i].amount/100;fill(d,f,col);std::wstring pct=std::to_wstring(r[i].amount)+L"%";label(d,pct.c_str(),q.right-46,q.top+8,7,RGB(150,154,162),FW_BOLD);y+=62;}addFx11={(LONG)x,(LONG)std::min(y+5,(int)inspector10.bottom-43),inspector10.right-18,(LONG)std::min(y+40,(int)inspector10.bottom-8)};fill(d,addFx11,RGB(34,37,44));label(d,L"+  AJOUTER UN EFFET",addFx11.left+17,addFx11.top+11,8,RGB(201,203,208),FW_BOLD);}
void drawEditor11(HDC d){if(!editorOpen)return;fill(d,editorArea11,RGB(17,19,23));int top=(int)editorArea11.top;fill(d,{0,(LONG)top,editorArea11.right,(LONG)(top+38)},RGB(25,27,33));bool isDrum=laneSelected>=0&&laneSelected<(int)lanes.size()&&lanes[laneSelected].type==LaneType::Drums;std::wstring title=isDrum?L"DRUM EDITOR":L"PIANO ROLL";title+=L"  /  BLOC "+std::to_wstring(selectedBar+1);if(laneSelected>=0&&laneSelected<(int)lanes.size())title+=L"  /  "+lanes[laneSelected].name;label(d,title.c_str(),18,top+13,8,RGB(207,209,214),FW_BOLD);if(laneSelected>=0&&laneSelected<(int)lanes.size()&&lanes[laneSelected].type==LaneType::Audio){label(d,L"Import / enregistrement audio bientot disponible",18,top+68,10,RGB(130,134,142));return;}int rows=isDrum?DR:NOTES;int gridTop=top+42,gridBottom=(int)editorArea11.bottom-12,labelW=86;int rh=std::max(12,(gridBottom-gridTop)/std::max(1,rows));int cw=std::max(8,((int)editorArea11.right-labelW-14)/STEPS);for(int r=0;r<rows;r++){int y=gridTop+r*rh;std::wstring nm=isDrum?(r==0?L"KICK":r==1?L"SNARE":r==2?L"CLAP":L"HI-HAT"):L"NOTE "+std::to_wstring(rows-r);label(d,nm.c_str(),14,y+std::max(2,rh/2-5),7,RGB(119,123,132));for(int s=0;s<STEPS;s++){RECT q{(LONG)(labelW+s*cw),(LONG)y,(LONG)(labelW+(s+1)*cw-1),(LONG)std::min(gridBottom,y+rh-1)};bool on=isDrum?drumForLane11(laneSelected,selectedBar)[r][s]:noteForLane(laneSelected,selectedBar)[r][s];fill(d,q,on?RGB(230,102,73):RGB(37,40,47));if(isDrum)dp[r][s]=q;else np[r][s]=q;}}}
void draw11(HDC d,RECT c){fill(d,c,RGB(17,19,23));drawTop11(d,c);fill(d,{0,70,inspector10.left,116},RGB(24,26,31));button(d,addTrackR,L"+ PISTE");button(d,removeTrackR,L"SUPPR.");button(d,renameTrackR,L"RENOMMER");drawTracks11(d);drawTimeline11(d);drawEditor11(d);drawInspector11(d);}
bool hitTimeline11(POINT p,int&lane,int&bar){if(!inside(timeline10,p))return false;int w=std::max(1,(int)(timeline10.right-timeline10.left));int v=(int)((long long)(p.x-(int)timeline10.left)*visibleBars/w);bar=scrollBar+v;if(bar<0||bar>=activeBars)return false;for(int i=0;i<(int)lanes.size();i++)if(p.y>=laneHeadR[i].top&&p.y<laneHeadR[i].bottom){lane=i;return true;}return false;}
void editCell11(POINT p){if(!editorOpen||!inside(editorArea11,p)||p.y<editorArea11.top+38||laneSelected<0||laneSelected>=(int)lanes.size())return;if(lanes[laneSelected].type==LaneType::Drums){auto&c=drumForLane11(laneSelected,selectedBar);for(int r=0;r<DR;r++)for(int s=0;s<STEPS;s++)if(inside(dp[r][s],p)){c[r][s]=!c[r][s];InvalidateRect(win,nullptr,FALSE);return;}}else if(lanes[laneSelected].type==LaneType::Instrument){auto&n=noteForLane(laneSelected,selectedBar);for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)if(inside(np[r][s],p)){n[r][s]=!n[r][s];InvalidateRect(win,nullptr,FALSE);return;}}}
LRESULT CALLBACK proc_v11(HWND h,UINT m,WPARAM wp,LPARAM lp){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(m==WM_SIZE){proc_v9(h,m,wp,lp);layout11(h);InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDOWN){if(inside(playR,p)){play11();return 0;}if(inside(wavR,p)){export11();return 0;}if(inside(addTrackR,p)){addTrack(h);layout11(h);return 0;}if(inside(removeTrackR,p)){removeTrack();layout11(h);return 0;}if(inside(renameTrackR,p)){renameTrack();return 0;}if(inside(editorArea11,p)){editCell11(p);return 0;}if(inside(inspector10,p)&&laneSelected>=0){if(laneSelected>0&&inside(instrument10,p)){chooseInstrument9(h,laneSelected,p);return 0;}if(inside(addFx11,p)){addFxMenu11(h,p);return 0;}for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],p)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected][idx].on=!rack11[laneSelected][idx].on;InvalidateRect(h,nullptr,FALSE);return 0;}}return 0;}int lane,bar;if(hitTimeline11(p,lane,bar)){laneSelected=lane;selectedTrack=std::min(TRACKS-1,lane);selectedBar=bar;clearMulti();addMulti(lane,bar);InvalidateRect(h,nullptr,FALSE);return 0;}}if(m==WM_RBUTTONDOWN){int lane,bar;if(hitTimeline11(p,lane,bar)){showV6ClipMenu(h,p,lane,bar);return 0;}if(inside(inspector10,p)&&laneSelected>=0){for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],p)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected].erase(rack11[laneSelected].begin()+idx);InvalidateRect(h,nullptr,FALSE);return 0;}}}}if(m==WM_MOUSEWHEEL&&laneSelected>=0&&laneSelected<(int)lanes.size()){POINT sp{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};ScreenToClient(h,&sp);for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],sp)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected][idx].amount=std::clamp(rack11[laneSelected][idx].amount+(GET_WHEEL_DELTA_WPARAM(wp)>0?5:-5),0,100);InvalidateRect(h,nullptr,FALSE);return 0;}}}if(m==WM_KEYDOWN&&wp==VK_SPACE){play11();return 0;}return proc_v9(h,m,wp,lp);}
}
#ifndef BOOMIFY_V12_INCLUDE
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v11;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV11";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 5",WS_OVERLAPPEDWINDOW,0,0,1600,960,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;layout11(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
#endif
