// Boomify V6 - dynamic track workspace
// V6 extends the proven V5 timeline engine instead of bypassing it.
#define BOOMIFY_V5_NO_ENTRY
#include "main_v5.cpp"
#undef BOOMIFY_V5_NO_ENTRY

namespace {
constexpr int V6_MAX_TRACKS=16;
enum class LaneType{Drums,Instrument,Audio};
struct Lane{std::wstring name;LaneType type=LaneType::Instrument;bool mute=false,solo=false;int volume=80;};
std::vector<Lane> lanes={{L"Drums",LaneType::Drums,false,false,85},{L"Bass",LaneType::Instrument,false,false,80},{L"Synth",LaneType::Instrument,false,false,80}};
int laneSelected=0; RECT addTrackR{},removeTrackR{},renameTrackR{},soloR[V6_MAX_TRACKS]{},laneMuteR[V6_MAX_TRACKS]{},laneVolR[V6_MAX_TRACKS]{},laneHeadR[V6_MAX_TRACKS]{};
std::array<std::array<NoteClip,MAX_BARS>,V6_MAX_TRACKS-3> extraNotes{};
void layoutV6(HWND h);
NoteClip& noteForLane(int lane,int bar){if(lane==1)return bass[bar];if(lane==2)return melody[bar];return extraNotes[lane-3][bar];}
bool laneUsed(int lane,int bar){if(lane==0)return usedDrum(bar);if(lanes[lane].type==LaneType::Audio)return false;return usedNote(noteForLane(lane,bar));}
const wchar_t* typeLabel(LaneType t){return t==LaneType::Drums?L"BATTERIE":t==LaneType::Audio?L"AUDIO":L"INSTRUMENT";}
const int PICK_DRUM=62001,PICK_INST=62002,PICK_AUDIO=62003,PICK_CANCEL=62004; int pickChoice=0; HWND picker=nullptr;
LRESULT CALLBACK pickerProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CREATE){CreateWindowW(L"STATIC",L"AJOUTER UNE PISTE",WS_CHILD|WS_VISIBLE,24,20,320,28,h,nullptr,nullptr,nullptr);CreateWindowW(L"STATIC",L"Choisis ce que cette piste doit faire.",WS_CHILD|WS_VISIBLE,24,52,330,22,h,nullptr,nullptr,nullptr);CreateWindowW(L"BUTTON",L"BATTERIE   - Programmer kicks, snares, hats...",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,24,88,390,46,h,(HMENU)(INT_PTR)PICK_DRUM,nullptr,nullptr);CreateWindowW(L"BUTTON",L"INSTRUMENT - Basse, synth, piano...",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,24,142,390,46,h,(HMENU)(INT_PTR)PICK_INST,nullptr,nullptr);CreateWindowW(L"BUTTON",L"AUDIO      - Import / enregistrement (bientot)",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,24,196,390,46,h,(HMENU)(INT_PTR)PICK_AUDIO,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Annuler",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,294,258,120,32,h,(HMENU)(INT_PTR)PICK_CANCEL,nullptr,nullptr);return 0;}if(m==WM_CTLCOLORSTATIC){HDC dc=(HDC)w;SetTextColor(dc,RGB(238,238,240));SetBkColor(dc,RGB(31,32,36));static HBRUSH br=CreateSolidBrush(RGB(31,32,36));return(LRESULT)br;}if(m==WM_ERASEBKGND){RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(31,32,36));FillRect((HDC)w,&r,b);DeleteObject(b);return 1;}if(m==WM_COMMAND){int id=LOWORD(w);if(id>=PICK_DRUM&&id<=PICK_CANCEL){pickChoice=id;DestroyWindow(h);return 0;}}if(m==WM_CLOSE){pickChoice=PICK_CANCEL;DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);}
LaneType chooseTrackType(HWND owner){HINSTANCE hi=(HINSTANCE)GetWindowLongPtrW(owner,GWLP_HINSTANCE);static bool reg=false;if(!reg){WNDCLASSW wc{};wc.lpfnWndProc=pickerProc;wc.hInstance=hi;wc.lpszClassName=L"BoomifyTrackPicker";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);reg=true;}pickChoice=0;picker=CreateWindowExW(WS_EX_TOPMOST,L"BoomifyTrackPicker",L"Boomify - Nouvelle piste",WS_POPUP|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,454,340,owner,nullptr,hi,nullptr);RECT r;GetWindowRect(picker,&r);SetWindowPos(picker,nullptr,(GetSystemMetrics(SM_CXSCREEN)-(r.right-r.left))/2,(GetSystemMetrics(SM_CYSCREEN)-(r.bottom-r.top))/2,0,0,SWP_NOSIZE|SWP_NOZORDER);EnableWindow(owner,FALSE);ShowWindow(picker,SW_SHOW);UpdateWindow(picker);MSG msg{};while(IsWindow(picker)&&GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}EnableWindow(owner,TRUE);SetForegroundWindow(owner);if(pickChoice==PICK_DRUM)return LaneType::Drums;if(pickChoice==PICK_AUDIO)return LaneType::Audio;return LaneType::Instrument;}
void addTrack(HWND owner){if((int)lanes.size()>=V6_MAX_TRACKS)return;LaneType t=chooseTrackType(owner);if(pickChoice==PICK_CANCEL||pickChoice==0)return;int count=1;for(auto&x:lanes)if(x.type==t)count++;std::wstring name=t==LaneType::Drums?L"Drums "+std::to_wstring(count):t==LaneType::Audio?L"Audio "+std::to_wstring(count):L"Instrument "+std::to_wstring(count);lanes.push_back({name,t,false,false,80});laneSelected=(int)lanes.size()-1;layoutV6(owner);InvalidateRect(owner,nullptr,FALSE);}
void removeTrack(){if(laneSelected<0||laneSelected>=(int)lanes.size()||lanes.size()<=1)return;if(laneSelected<3){MessageBoxW(win,L"Les trois pistes historiques restent verrouillees pendant la migration du format projet.",L"Boomify",MB_OK|MB_ICONINFORMATION);return;}int idx=laneSelected-3;for(int k=idx;k<V6_MAX_TRACKS-4;k++)extraNotes[k]=extraNotes[k+1];for(auto&c:extraNotes[V6_MAX_TRACKS-4])clearNote(c);lanes.erase(lanes.begin()+laneSelected);laneSelected=std::min(laneSelected,(int)lanes.size()-1);layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void renameTrack(){if(laneSelected<0||laneSelected>=(int)lanes.size())return;static int n=1;lanes[laneSelected].name=L"Track "+std::to_wstring(n++);InvalidateRect(win,nullptr,FALSE);}
void moveLane(int from,int to){if(from<3||to<3||from==to||from>=(int)lanes.size()||to>=(int)lanes.size())return;std::swap(lanes[from],lanes[to]);std::swap(extraNotes[from-3],extraNotes[to-3]);laneSelected=to;layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void layoutV6(HWND h){layout(h);RECT c;GetClientRect(h,&c);addTrackR={12,88,116,118};removeTrackR={122,88,214,118};renameTrackR={220,88,312,118};int top=128,bottom=editorOpen?std::max(455,(int)(c.bottom*.64)):c.bottom-45;int n=std::max(1,(int)lanes.size());int available=std::max(1,bottom-top);int rh=std::max(34,std::min(82,available/n));for(int i=0;i<V6_MAX_TRACKS;i++){laneHeadR[i]={0,0,0,0};laneMuteR[i]={0,0,0,0};soloR[i]={0,0,0,0};laneVolR[i]={0,0,0,0};}for(int i=0;i<n;i++){int y=top+i*rh;laneHeadR[i]={4,y,194,std::min(bottom,y+rh-2)};laneMuteR[i]={126,y+7,152,y+29};soloR[i]={158,y+7,184,y+29};laneVolR[i]={14,std::max(y+31,y+rh-13),112,std::max(y+37,y+rh-7)};}}
void drawClipGridForLane(HDC d,RECT c,int lane,RECT row){int left=200,right=c.right-20;if(right<=left)return;int width=right-left;for(int v=0;v<visibleBars;v++){int b=scrollBar+v;if(b>=activeBars)break;int x1=left+(int)((long long)v*width/visibleBars),x2=left+(int)((long long)(v+1)*width/visibleBars);RECT r{x1,row.top,std::max(x1+1,x2-1),row.bottom};bool used=laneUsed(lane,b);COLORREF base=used?(lane==0?RGB(53,145,116):lane==1?RGB(68,112,184):RGB(191,118,72)):RGB(28,29,31);fill(d,r,base);line(d,r.left,r.top,r.left,r.bottom,grid);if(b==cursorBar)fill(d,{r.left,r.top,r.left+2,r.bottom},accent);if(b==selectedBar&&lane==laneSelected){line(d,r.left+1,r.top+1,r.right-1,r.top+1,RGB(245,245,245),2);line(d,r.left+1,r.bottom-2,r.right-1,r.bottom-2,RGB(245,245,245),2);}}}
void drawV6(HDC d,RECT c){paint(d,c);fill(d,{0,82,c.right,126},RGB(24,25,27));button(d,addTrackR,L"+ PISTE");button(d,removeTrackR,L"SUPPR.");button(d,renameTrackR,L"RENOMMER");int top=128,bottom=editorOpen?std::max(455,(int)(c.bottom*.64)):c.bottom-45;fill(d,{0,top,c.right,bottom},RGB(25,26,28));for(int i=0;i<(int)lanes.size();i++){RECT hr=laneHeadR[i];if(hr.bottom<=hr.top)continue;fill(d,hr,i==laneSelected?RGB(49,50,54):RGB(39,40,43));if(i==laneSelected)fill(d,{4,hr.top,8,hr.bottom},accent);label(d,lanes[i].name.c_str(),14,hr.top+6,11,txt,FW_BOLD);label(d,typeLabel(lanes[i].type),14,hr.top+22,8,RGB(150,153,158));button(d,laneMuteR[i],L"M",lanes[i].mute);button(d,soloR[i],L"S",lanes[i].solo);fill(d,laneVolR[i],RGB(18,19,21));int vw=(laneVolR[i].right-laneVolR[i].left)*lanes[i].volume/100;fill(d,{laneVolR[i].left,laneVolR[i].top,laneVolR[i].left+vw,laneVolR[i].bottom},accent);drawClipGridForLane(d,c,i,hr);}paintSelectionOverlay(d,false);label(d,L"PISTES",330,96,10,RGB(175,177,181),FW_BOLD);}
bool hitLaneClip(POINT p,int&lane,int&bar){RECT c;GetClientRect(win,&c);int left=200,right=c.right-20;if(p.x<left||p.x>=right)return false;for(int i=0;i<(int)lanes.size();i++){if(p.y>=laneHeadR[i].top&&p.y<laneHeadR[i].bottom){int width=right-left;int v=(int)((long long)(p.x-left)*visibleBars/std::max(1,width));if(v>=0&&v<visibleBars){lane=i;bar=scrollBar+v;return bar<activeBars;}}}return false;}
void toggleExtraNote(int lane,int bar,POINT p){if(lanes[lane].type==LaneType::Audio){MessageBoxW(win,L"Piste Audio creee. L'import et l'enregistrement arrivent dans l'upgrade audio.",L"Boomify - Audio",MB_OK|MB_ICONINFORMATION);return;}RECT c;GetClientRect(win,&c);int left=200,right=c.right-20,width=std::max(1,right-left);int v=bar-scrollBar,x1=left+(int)((long long)v*width/visibleBars),x2=left+(int)((long long)(v+1)*width/visibleBars);int local=p.x-x1,cellW=std::max(1,x2-x1),step=std::clamp(local*STEPS/cellW,0,STEPS-1);auto&clip=noteForLane(lane,bar);clip[6][step]=!clip[6][step];InvalidateRect(win,nullptr,FALSE);}
void v6Fresh(){freshEmpty();clearMulti();for(auto&a:extraNotes)for(auto&c:a)clearNote(c);lanes={{L"Drums",LaneType::Drums,false,false,85},{L"Bass",LaneType::Instrument,false,false,80},{L"Synth",LaneType::Instrument,false,false,80}};laneSelected=0;layoutV6(win);}
LRESULT CALLBACK proc_v6(HWND h,UINT m,WPARAM wp,LPARAM lp){if(m==WM_SIZE){proc_v5(h,m,wp,lp);layoutV6(h);InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);drawV6(mem,c);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(inside(addTrackR,p)){addTrack(h);return 0;}if(inside(removeTrackR,p)){removeTrack();return 0;}if(inside(renameTrackR,p)){renameTrack();return 0;}for(int i=0;i<(int)lanes.size();i++){if(inside(laneMuteR[i],p)){lanes[i].mute=!lanes[i].mute;if(i<3)muted[i]=lanes[i].mute;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(soloR[i],p)){lanes[i].solo=!lanes[i].solo;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(laneVolR[i],p)){int width=(int)(laneVolR[i].right-laneVolR[i].left),raw=(int)(p.x-laneVolR[i].left)*100/std::max(1,width);lanes[i].volume=std::clamp(raw,0,100);InvalidateRect(h,nullptr,FALSE);return 0;}}int lane,bar;if(hitLaneClip(p,lane,bar)){laneSelected=lane;if(lane<3){selectedTrack=lane;return proc_v5(h,m,wp,lp);}selectedBar=bar;toggleExtraNote(lane,bar,p);return 0;}for(int i=0;i<(int)lanes.size();i++)if(inside(laneHeadR[i],p)){laneSelected=i;if(i<3)selectedTrack=i;InvalidateRect(h,nullptr,FALSE);return 0;}}if(m==WM_KEYDOWN&&wp==VK_UP&&laneSelected>3){moveLane(laneSelected,laneSelected-1);return 0;}if(m==WM_KEYDOWN&&wp==VK_DOWN&&laneSelected>=3&&laneSelected+1<(int)lanes.size()){moveLane(laneSelected,laneSelected+1);return 0;}return proc_v5(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v6;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV6";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 3 - Track Workspace",WS_OVERLAPPEDWINDOW,0,0,1500,920,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();layoutV6(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
