// Boomify Alpha 5 - dynamic native FX rack
#define BOOMIFY_V11_INCLUDE
#include "main_v10.cpp"
#undef BOOMIFY_V11_INCLUDE

namespace {
enum class FxType11{SoftClip,HardClip,Overdrive,Saturation,Wavefold,Bitcrush,Compressor,Limiter,Transient,LowPass,HighPass,Delay,Reverb};
struct Fx11{FxType11 type=FxType11::SoftClip;bool on=true;int amount=50;};
std::array<std::vector<Fx11>,V6_MAX_TRACKS> rack11;
std::vector<RECT> fxRects11;RECT addFx11{};int fxScroll11=0;
const wchar_t* fxName11(FxType11 t){switch(t){case FxType11::SoftClip:return L"Soft Clip";case FxType11::HardClip:return L"Hard Clip";case FxType11::Overdrive:return L"Overdrive";case FxType11::Saturation:return L"Saturation";case FxType11::Wavefold:return L"Wavefold";case FxType11::Bitcrush:return L"Bitcrush";case FxType11::Compressor:return L"Compressor";case FxType11::Limiter:return L"Limiter";case FxType11::Transient:return L"Transient Shaper";case FxType11::LowPass:return L"Low-pass Filter";case FxType11::HighPass:return L"High-pass Filter";case FxType11::Delay:return L"Delay";default:return L"Reverb";}}
COLORREF fxColor11(FxType11 t){int v=(int)t;if(v<=5)return RGB(231,111,80);if(v<=8)return RGB(78,174,211);if(v<=10)return RGB(83,196,159);return RGB(166,105,220);}
double processFx11(double x,const Fx11&f,double&state){if(!f.on)return x;double a=f.amount/100.0;switch(f.type){case FxType11::SoftClip:return tanh(x*(1.0+a*8.0));case FxType11::HardClip:{double lim=1.0-a*.9;return std::clamp(x,-lim,lim)/std::max(.1,lim);}case FxType11::Overdrive:return atan(x*(1.0+a*14.0))*0.75;case FxType11::Saturation:return x/(1.0+std::abs(x)*(a*5.0));case FxType11::Wavefold:{double g=x*(1+a*8);return sin(g*2.2);}case FxType11::Bitcrush:{double levels=std::max(4.0,256.0*(1.0-a)+4.0);return floor(x*levels)/levels;}case FxType11::Compressor:{double th=.8-a*.6;double ax=std::abs(x);if(ax>th)x=(x<0?-1:1)*(th+(ax-th)*(.5-a*.4));return x;}case FxType11::Limiter:{double lim=.95-a*.45;return std::clamp(x,-lim,lim);}case FxType11::Transient:return x*(1.0+a*.8);case FxType11::LowPass:{double k=.02+(1-a)*.45;state+=k*(x-state);return state;}case FxType11::HighPass:{double k=.02+(1-a)*.45;state+=k*(x-state);return x-state;}case FxType11::Delay:{double y=x+state*a*.65;state=state*.998+x*.002;return y;}case FxType11::Reverb:{double y=x+state*a*.45;state=state*.995+x*.005;return y;}}return x;}
void renderRange11(std::vector<int16_t>&out,int start){start=std::clamp(start,0,activeBars-1);int step=std::max(1,(int)(SR*60.0/bpm/4.0));size_t frames=(size_t)step*STEPS*(activeBars-start);out.assign(frames*2,0);std::vector<Voice> dv;std::vector<Voice9> nv;std::array<std::array<double,16>,V6_MAX_TRACKS> states{};bool anySolo=false;for(auto&l:lanes)if(l.solo)anySolo=true;for(size_t f=0;f<frames;f++){if(f%step==0){int g=(int)(f/step),b=start+g/STEPS,s=g%STEPS;if(!lanes.empty()&&!lanes[0].mute&&(!anySolo||lanes[0].solo))for(int r=0;r<DR;r++)if(drums[b][r][s])dv.push_back({r,0});for(int lane=1;lane<(int)lanes.size();lane++){if(lanes[lane].type==LaneType::Audio||lanes[lane].mute||(anySolo&&!lanes[lane].solo))continue;auto&clip=noteForLane(lane,b);int base=familyOf(sound9[lane])==Family9::Bass?47:71;for(int r=0;r<NOTES;r++)if(clip[r][s])nv.push_back({sound9[lane],lane,base-r});}}std::array<double,V6_MAX_TRACKS> mix{};for(auto&q:dv)mix[0]+=sample(q);for(auto&q:nv)if(q.lane>=0&&q.lane<(int)lanes.size())mix[q.lane]+=sample9(q);double masterMix=0;for(int lane=0;lane<(int)lanes.size();lane++){if(lanes[lane].mute||(anySolo&&!lanes[lane].solo))continue;double y=mix[lane]*(lanes[lane].volume/100.0);for(size_t j=0;j<rack11[lane].size();j++)y=processFx11(y,rack11[lane][j],states[lane][std::min<size_t>(j,15)]);masterMix+=y;}dv.erase(std::remove_if(dv.begin(),dv.end(),[](const Voice&q){return!alive(q);}),dv.end());nv.erase(std::remove_if(nv.begin(),nv.end(),[](const Voice9&q){return!alive9(q);}),nv.end());int16_t z=(int16_t)(std::clamp(masterMix*.20*(master/100.0),-1.0,1.0)*32767);out[f*2]=out[f*2+1]=z;}}
void play11(){if(playing){stopAudio();return;}playStartBar=cursorBar;renderRange11(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutWrite(wave,&waveHdr,sizeof(waveHdr));playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export11(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderRange11(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,align=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&align,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
void addFxMenu11(HWND h,POINT p){if(laneSelected<0||laneSelected>=(int)lanes.size())return;HMENU root=CreatePopupMenu(),dist=CreatePopupMenu(),dyn=CreatePopupMenu(),filter=CreatePopupMenu(),space=CreatePopupMenu();for(int i=0;i<6;i++)AppendMenuW(dist,MF_STRING,67001+i,fxName11((FxType11)i));for(int i=6;i<9;i++)AppendMenuW(dyn,MF_STRING,67001+i,fxName11((FxType11)i));for(int i=9;i<11;i++)AppendMenuW(filter,MF_STRING,67001+i,fxName11((FxType11)i));for(int i=11;i<13;i++)AppendMenuW(space,MF_STRING,67001+i,fxName11((FxType11)i));AppendMenuW(root,MF_POPUP,(UINT_PTR)dist,L"Distortion / Color");AppendMenuW(root,MF_POPUP,(UINT_PTR)dyn,L"Dynamics");AppendMenuW(root,MF_POPUP,(UINT_PTR)filter,L"EQ / Filter");AppendMenuW(root,MF_POPUP,(UINT_PTR)space,L"Space");ClientToScreen(h,&p);int cmd=TrackPopupMenu(root,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,h,nullptr);DestroyMenu(root);if(cmd>=67001&&cmd<67014){rack11[laneSelected].push_back({(FxType11)(cmd-67001),true,50});InvalidateRect(h,nullptr,FALSE);}}
void drawInspector11(HDC d){panel10(d,inspector10,RGB(25,27,32));int x=inspector10.left+16;label(d,L"PISTE SELECTIONNEE",x,98,8,RGB(128,132,140),FW_BOLD);if(laneSelected<0||laneSelected>=(int)lanes.size())return;label(d,lanes[laneSelected].name.c_str(),x,116,14,RGB(241,242,245),FW_BOLD);int y=154;if(laneSelected>0&&lanes[laneSelected].type==LaneType::Instrument){instrument10={x,y,inspector10.right-16,y+40};fill(d,instrument10,RGB(36,38,44));label(d,soundName9(sound9[laneSelected]),x+12,y+13,10,RGB(231,123,91),FW_BOLD);y+=58;}else instrument10={0,0,0,0};label(d,L"CHAINE D'EFFETS",x,y,8,RGB(128,132,140),FW_BOLD);y+=20;fxRects11.clear();auto&rack=rack11[laneSelected];for(int i=fxScroll11;i<(int)rack.size()&&y+58<inspector10.bottom-52;i++){RECT r{x,y,inspector10.right-16,y+54};fxRects11.push_back(r);fill(d,r,RGB(34,36,42));COLORREF col=fxColor11(rack[i].type);fill(d,{r.left,r.top,r.left+4,r.bottom},rack[i].on?col:RGB(75,77,84));label(d,fxName11(rack[i].type),r.left+13,r.top+8,9,rack[i].on?RGB(238,239,242):RGB(130,132,138),FW_BOLD);std::wstring val=std::to_wstring(rack[i].amount)+L"%";label(d,val.c_str(),r.right-48,r.top+8,8,col,FW_BOLD);RECT bar{r.left+13,r.top+32,r.right-13,r.top+40};fill(d,bar,RGB(19,20,24));RECT q=bar;q.right=q.left+(q.right-q.left)*rack[i].amount/100;fill(d,q,col);y+=62;}addFx11={x,std::min(y+4,inspector10.bottom-44),inspector10.right-16,std::min(y+40,inspector10.bottom-8)};fill(d,addFx11,RGB(38,40,46));label(d,L"+  AJOUTER UN EFFET",addFx11.left+18,addFx11.top+11,9,RGB(186,188,195),FW_BOLD);}
void draw11(HDC d,RECT c){fill(d,c,RGB(18,20,24));drawTop10(d,c);fill(d,{0,82,inspector10.left,126},RGB(27,29,34));button(d,addTrackR,L"+ PISTE");button(d,removeTrackR,L"SUPPR.");button(d,renameTrackR,L"RENOMMER");drawTrackHeaders10(d);drawTimeline10(d);drawInspector11(d);drawBrowser10(d);}
LRESULT CALLBACK proc_v11(HWND h,UINT m,WPARAM wp,LPARAM lp){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDOWN){if(inside(playR,p)){play11();return 0;}if(inside(wavR,p)){export11();return 0;}if(laneSelected>=0&&laneSelected<(int)lanes.size()){if(laneSelected>0&&inside(instrument10,p)){chooseInstrument9(h,laneSelected,p);return 0;}if(inside(addFx11,p)){addFxMenu11(h,p);return 0;}for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],p)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected][idx].on=!rack11[laneSelected][idx].on;InvalidateRect(h,nullptr,FALSE);return 0;}}}}if(m==WM_MOUSEWHEEL&&laneSelected>=0&&laneSelected<(int)lanes.size()){POINT sp{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};ScreenToClient(h,&sp);for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],sp)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){int d=GET_WHEEL_DELTA_WPARAM(wp)>0?5:-5;rack11[laneSelected][idx].amount=std::clamp(rack11[laneSelected][idx].amount+d,0,100);InvalidateRect(h,nullptr,FALSE);return 0;}}}if(m==WM_RBUTTONDOWN&&laneSelected>=0&&laneSelected<(int)lanes.size()){for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],p)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected].erase(rack11[laneSelected].begin()+idx);InvalidateRect(h,nullptr,FALSE);return 0;}}}if(m==WM_KEYDOWN&&wp==VK_SPACE){play11();return 0;}return proc_v10(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v11;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV11";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 5 - Native FX Rack",WS_OVERLAPPEDWINDOW,0,0,1600,960,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;rack11[0]={{FxType11::SoftClip,true,35}};layout10(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
