// Boomify V17 navigation/audio layer. Keeps V17 as the single application entry point.
#include <windows.h>
#include <windowsx.h>
#include <vector>
#include <cmath>
LRESULT CALLBACK proc_v17_nav(HWND,UINT,WPARAM,LPARAM);
static ATOM RegisterClassW_nav(const WNDCLASSW* src){WNDCLASSW wc=*src;wc.lpfnWndProc=proc_v17_nav;return ::RegisterClassW(&wc);}
#define RegisterClassW RegisterClassW_nav
#include "main_v17.cpp"
#undef RegisterClassW

namespace {
RECT zoomOutNavR{},zoomInNavR{},fitNavR{},loopNavR{},setLoopNavR{};
bool loopOnNav=false;int loopStartNav=0,loopEndNav=3;
HICON boomifyIconNav=nullptr;

void drawBurstNav(HDC d,int cx,int cy,int radius){const POINT outerRaw[]={{0,-100},{18,-48},{52,-82},{48,-38},{94,-50},{58,-14},{100,0},{56,17},{88,55},{43,39},{54,92},{15,51},{0,100},{-17,52},{-54,88},{-43,38},{-94,53},{-57,15},{-100,0},{-57,-17},{-88,-55},{-42,-39},{-53,-91},{-15,-51}};const POINT innerRaw[]={{0,-58},{12,-27},{35,-43},{29,-18},{57,-25},{34,-6},{61,5},{31,13},{48,38},{22,25},{24,55},{6,29},{-8,57},{-13,28},{-39,43},{-28,17},{-58,21},{-33,2},{-57,-12},{-28,-15},{-42,-42},{-18,-27},{-18,-56},{-4,-30}};POINT o[24],in[24];for(int i=0;i<24;i++){o[i]={(LONG)(cx+outerRaw[i].x*radius/100),(LONG)(cy+outerRaw[i].y*radius/100)};in[i]={(LONG)(cx+innerRaw[i].x*radius/100),(LONG)(cy+innerRaw[i].y*radius/100)};}HBRUSH bo=CreateSolidBrush(RGB(255,126,47)),br=CreateSolidBrush(RGB(239,45,50));HPEN pn=CreatePen(PS_NULL,0,0);auto op=SelectObject(d,pn);auto ob=SelectObject(d,bo);Polygon(d,o,24);SelectObject(d,br);Polygon(d,in,24);SelectObject(d,ob);SelectObject(d,op);DeleteObject(bo);DeleteObject(br);DeleteObject(pn);}
HICON makeBoomifyIconNav(int size){size=std::max(16,size);BITMAPV5HEADER bi{};bi.bV5Size=sizeof(bi);bi.bV5Width=size;bi.bV5Height=-size;bi.bV5Planes=1;bi.bV5BitCount=32;bi.bV5Compression=BI_BITFIELDS;bi.bV5RedMask=0x00FF0000;bi.bV5GreenMask=0x0000FF00;bi.bV5BlueMask=0x000000FF;bi.bV5AlphaMask=0xFF000000;void*bits=nullptr;HDC s=GetDC(nullptr);HBITMAP color=CreateDIBSection(s,(BITMAPINFO*)&bi,DIB_RGB_COLORS,&bits,nullptr,0);HDC mem=CreateCompatibleDC(s);auto old=SelectObject(mem,color);RECT r{0,0,size,size};HBRUSH bg=CreateSolidBrush(RGB(9,10,17));FillRect(mem,&r,bg);DeleteObject(bg);HBRUSH circle=CreateSolidBrush(RGB(18,20,31));HPEN cp=CreatePen(PS_SOLID,std::max(1,size/32),RGB(50,52,69));auto oldb=SelectObject(mem,circle);auto oldp=SelectObject(mem,cp);Ellipse(mem,size/12,size/12,size-size/12,size-size/12);SelectObject(mem,oldb);SelectObject(mem,oldp);DeleteObject(circle);DeleteObject(cp);drawBurstNav(mem,size/2,size/2,size*36/100);SelectObject(mem,old);DeleteDC(mem);ReleaseDC(nullptr,s);HBITMAP mask=CreateBitmap(size,size,1,1,nullptr);ICONINFO ii{};ii.fIcon=TRUE;ii.hbmColor=color;ii.hbmMask=mask;HICON icon=CreateIconIndirect(&ii);DeleteObject(color);DeleteObject(mask);return icon;}
void drawBrandNav(HDC d){RECT h=panels15.tracks;RECT cover{12,7,216,std::max<LONG>(70,h.top-2)};fill(d,cover,BG16);drawBurstNav(d,43,35,24);text16(d,L"BOOMIFY",{75,10,211,49},19,RGB(255,126,47),FW_HEAVY);text16(d,L"STUDIO  /  ALPHA 6",{76,44,211,64},6,RGB(239,74,79),FW_BOLD);}
void relayoutNav(){layout11(win);sync16(win);InvalidateRect(win,nullptr,FALSE);}
void scrollTimelineNav(int dir){if(!dir)return;int step=std::max(1,visibleBars/4);if(dir>0){int wanted=scrollBar+step,needed=std::min(MAX_BARS,wanted+visibleBars);if(needed>activeBars)activeBars=needed;scrollBar=std::min(wanted,std::max(0,MAX_BARS-visibleBars));}else scrollBar=std::max(0,scrollBar-step);cursorBar=std::clamp(cursorBar,scrollBar,std::min(MAX_BARS-1,scrollBar+visibleBars-1));relayoutNav();}
void zoomNav(int dir){int old=visibleBars;if(dir>0)visibleBars=std::max(4,visibleBars/2);else visibleBars=std::min(MAX_BARS,std::max(visibleBars+1,visibleBars*2));if(dir<0&&visibleBars>activeBars)visibleBars=std::min(MAX_BARS,std::max(activeBars,4));if(old==visibleBars)return;scrollBar=std::clamp(scrollBar,0,std::max(0,MAX_BARS-visibleBars));if(cursorBar<scrollBar)scrollBar=cursorBar;if(cursorBar>=scrollBar+visibleBars)scrollBar=std::max(0,cursorBar-visibleBars+1);relayoutNav();}
void fitTimelineNav(){visibleBars=std::clamp(activeBars,4,MAX_BARS);scrollBar=0;relayoutNav();}
void setLoopNavFromSelection(){int lo=MAX_BARS,hi=-1;for(auto&q:multiSelection){lo=std::min(lo,q.bar);hi=std::max(hi,q.bar);}if(hi<0){lo=std::clamp(selectedBar,0,std::max(0,activeBars-1));hi=std::min(activeBars-1,lo+3);}loopStartNav=std::clamp(lo,0,std::max(0,activeBars-1));loopEndNav=std::clamp(std::max(loopStartNav,hi),loopStartNav,std::max(loopStartNav,activeBars-1));loopOnNav=true;InvalidateRect(win,nullptr,FALSE);}
void drawNavTools(HDC d){RECT p=panels15.timeline;LONG y=p.top+13;setLoopNavR={p.right-350,y,p.right-275,y+27};loopNavR={p.right-269,y,p.right-205,y+27};fitNavR={p.right-199,y,p.right-145,y+27};zoomOutNavR={p.right-139,y,p.right-97,y+27};zoomInNavR={p.right-91,y,p.right-49,y+27};pill16(d,setLoopNavR,L"SET LOOP",CYAN16);pill16(d,loopNavR,L"LOOP",PINK16,loopOnNav);pill16(d,fitNavR,L"FIT",PURPLE16);pill16(d,zoomOutNavR,L"-",PURPLE16);pill16(d,zoomInNavR,L"+",PURPLE16);if(loopOnNav){int left=(int)p.left+15,right=(int)p.right-15,width=std::max(1,right-left),a=loopStartNav-scrollBar,b=loopEndNav-scrollBar+1;if(b>0&&a<visibleBars){a=std::clamp(a,0,visibleBars);b=std::clamp(b,0,visibleBars);LONG x0=left+(LONG)((long long)a*width/std::max(1,visibleBars)),x1=left+(LONG)((long long)b*width/std::max(1,visibleBars));RECT r{x0,p.top+38,x1,p.top+43};fill(d,r,PINK16);}}}
void clearLaneStorageNav(int lane){if(lane<0||lane>=V6_MAX_TRACKS)return;samples15[lane]={};kicks15[lane]={};colors15[lane]=defaultColor15(lane);rack11[lane].clear();for(int b=0;b<MAX_BARS;++b)fine16[lane][b].clear();if(lane>=3){int idx=lane-3;if(idx>=0&&idx<V6_MAX_TRACKS-3){for(auto&c:extraNotes[idx])clearNote(c);for(auto&c:extraDrums11[idx])for(auto&r:c)r.fill(false);}}}
void addTrackNav(HWND h,POINT client){if((int)lanes.size()>=V6_MAX_TRACKS){MessageBoxW(h,L"Nombre maximum de pistes atteint.",L"Boomify",MB_OK|MB_ICONINFORMATION);return;}HMENU menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,PICK_DRUM,L"Drums / Batterie");AppendMenuW(menu,MF_STRING,PICK_INST,L"Instrument / Bass / Synth");AppendMenuW(menu,MF_STRING,PICK_AUDIO,L"Audio / Sample WAV");POINT s=client;ClientToScreen(h,&s);int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_RIGHTBUTTON,s.x,s.y,0,h,nullptr);DestroyMenu(menu);if(cmd!=PICK_DRUM&&cmd!=PICK_INST&&cmd!=PICK_AUDIO)return;LaneType t=cmd==PICK_DRUM?LaneType::Drums:cmd==PICK_AUDIO?LaneType::Audio:LaneType::Instrument;int count=1;for(auto&x:lanes)if(x.type==t)count++;std::wstring name=t==LaneType::Drums?L"Drums "+std::to_wstring(count):t==LaneType::Audio?L"Audio "+std::to_wstring(count):L"Instrument "+std::to_wstring(count);int n=(int)lanes.size();clearLaneStorageNav(n);lanes.push_back({name,t,false,false,80});laneSelected=n;selectedTrack=std::min(TRACKS-1,n);selectedBar=std::clamp(selectedBar,0,std::max(0,activeBars-1));clearMulti();if(t==LaneType::Instrument)sound9[n]=Sound9::SawLead;layout11(h);layoutPanels15(h);sync16(h);InvalidateRect(h,nullptr,FALSE);}
void removeTrackNav(){if(laneSelected<0||laneSelected>=(int)lanes.size())return;if(laneSelected<3){MessageBoxW(win,L"Les trois pistes de base restent verrouillees pour cette Alpha.",L"Boomify",MB_OK|MB_ICONINFORMATION);return;}int old=laneSelected,n=(int)lanes.size();for(int lane=old;lane<n-1;++lane){samples15[lane]=std::move(samples15[lane+1]);kicks15[lane]=kicks15[lane+1];colors15[lane]=colors15[lane+1];rack11[lane]=std::move(rack11[lane+1]);sound9[lane]=sound9[lane+1];fine16[lane]=std::move(fine16[lane+1]);}int idx=old-3;for(int k=idx;k<V6_MAX_TRACKS-4;++k){extraNotes[k]=std::move(extraNotes[k+1]);extraDrums11[k]=std::move(extraDrums11[k+1]);}for(auto&c:extraNotes[V6_MAX_TRACKS-4])clearNote(c);for(auto&c:extraDrums11[V6_MAX_TRACKS-4])for(auto&r:c)r.fill(false);clearLaneStorageNav(n-1);lanes.erase(lanes.begin()+old);laneSelected=std::min(old,(int)lanes.size()-1);selectedTrack=std::min(TRACKS-1,laneSelected);selectedBar=std::clamp(selectedBar,0,std::max(0,activeBars-1));audioSelected15=-1;fineClipboard17.clear();clip12.clear();clearMulti();layout11(win);layoutPanels15(win);sync16(win);InvalidateRect(win,nullptr,FALSE);}

// Basic kick is rendered separately, but ONLY its kick cells are removed from the legacy pass.
// The rest of every drum lane (snare/hat/etc.), including dynamic lanes 4+, remains audible.
void renderBasicKickNav(std::vector<int16_t>&a,int startBar){if(a.empty())return;const int bpmNow=std::max(60,(int)bpm);const double secBar=240.0/(double)bpmNow;const long long barFrames=(long long)(secBar*SR),stepFrames=std::max<long long>(1,barFrames/STEPS),kickFrames=(long long)(0.30*SR);std::vector<double> kick((size_t)kickFrames,0.0);double ph=0.0;for(long long q=0;q<kickFrames;++q){double t=(double)q/SR,f=48.0+110.0*std::exp(-t*35.0);ph+=6.283185307179586*f/SR;double attack=std::clamp(t/0.0025,0.0,1.0),remain=(kickFrames-1-q)/(double)SR,release=std::clamp(remain/0.020,0.0,1.0);release=release*release*(3.0-2.0*release);kick[(size_t)q]=std::sin(ph)*std::exp(-t*16.0)*attack*release*0.34;}if(!kick.empty()){kick.front()=0.0;kick.back()=0.0;}for(int lane=0;lane<(int)lanes.size();++lane){if(lanes[lane].type!=LaneType::Drums||kicks15[lane].enabled||lanes[lane].mute)continue;double gain=lanes[lane].volume/100.0;for(int bar=std::max(0,startBar);bar<activeBars;++bar){auto&dr=drumForLane11(lane,bar);for(int step=0;step<STEPS;++step){if(!dr[0][step])continue;long long st=((long long)bar-startBar)*barFrames+(long long)step*stepFrames;for(long long q=0;q<kickFrames;++q){size_t j=(size_t)(st+q)*2;if(j+1>=a.size())break;int add=(int)std::lrint(kick[(size_t)q]*gain*32767.0);a[j]=(int16_t)std::clamp((int)a[j]+add,-32768,32767);a[j+1]=(int16_t)std::clamp((int)a[j+1]+add,-32768,32767);}}}}}
void renderNav(std::vector<int16_t>&a,int start){struct Hit{int lane,bar,step;};std::vector<Hit> hidden;for(int l=0;l<(int)lanes.size();++l){if(lanes[l].type!=LaneType::Drums||kicks15[l].enabled||lanes[l].mute)continue;for(int b=std::max(0,start);b<activeBars;++b){auto&d=drumForLane11(l,b);for(int s=0;s<STEPS;++s)if(d[0][s]){hidden.push_back({l,b,s});d[0][s]=false;}}}
// Native instruments currently leave the synth too hot. Apply a temporary render gain only;
// project faders and saved values are left untouched so old projects stay editable.
std::vector<int> oldVol(lanes.size());for(int l=0;l<(int)lanes.size();++l){oldVol[l]=lanes[l].volume;if(lanes[l].type==LaneType::Instrument)lanes[l].volume=std::max(0,(lanes[l].volume+49)/50);}
render16(a,start);
for(int l=0;l<(int)lanes.size();++l)lanes[l].volume=oldVol[l];for(auto&h:hidden)drumForLane11(h.lane,h.bar)[0][h.step]=true;renderBasicKickNav(a,start);loudness16(a);}
void playNav(){if(playing){stopAudio();return;}int start=loopOnNav?loopStartNav:cursorBar;start=std::clamp(start,0,std::max(0,activeBars-1));playStartBar=start;renderNav(playBuffer,start);if(loopOnNav){int bpmNow=std::max(60,(int)bpm);double secBar=240.0/(double)bpmNow;size_t frames=(size_t)(secBar*SR)*std::max(1,loopEndNav-loopStartNav+1),samples=frames*2;if(playBuffer.size()>samples)playBuffer.resize(samples);}WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);if(loopOnNav){waveHdr.dwFlags=WHDR_BEGINLOOP|WHDR_ENDLOOP;waveHdr.dwLoops=0xFFFFFFFFu;}if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void exportNav(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderNav(a,0);if(a.empty()){MessageBoxW(win,L"Rien a exporter.",L"Boomify",MB_OK|MB_ICONWARNING);return;}std::ofstream o(p,std::ios::binary);if(!o){MessageBoxW(win,L"Impossible de creer le WAV.",L"Boomify",MB_OK|MB_ICONERROR);return;}uint32_t ds=(uint32_t)(a.size()*sizeof(int16_t)),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);o.close();MessageBoxW(win,L"Export WAV termine.",L"Boomify",MB_OK|MB_ICONINFORMATION);}
}

LRESULT CALLBACK proc_v17_nav(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_CREATE){boomifyIconNav=makeBoomifyIconNav(64);if(boomifyIconNav){SendMessageW(h,WM_SETICON,ICON_BIG,(LPARAM)boomifyIconNav);SendMessageW(h,WM_SETICON,ICON_SMALL,(LPARAM)boomifyIconNav);}}if(m==WM_DESTROY&&boomifyIconNav){DestroyIcon(boomifyIconNav);boomifyIconNav=nullptr;}if(m==WM_PAINT){LRESULT r=proc_v17(h,m,w,l);HDC d=GetDC(h);if(d){drawBrandNav(d);drawNavTools(d);ReleaseDC(h,d);}return r;}if(m==WM_MOUSEWHEEL||m==WM_MOUSEHWHEEL){POINT q{GET_X_LPARAM(l),GET_Y_LPARAM(l)};ScreenToClient(h,&q);if(inside(timeline10,q)){short delta=GET_WHEEL_DELTA_WPARAM(w);bool ctrl=(GET_KEYSTATE_WPARAM(w)&MK_CONTROL)!=0;if(ctrl)zoomNav(delta>0?1:-1);else scrollTimelineNav(delta<0?1:-1);return 0;}}if(m==WM_LBUTTONDOWN){if(inside(addTrack15,p)){addTrackNav(h,p);return 0;}if(inside(removeTrack15,p)){removeTrackNav();return 0;}for(int i=0;i<(int)lanes.size();++i){if(inside(laneMuteR[i],p)){lanes[i].mute=!lanes[i].mute;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(soloR[i],p)){lanes[i].solo=!lanes[i].solo;InvalidateRect(h,nullptr,FALSE);return 0;}}if(inside(playR,p)){playNav();return 0;}if(inside(wavR,p)){exportNav();return 0;}if(inside(setLoopNavR,p)){setLoopNavFromSelection();return 0;}if(inside(loopNavR,p)){if(loopOnNav)loopOnNav=false;else setLoopNavFromSelection();InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(fitNavR,p)){fitTimelineNav();return 0;}if(inside(zoomOutNavR,p)){zoomNav(-1);return 0;}if(inside(zoomInNavR,p)){zoomNav(1);return 0;}}if(m==WM_KEYDOWN){bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0;if(w==VK_SPACE){playNav();return 0;}if(ctrl&&w=='L'){if(loopOnNav)loopOnNav=false;else setLoopNavFromSelection();InvalidateRect(h,nullptr,FALSE);return 0;}if(ctrl&&(w==VK_OEM_PLUS||w==VK_ADD)){zoomNav(1);return 0;}if(ctrl&&(w==VK_OEM_MINUS||w==VK_SUBTRACT)){zoomNav(-1);return 0;}}return proc_v17(h,m,w,l);}
