// Boomify V14 - stabilized musical editor + project workflow
#define BOOMIFY_V14_INCLUDE
#include "main_v13.cpp"
#undef BOOMIFY_V14_INCLUDE

namespace {
bool paintNotes14=false,paintValue14=false;int lastRow14=-1,lastStep14=-1;
RECT clearNotes14{},shiftUp14{},shiftDown14{},save14{},open14{};
const wchar_t* noteClass14(int n){static const wchar_t* a[]={L"C",L"C#",L"D",L"D#",L"E",L"F",L"F#",L"G",L"G#",L"A",L"A#",L"B"};return a[(n%12+12)%12];}
std::wstring noteName14(int midi){return std::wstring(noteClass14(midi))+std::to_wstring(midi/12-1);}
RECT noteRect14(int r,int s){int top=(int)editorArea11.top,gt=top+44,gb=(int)editorArea11.bottom-12,lw=86;int rh=std::max(12,(gb-gt)/std::max(1,NOTES));int cw=std::max(8,((int)editorArea11.right-lw-14)/STEPS);int y=gt+r*rh;return{(LONG)(lw+s*cw),(LONG)y,(LONG)(lw+(s+1)*cw),(LONG)std::min(gb,y+rh)};}
bool noteCell14(POINT p,int&r,int&s){if(!editorOpen||laneSelected<0||laneSelected>=(int)lanes.size()||lanes[laneSelected].type!=LaneType::Instrument)return false;for(r=0;r<NOTES;r++)for(s=0;s<STEPS;s++)if(inside(noteRect14(r,s),p))return true;return false;}
void setNote14(int r,int s,bool v){if(laneSelected<0||laneSelected>=(int)lanes.size())return;noteForLane(laneSelected,selectedBar)[r][s]=v;InvalidateRect(win,nullptr,FALSE);}
void shiftNotes14(int dir){if(laneSelected<0||laneSelected>=(int)lanes.size()||lanes[laneSelected].type!=LaneType::Instrument)return;auto&n=noteForLane(laneSelected,selectedBar);NoteClip out{};for(auto&r:out)r.fill(false);for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)if(n[r][s]){int nr=r-dir;if(nr>=0&&nr<NOTES)out[nr][s]=true;}n=out;InvalidateRect(win,nullptr,FALSE);}
void clearNotes14Fn(){if(laneSelected>=0&&laneSelected<(int)lanes.size()&&lanes[laneSelected].type==LaneType::Instrument){clearNote(noteForLane(laneSelected,selectedBar));InvalidateRect(win,nullptr,FALSE);}}
void boost14(std::vector<int16_t>&a){for(auto&x:a){int v=(int)x*5/2;x=(int16_t)std::clamp(v,-32768,32767);}}
void play14(){if(playing){stopAudio();return;}playStartBar=cursorBar;renderRange11(playBuffer,playStartBar);boost14(playBuffer);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;MessageBoxW(win,L"Sortie audio Windows indisponible.",L"Boomify",MB_OK|MB_ICONERROR);return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export14(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderRange11(a,0);boost14(a);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
void writeBits14(std::ofstream&o,const NoteClip&c){for(auto&r:c){for(bool x:r)o<<(x?'1':'0');o<<'\n';}}
void writeDrum14(std::ofstream&o,const DrumClip&c){for(auto&r:c){for(bool x:r)o<<(x?'1':'0');o<<'\n';}}
void readBits14(std::ifstream&i,NoteClip&c){std::string z;for(auto&r:c){i>>z;for(int s=0;s<STEPS;s++)r[s]=s<(int)z.size()&&z[s]=='1';}}
void readDrum14(std::ifstream&i,DrumClip&c){std::string z;for(auto&r:c){i>>z;for(int s=0;s<STEPS;s++)r[s]=s<(int)z.size()&&z[s]=='1';}}
void saveProject14(){auto p=dialog(true,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return;std::ofstream o(p);if(!o){MessageBoxW(win,L"Impossible d'enregistrer le projet.",L"Boomify",MB_OK|MB_ICONERROR);return;}o<<"BOOMIFY14 "<<bpm<<' '<<master<<' '<<activeBars<<' '<<lanes.size()<<'\n';for(int l=0;l<(int)lanes.size();l++){std::string n=narrowName(lanes[l].name);o<<(int)lanes[l].type<<' '<<lanes[l].mute<<' '<<lanes[l].solo<<' '<<lanes[l].volume<<' '<<(int)sound9[l]<<' '<<n.size()<<' '<<n<<'\n';o<<rack11[l].size()<<'\n';for(auto&f:rack11[l])o<<(int)f.type<<' '<<f.on<<' '<<f.amount<<'\n';}for(int l=0;l<(int)lanes.size();l++)for(int b=0;b<activeBars;b++){if(lanes[l].type==LaneType::Drums)writeDrum14(o,drumForLane11(l,b));else if(lanes[l].type==LaneType::Instrument)writeBits14(o,noteForLane(l,b));}}
bool openProject14(){auto p=dialog(false,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return false;std::ifstream i(p);std::string magic;if(!(i>>magic)||magic!="BOOMIFY14"){MessageBoxW(win,L"Ce fichier n'est pas un projet Boomify Alpha 5.1 valide.",L"Boomify",MB_OK|MB_ICONWARNING);return false;}int bb=150,mm=100,nb=16,nl=3;if(!(i>>bb>>mm>>nb>>nl)||nb<1||nb>MAX_BARS||nl<1||nl>V6_MAX_TRACKS){MessageBoxW(win,L"Projet endommage.",L"Boomify",MB_OK|MB_ICONWARNING);return false;}stopAudio();for(int b=0;b<MAX_BARS;b++){clearDrum(b);clearNote(bass[b]);clearNote(melody[b]);}for(auto&a:extraNotes)for(auto&c:a)clearNote(c);for(auto&a:extraDrums11)for(auto&c:a)for(auto&r:c)r.fill(false);for(auto&r:rack11)r.clear();lanes.clear();for(int l=0;l<nl;l++){int ty=1,mu=0,so=0,vol=100,snd=3;size_t len=0;if(!(i>>ty>>mu>>so>>vol>>snd>>len)||len>1024)return false;i.get();std::string n(len,' ');if(len)i.read(&n[0],(std::streamsize)len);i.ignore(4096,'\n');lanes.push_back({widenName(n),(LaneType)std::clamp(ty,0,2),mu!=0,so!=0,std::clamp(vol,0,100)});sound9[l]=(Sound9)std::clamp(snd,0,14);int nf=0;i>>nf;nf=std::clamp(nf,0,64);for(int k=0;k<nf;k++){int t=0,on=1,am=50;i>>t>>on>>am;rack11[l].push_back({(FxType11)std::clamp(t,0,12),on!=0,std::clamp(am,0,100)});}}activeBars=nb;bpm=std::clamp(bb,60,220);master=std::clamp(mm,0,100);for(int l=0;l<nl;l++)for(int b=0;b<activeBars;b++){if(lanes[l].type==LaneType::Drums)readDrum14(i,drumForLane11(l,b));else if(lanes[l].type==LaneType::Instrument)readBits14(i,noteForLane(l,b));}laneSelected=selectedTrack=selectedBar=scrollBar=cursorBar=0;clearMulti();layout11(win);InvalidateRect(win,nullptr,FALSE);return true;}
bool selectedHas14(int l,int b){for(auto&q:multiSelection)if(q.track==l&&q.bar==b)return true;return false;}
void menu14(HWND h,POINT p,int l,int b){if(!selectedHas14(l,b))pick12(l,b,false,false);HMENU m=CreatePopupMenu();AppendMenuW(m,MF_STRING,74001,L"Copier\tCtrl+C");AppendMenuW(m,MF_STRING,74002,L"Coller\tCtrl+V");AppendMenuW(m,MF_STRING,74003,L"Dupliquer\tCtrl+D");AppendMenuW(m,MF_SEPARATOR,0,nullptr);AppendMenuW(m,MF_STRING,74004,L"Vider\tSuppr");POINT s=p;ClientToScreen(h,&s);int c=TrackPopupMenu(m,TPM_RETURNCMD|TPM_RIGHTBUTTON,s.x,s.y,0,h,nullptr);DestroyMenu(m);if(c==74001)copy12();else if(c==74002)paste12(b);else if(c==74003)duplicate12();else if(c==74004)erase12();}
void drawV14(HDC d){RECT c;GetClientRect(win,&c);save14={310,18,382,52};open14={388,18,468,52};fill(d,save14,RGB(38,42,50));fill(d,open14,RGB(38,42,50));label(d,L"SAVE",save14.left+19,save14.top+11,8,RGB(228,230,235),FW_BOLD);label(d,L"OPEN",open14.left+20,open14.top+11,8,RGB(228,230,235),FW_BOLD);if(inspector10.right>inspector10.left){RECT head{inspector10.left,70,inspector10.right,140};fill(d,head,RGB(18,20,25));if(laneSelected>=0&&laneSelected<(int)lanes.size()){label(d,L"INSPECTEUR DE PISTE",(int)inspector10.left+18,84,7,RGB(116,122,134),FW_BOLD);label(d,lanes[laneSelected].name.c_str(),(int)inspector10.left+18,106,13,RGB(239,241,244),FW_BOLD);}}if(!editorOpen||laneSelected<0||laneSelected>=(int)lanes.size()||lanes[laneSelected].type!=LaneType::Instrument)return;int top=(int)editorArea11.top,base=familyOf(sound9[laneSelected])==Family9::Bass?47:71;fill(d,editorArea11,RGB(18,20,25));fill(d,{0,(LONG)top,editorArea11.right,(LONG)(top+42)},RGB(23,26,32));auto&notes=noteForLane(laneSelected,selectedBar);for(int r=0;r<NOTES;r++){RECT first=noteRect14(r,0);bool root=((base-r)%12)==0;fill(d,{0,first.top,85,first.bottom},root?RGB(35,38,45):RGB(23,25,30));std::wstring nm=noteName14(base-r);label(d,nm.c_str(),22,first.top+std::max(2,(int)(first.bottom-first.top)/2-5),8,root?RGB(240,120,88):RGB(157,162,173),FW_BOLD);for(int s=0;s<STEPS;s++){RECT q=noteRect14(r,s);fill(d,q,notes[r][s]?RGB(220,96,69):(root?RGB(30,33,39):RGB(25,28,34)));line(d,q.left,q.bottom-1,q.right,q.bottom-1,RGB(43,47,55));line(d,q.right-1,q.top,q.right-1,q.bottom,RGB(43,47,55));}}for(int s=0;s<STEPS;s+=4){RECT f=noteRect14(0,s),la=noteRect14(NOTES-1,s);line(d,f.left,f.top,f.left,la.bottom,RGB(86,92,104),2);std::wstring bt=std::to_wstring(s/4+1);label(d,bt.c_str(),f.left+5,top+15,7,RGB(145,150,161),FW_BOLD);}clearNotes14={(LONG)(editorArea11.right-108),(LONG)(top+7),(LONG)(editorArea11.right-18),(LONG)(top+32)};shiftDown14={(LONG)(editorArea11.right-196),(LONG)(top+7),(LONG)(editorArea11.right-160),(LONG)(top+32)};shiftUp14={(LONG)(editorArea11.right-154),(LONG)(top+7),(LONG)(editorArea11.right-114),(LONG)(top+32)};for(RECT r:{shiftDown14,shiftUp14,clearNotes14})fill(d,r,RGB(40,44,52));label(d,L"-1",shiftDown14.left+10,shiftDown14.top+7,7,RGB(220,223,229),FW_BOLD);label(d,L"+1",shiftUp14.left+10,shiftUp14.top+7,7,RGB(220,223,229),FW_BOLD);label(d,L"EFFACER",clearNotes14.left+18,clearNotes14.top+7,7,RGB(232,137,118),FW_BOLD);label(d,L"Clic + glisser : dessiner / effacer",300,top+13,7,RGB(130,136,148));}
LRESULT CALLBACK proc_v14(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);overlay12(mem);drawV13Chrome(mem);drawV14(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_RBUTTONDOWN&&inside(timeline10,p)){int a=-1,b=-1;if(hitTimeline11(p,a,b)){menu14(h,p,a,b);return 0;}}if(m==WM_LBUTTONDOWN){if(inside(save14,p)){saveProject14();return 0;}if(inside(open14,p)){openProject14();return 0;}if(inside(playR,p)){play14();return 0;}if(inside(wavR,p)){export14();return 0;}if(inside(clearNotes14,p)){clearNotes14Fn();return 0;}if(inside(shiftDown14,p)){shiftNotes14(-1);return 0;}if(inside(shiftUp14,p)){shiftNotes14(1);return 0;}int r=-1,s=-1;if(noteCell14(p,r,s)){paintNotes14=true;paintValue14=!noteForLane(laneSelected,selectedBar)[r][s];lastRow14=r;lastStep14=s;setNote14(r,s,paintValue14);SetCapture(h);return 0;}}if(m==WM_MOUSEMOVE&&paintNotes14&&(w&MK_LBUTTON)){int r=-1,s=-1;if(noteCell14(p,r,s)&&(r!=lastRow14||s!=lastStep14)){lastRow14=r;lastStep14=s;setNote14(r,s,paintValue14);}return 0;}if(m==WM_LBUTTONUP&&paintNotes14){paintNotes14=false;lastRow14=lastStep14=-1;if(GetCapture()==h)ReleaseCapture();return 0;}return proc_v13(h,m,w,l);}
}
#ifndef BOOMIFY_V15_INCLUDE
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v14;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV14";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Studio - Alpha 5.1 Stabilized",WS_OVERLAPPEDWINDOW,0,0,1680,1000,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();editorOpen=true;master=100;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;layout11(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
#endif
