// Boomify Alpha 5 - functional DAW workspace + native FX rack
#define BOOMIFY_V11_INCLUDE
#include "main_v10.cpp"
#undef BOOMIFY_V11_INCLUDE

namespace {
enum class FxType11{SoftClip,HardClip,Overdrive,Saturation,Wavefold,Bitcrush,Compressor,Limiter,Transient,LowPass,HighPass,Delay,Reverb};
struct Fx11{FxType11 type=FxType11::SoftClip;bool on=true;int amount=50;};
std::array<std::vector<Fx11>,V6_MAX_TRACKS> rack11;
std::vector<RECT> fxRects11; RECT addFx11{}; int fxScroll11=0;

const wchar_t* fxName11(FxType11 t){switch(t){case FxType11::SoftClip:return L"Soft Clip";case FxType11::HardClip:return L"Hard Clip";case FxType11::Overdrive:return L"Overdrive";case FxType11::Saturation:return L"Saturation";case FxType11::Wavefold:return L"Wavefold";case FxType11::Bitcrush:return L"Bitcrush";case FxType11::Compressor:return L"Compressor";case FxType11::Limiter:return L"Limiter";case FxType11::Transient:return L"Transient Shaper";case FxType11::LowPass:return L"Low-pass";case FxType11::HighPass:return L"High-pass";case FxType11::Delay:return L"Delay";default:return L"Reverb";}}
COLORREF fxColor11(FxType11 t){int v=(int)t;return v<=5?RGB(230,104,76):v<=8?RGB(74,164,211):v<=10?RGB(75,190,151):RGB(160,101,214);}

void layout11(HWND h){layoutV6(h);RECT c;GetClientRect(h,&c);int right=std::max(760,(int)c.right-320);int editorTop=editorOpen?std::max(455,(int)(c.bottom*.64)):c.bottom-45;trackList10={0,126,198,editorTop};timeline10={198,126,right,editorTop};inspector10={(LONG)right,82,c.right,c.bottom};browser10={0,(LONG)editorTop,(LONG)right,c.bottom};}

double processFx11(double x,const Fx11&f,double&state){if(!f.on)return x;double a=f.amount/100.0;switch(f.type){case FxType11::SoftClip:return tanh(x*(1+a*8));case FxType11::HardClip:{double lim=1-a*.9;return std::clamp(x,-lim,lim)/std::max(.1,lim);}case FxType11::Overdrive:return atan(x*(1+a*14))*.75;case FxType11::Saturation:return x/(1+std::abs(x)*(a*5));case FxType11::Wavefold:return sin(x*(1+a*8)*2.2);case FxType11::Bitcrush:{double lv=std::max(4.0,260.0*(1-a));return floor(x*lv)/lv;}case FxType11::Compressor:{double th=.8-a*.6,ax=std::abs(x);if(ax>th)x=(x<0?-1:1)*(th+(ax-th)*(.5-a*.4));return x;}case FxType11::Limiter:{double lim=.95-a*.45;return std::clamp(x,-lim,lim);}case FxType11::Transient:return x*(1+a*.8);case FxType11::LowPass:{double k=.02+(1-a)*.45;state+=k*(x-state);return state;}case FxType11::HighPass:{double k=.02+(1-a)*.45;state+=k*(x-state);return x-state;}case FxType11::Delay:{double y=x+state*a*.7;state=state*.997+x*.003;return y;}case FxType11::Reverb:{double y=x+state*a*.5;state=state*.993+x*.007;return y;}}return x;}

void renderRange11(std::vector<int16_t>&out,int start){start=std::clamp(start,0,activeBars-1);int step=std::max(1,(int)(SR*60.0/bpm/4.0));size_t frames=(size_t)step*STEPS*(activeBars-start);out.assign(frames*2,0);std::vector<Voice>dv;std::vector<Voice9>nv;std::array<std::array<double,16>,V6_MAX_TRACKS> states{};bool solo=false;for(auto&l:lanes)if(l.solo)solo=true;for(size_t f=0;f<frames;f++){if(f%step==0){int g=(int)(f/step),b=start+g/STEPS,s=g%STEPS;if(!lanes.empty()&&!lanes[0].mute&&(!solo||lanes[0].solo))for(int r=0;r<DR;r++)if(drums[b][r][s])dv.push_back({r,0});for(int l=1;l<(int)lanes.size();l++){if(lanes[l].type==LaneType::Audio||lanes[l].mute||(solo&&!lanes[l].solo))continue;auto&clip=noteForLane(l,b);int base=familyOf(sound9[l])==Family9::Bass?47:71;for(int r=0;r<NOTES;r++)if(clip[r][s])nv.push_back({sound9[l],l,base-r});}}std::array<double,V6_MAX_TRACKS>mix{};for(auto&q:dv)mix[0]+=sample(q);for(auto&q:nv)if(q.lane>=0&&q.lane<(int)lanes.size())mix[q.lane]+=sample9(q);double masterMix=0;for(int l=0;l<(int)lanes.size();l++){if(lanes[l].mute||(solo&&!lanes[l].solo))continue;double y=mix[l]*(lanes[l].volume/100.0);for(size_t j=0;j<rack11[l].size();j++)y=processFx11(y,rack11[l][j],states[l][std::min<size_t>(j,15)]);masterMix+=y;}dv.erase(std::remove_if(dv.begin(),dv.end(),[](const Voice&q){return!alive(q);}),dv.end());nv.erase(std::remove_if(nv.begin(),nv.end(),[](const Voice9&q){return!alive9(q);}),nv.end());int16_t z=(int16_t)(std::clamp(masterMix*.20*(master/100.0),-1.0,1.0)*32767);out[f*2]=out[f*2+1]=z;}}
void play11(){if(playing){stopAudio();return;}playStartBar=cursorBar;renderRange11(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutWrite(wave,&waveHdr,sizeof(waveHdr));playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export11(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderRange11(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,align=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&align,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}

void addFxMenu11(HWND h,POINT p){if(laneSelected<0||laneSelected>=(int)lanes.size())return;HMENU root=CreatePopupMenu(),dist=CreatePopupMenu(),dyn=CreatePopupMenu(),filter=CreatePopupMenu(),space=CreatePopupMenu();for(int i=0;i<6;i++)AppendMenuW(dist,MF_STRING,67001+i,fxName11((FxType11)i));for(int i=6;i<9;i++)AppendMenuW(dyn,MF_STRING,67001+i,fxName11((FxType11)i));for(int i=9;i<11;i++)AppendMenuW(filter,MF_STRING,67001+i,fxName11((FxType11)i));for(int i=11;i<13;i++)AppendMenuW(space,MF_STRING,67001+i,fxName11((FxType11)i));AppendMenuW(root,MF_POPUP,(UINT_PTR)dist,L"Distortion / Color");AppendMenuW(root,MF_POPUP,(UINT_PTR)dyn,L"Dynamics");AppendMenuW(root,MF_POPUP,(UINT_PTR)filter,L"Filter");AppendMenuW(root,MF_POPUP,(UINT_PTR)space,L"Delay / Reverb");POINT s=p;ClientToScreen(h,&s);int cmd=TrackPopupMenu(root,TPM_RETURNCMD|TPM_RIGHTBUTTON,s.x,s.y,0,h,nullptr);DestroyMenu(root);if(cmd>=67001&&cmd<67014){rack11[laneSelected].push_back({(FxType11)(cmd-67001),true,50});InvalidateRect(h,nullptr,FALSE);}}

void drawInspector11(HDC d){panel10(d,inspector10,RGB(23,25,30));int x=(int)inspector10.left+16;label(d,L"INSPECTEUR",x,98,8,RGB(126,130,139),FW_BOLD);if(laneSelected<0||laneSelected>=(int)lanes.size())return;label(d,lanes[laneSelected].name.c_str(),x,117,15,RGB(241,242,245),FW_BOLD);int y=154;if(laneSelected>0&&lanes[laneSelected].type==LaneType::Instrument){instrument10={(LONG)x,(LONG)y,inspector10.right-16,(LONG)(y+44)};fill(d,instrument10,RGB(34,37,44));label(d,L"INSTRUMENT",x+12,y+7,7,RGB(126,130,139),FW_BOLD);label(d,soundName9(sound9[laneSelected]),x+12,y+23,10,RGB(231,116,84),FW_BOLD);y+=62;}else instrument10={0,0,0,0};label(d,L"EFFETS",x,y,8,RGB(126,130,139),FW_BOLD);y+=18;fxRects11.clear();auto&r=rack11[laneSelected];for(int i=fxScroll11;i<(int)r.size()&&y+58<(int)inspector10.bottom-55;i++){RECT q{(LONG)x,(LONG)y,inspector10.right-16,(LONG)(y+54)};fxRects11.push_back(q);COLORREF col=fxColor11(r[i].type);fill(d,q,RGB(34,37,44));fill(d,{q.left,q.top,q.left+4,q.bottom},r[i].on?col:RGB(73,76,83));label(d,fxName11(r[i].type),q.left+13,q.top+8,9,r[i].on?RGB(236,237,240):RGB(128,131,137),FW_BOLD);std::wstring v=std::to_wstring(r[i].amount)+L"%";label(d,v.c_str(),q.right-48,q.top+8,8,col,FW_BOLD);RECT bar{q.left+13,q.top+33,q.right-13,q.top+41};fill(d,bar,RGB(17,19,23));RECT f=bar;f.right=f.left+(f.right-f.left)*r[i].amount/100;fill(d,f,col);y+=62;}int at=std::min(y+5,(int)inspector10.bottom-44),ab=std::min(y+41,(int)inspector10.bottom-8);addFx11={(LONG)x,(LONG)at,inspector10.right-16,(LONG)ab};fill(d,addFx11,RGB(39,42,49));label(d,L"+  AJOUTER UN EFFET",addFx11.left+18,addFx11.top+11,9,RGB(203,205,210),FW_BOLD);}

void drawEditorTitle11(HDC d){if(!editorOpen)return;int y=(int)browser10.top;fill(d,{0,(LONG)y,inspector10.left,(LONG)(y+30)},RGB(25,27,32));std::wstring s=L"EDITEUR DU BLOC  ";s+=std::to_wstring(selectedBar+1);s+=L"  -  ";if(laneSelected>=0&&laneSelected<(int)lanes.size())s+=lanes[laneSelected].name;label(d,s.c_str(),18,y+9,8,RGB(175,178,185),FW_BOLD);}
void draw11(HDC d,RECT c){paint(d,c);paintExtraEditor(d);fill(d,{0,0,c.right,82},RGB(19,21,26));drawTop10(d,c);fill(d,{0,82,inspector10.left,126},RGB(26,28,33));button(d,addTrackR,L"+ PISTE");button(d,removeTrackR,L"SUPPR.");button(d,renameTrackR,L"RENOMMER");fill(d,{0,126,inspector10.left,browser10.top},RGB(21,23,28));drawTrackHeaders10(d);drawTimeline10(d);paintV6Selection(d);drawEditorTitle11(d);drawInspector11(d);}

bool hitTimeline11(POINT p,int&lane,int&bar){if(!inside(timeline10,p))return false;int width=std::max(1,(int)(timeline10.right-timeline10.left));int v=(int)((long long)(p.x-timeline10.left)*visibleBars/width);bar=scrollBar+v;if(bar<0||bar>=activeBars)return false;for(int i=0;i<(int)lanes.size();i++)if(p.y>=laneHeadR[i].top&&p.y<laneHeadR[i].bottom){lane=i;return true;}return false;}
LRESULT CALLBACK proc_v11(HWND h,UINT m,WPARAM wp,LPARAM lp){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(m==WM_SIZE){proc_v9(h,m,wp,lp);layout11(h);InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDOWN){if(inside(playR,p)){play11();return 0;}if(inside(wavR,p)){export11();return 0;}if(inside(addTrackR,p)){addTrack(h);layout11(h);return 0;}if(inside(removeTrackR,p)){removeTrack();layout11(h);return 0;}if(inside(renameTrackR,p)){renameTrack();return 0;}if(inside(inspector10,p)&&laneSelected>=0&&laneSelected<(int)lanes.size()){if(laneSelected>0&&inside(instrument10,p)){chooseInstrument9(h,laneSelected,p);return 0;}if(inside(addFx11,p)){addFxMenu11(h,p);return 0;}for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],p)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected][idx].on=!rack11[laneSelected][idx].on;InvalidateRect(h,nullptr,FALSE);return 0;}}return 0;}int lane,bar;if(hitTimeline11(p,lane,bar)){beginV6Selection(h,p,lane,bar);return 0;}}
if(m==WM_RBUTTONDOWN){if(inside(inspector10,p)&&laneSelected>=0){for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],p)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected].erase(rack11[laneSelected].begin()+idx);InvalidateRect(h,nullptr,FALSE);return 0;}}}int lane,bar;if(hitTimeline11(p,lane,bar)){showV6ClipMenu(h,p,lane,bar);return 0;}}
if(m==WM_MOUSEWHEEL&&laneSelected>=0&&laneSelected<(int)lanes.size()){POINT sp{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};ScreenToClient(h,&sp);for(size_t j=0;j<fxRects11.size();j++)if(inside(fxRects11[j],sp)){int idx=fxScroll11+(int)j;if(idx<(int)rack11[laneSelected].size()){rack11[laneSelected][idx].amount=std::clamp(rack11[laneSelected][idx].amount+(GET_WHEEL_DELTA_WPARAM(wp)>0?5:-5),0,100);InvalidateRect(h,nullptr,FALSE);return 0;}}}
if(m==WM_KEYDOWN&&wp==VK_SPACE){play11();return 0;}return proc_v9(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v11;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV11";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 5 - Functional DAW",WS_OVERLAPPEDWINDOW,0,0,1600,960,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;rack11[0]={{FxType11::SoftClip,true,35}};layout11(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
