// Boomify V6 - dynamic track workspace
#define BOOMIFY_V5_NO_ENTRY
#include "main_v5.cpp"
#undef BOOMIFY_V5_NO_ENTRY

namespace {
constexpr int V6_MAX_TRACKS=16;
enum class LaneType{Drums,Instrument,Audio};
struct Lane{std::wstring name;LaneType type=LaneType::Instrument;bool mute=false,solo=false;int volume=80;};
std::vector<Lane> lanes={{L"Drums",LaneType::Drums,false,false,85},{L"Bass",LaneType::Instrument,false,false,80},{L"Synth",LaneType::Instrument,false,false,80}};
int laneSelected=0; RECT addTrackR{},removeTrackR{},renameTrackR{},soloR[V6_MAX_TRACKS]{},laneMuteR[V6_MAX_TRACKS]{},laneVolR[V6_MAX_TRACKS]{},laneHeadR[V6_MAX_TRACKS]{};
std::array<std::array<NoteClip,MAX_BARS>,V6_MAX_TRACKS-3> extraNotes{};
void layoutV6(HWND h);void duplicateV6();
void relayoutV6AfterTimelineEdit(){if(win)layoutV6(win);}
NoteClip& noteForLane(int lane,int bar){if(lane==1)return bass[bar];if(lane==2)return melody[bar];return extraNotes[lane-3][bar];}
bool laneUsed(int lane,int bar){if(lane==0)return usedDrum(bar);if(lanes[lane].type==LaneType::Audio)return false;return usedNote(noteForLane(lane,bar));}
const wchar_t* typeLabel(LaneType t){return t==LaneType::Drums?L"BATTERIE":t==LaneType::Audio?L"AUDIO":L"INSTRUMENT";}
const int PICK_DRUM=62001,PICK_INST=62002,PICK_AUDIO=62003,PICK_CANCEL=62004;int pickChoice=0;HWND picker=nullptr;
LRESULT CALLBACK pickerProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_CREATE){CreateWindowW(L"STATIC",L"AJOUTER UNE PISTE",WS_CHILD|WS_VISIBLE,24,20,320,28,h,nullptr,nullptr,nullptr);CreateWindowW(L"STATIC",L"Choisis ce que cette piste doit faire.",WS_CHILD|WS_VISIBLE,24,52,330,22,h,nullptr,nullptr,nullptr);CreateWindowW(L"BUTTON",L"BATTERIE   - Programmer kicks, snares, hats...",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,24,88,390,46,h,(HMENU)(INT_PTR)PICK_DRUM,nullptr,nullptr);CreateWindowW(L"BUTTON",L"INSTRUMENT - Basse, synth, piano...",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,24,142,390,46,h,(HMENU)(INT_PTR)PICK_INST,nullptr,nullptr);CreateWindowW(L"BUTTON",L"AUDIO      - Import / enregistrement (bientot)",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,24,196,390,46,h,(HMENU)(INT_PTR)PICK_AUDIO,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Annuler",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,294,258,120,32,h,(HMENU)(INT_PTR)PICK_CANCEL,nullptr,nullptr);return 0;}if(m==WM_CTLCOLORSTATIC){HDC dc=(HDC)w;SetTextColor(dc,RGB(238,238,240));SetBkColor(dc,RGB(31,32,36));static HBRUSH br=CreateSolidBrush(RGB(31,32,36));return(LRESULT)br;}if(m==WM_ERASEBKGND){RECT r;GetClientRect(h,&r);HBRUSH b=CreateSolidBrush(RGB(31,32,36));FillRect((HDC)w,&r,b);DeleteObject(b);return 1;}if(m==WM_COMMAND){int id=LOWORD(w);if(id>=PICK_DRUM&&id<=PICK_CANCEL){pickChoice=id;DestroyWindow(h);return 0;}}if(m==WM_CLOSE){pickChoice=PICK_CANCEL;DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);}
LaneType chooseTrackType(HWND owner){HINSTANCE hi=(HINSTANCE)GetWindowLongPtrW(owner,GWLP_HINSTANCE);static bool reg=false;if(!reg){WNDCLASSW wc{};wc.lpfnWndProc=pickerProc;wc.hInstance=hi;wc.lpszClassName=L"BoomifyTrackPicker";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);reg=true;}pickChoice=0;picker=CreateWindowExW(WS_EX_TOPMOST,L"BoomifyTrackPicker",L"Boomify - Nouvelle piste",WS_POPUP|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,454,340,owner,nullptr,hi,nullptr);RECT r;GetWindowRect(picker,&r);SetWindowPos(picker,nullptr,(GetSystemMetrics(SM_CXSCREEN)-(r.right-r.left))/2,(GetSystemMetrics(SM_CYSCREEN)-(r.bottom-r.top))/2,0,0,SWP_NOSIZE|SWP_NOZORDER);EnableWindow(owner,FALSE);ShowWindow(picker,SW_SHOW);UpdateWindow(picker);MSG msg{};while(IsWindow(picker)&&GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}EnableWindow(owner,TRUE);SetForegroundWindow(owner);if(pickChoice==PICK_DRUM)return LaneType::Drums;if(pickChoice==PICK_AUDIO)return LaneType::Audio;return LaneType::Instrument;}
void addTrack(HWND owner){if((int)lanes.size()>=V6_MAX_TRACKS)return;LaneType t=chooseTrackType(owner);if(pickChoice==PICK_CANCEL||pickChoice==0)return;int count=1;for(auto&x:lanes)if(x.type==t)count++;std::wstring name=t==LaneType::Drums?L"Drums "+std::to_wstring(count):t==LaneType::Audio?L"Audio "+std::to_wstring(count):L"Instrument "+std::to_wstring(count);lanes.push_back({name,t,false,false,80});laneSelected=(int)lanes.size()-1;layoutV6(owner);InvalidateRect(owner,nullptr,FALSE);}
void removeTrack(){if(laneSelected<0||laneSelected>=(int)lanes.size()||lanes.size()<=1)return;if(laneSelected<3){MessageBoxW(win,L"Les trois pistes historiques restent verrouillees pendant la migration du format projet.",L"Boomify",MB_OK|MB_ICONINFORMATION);return;}int idx=laneSelected-3;for(int k=idx;k<V6_MAX_TRACKS-4;k++)extraNotes[k]=extraNotes[k+1];for(auto&c:extraNotes[V6_MAX_TRACKS-4])clearNote(c);lanes.erase(lanes.begin()+laneSelected);laneSelected=std::min(laneSelected,(int)lanes.size()-1);layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void renameTrack(){if(laneSelected<0||laneSelected>=(int)lanes.size())return;static int n=1;lanes[laneSelected].name=L"Track "+std::to_wstring(n++);InvalidateRect(win,nullptr,FALSE);}
void moveLane(int from,int to){if(from<3||to<3||from==to||from>=(int)lanes.size()||to>=(int)lanes.size())return;std::swap(lanes[from],lanes[to]);std::swap(extraNotes[from-3],extraNotes[to-3]);laneSelected=to;layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void layoutV6(HWND h){layout(h);RECT c;GetClientRect(h,&c);addTrackR={12,88,116,118};removeTrackR={122,88,214,118};renameTrackR={220,88,312,118};int top=128,bottom=editorOpen?std::max(455,(int)(c.bottom*.64)):c.bottom-45;int n=std::max(1,(int)lanes.size());int available=std::max(1,bottom-top);int rh=std::max(34,std::min(82,available/n));for(int i=0;i<V6_MAX_TRACKS;i++){laneHeadR[i]={0,0,0,0};laneMuteR[i]={0,0,0,0};soloR[i]={0,0,0,0};laneVolR[i]={0,0,0,0};}for(int i=0;i<n;i++){int y=top+i*rh;laneHeadR[i]={4,y,194,std::min(bottom,y+rh-2)};laneMuteR[i]={126,y+7,152,y+29};soloR[i]={158,y+7,184,y+29};laneVolR[i]={14,std::max(y+31,y+rh-13),112,std::max(y+37,y+rh-7)};}int left=200,right=c.right-20,width=std::max(1,right-left);for(int t=0;t<TRACKS;t++){trackR[t]={4,laneHeadR[t].top,194,laneHeadR[t].bottom};muteR[t]=laneMuteR[t];for(int v=0;v<visibleBars;v++){int x1=left+(int)((long long)v*width/visibleBars),x2=left+(int)((long long)(v+1)*width/visibleBars);clipR[t][v]={x1,laneHeadR[t].top,std::max(x1+1,x2-1),laneHeadR[t].bottom};}}}
RECT v6CellRect(int lane,int visible){RECT c;GetClientRect(win,&c);int left=200,right=c.right-20,width=std::max(1,right-left);int x1=left+(int)((long long)visible*width/visibleBars),x2=left+(int)((long long)(visible+1)*width/visibleBars);return{x1,laneHeadR[lane].top,std::max(x1+1,x2-1),laneHeadR[lane].bottom};}
bool hitLaneClip(POINT p,int&lane,int&bar){if(!win)return false;RECT c;GetClientRect(win,&c);int left=200,right=c.right-20;if(p.x<left||p.x>=right)return false;for(int i=0;i<(int)lanes.size();i++){if(p.y>=laneHeadR[i].top&&p.y<laneHeadR[i].bottom){int width=std::max(1,right-left);int v=(int)((long long)(p.x-left)*visibleBars/width);if(v>=0&&v<visibleBars){lane=i;bar=scrollBar+v;return bar<activeBars;}}}return false;}
bool hitLegacyLaneV6(POINT p,int&track,int&bar){int lane=-1;if(!hitLaneClip(p,lane,bar))return false;track=lane;return true;}
void selectRectV6(POINT a,POINT b){clearMulti();RECT rr{std::min(a.x,b.x),std::min(a.y,b.y),std::max(a.x,b.x)+1,std::max(a.y,b.y)+1};for(int t=0;t<(int)lanes.size();t++)for(int v=0;v<visibleBars;v++){int bar=scrollBar+v;if(bar>=activeBars)continue;RECT q=v6CellRect(t,v),inter{};if(IntersectRect(&inter,&rr,&q))addMulti(t,bar);}if(!multiSelection.empty()){laneSelected=multiSelection.front().track;selectedTrack=std::min(TRACKS-1,laneSelected);selectedBar=multiSelection.front().bar;}updateDebug(L"V6 SEL");InvalidateRect(win,nullptr,FALSE);}
void duplicateV6(){if(multiSelection.empty()){duplicateMulti();return;}if(selectingRange){selectingRange=false;rangeStartTrack=rangeStartBar=-1;if(GetCapture()==win)ReleaseCapture();}auto src=multiSelection;int minB=MAX_BARS,maxB=-1;for(auto&q:src){minB=std::min(minB,q.bar);maxB=std::max(maxB,q.bar);}int span=maxB-minB+1;if(span<=0)return;struct Snap{int lane,bar;DrumClip drum{};NoteClip note{};};std::vector<Snap> snap;snap.reserve(src.size());for(auto&q:src){if(q.track<0||q.track>=(int)lanes.size()||q.bar<0||q.bar>=MAX_BARS)continue;Snap s{};s.lane=q.track;s.bar=q.bar;if(q.track==0)s.drum=drums[q.bar];else s.note=noteForLane(q.track,q.bar);snap.push_back(s);}clearMulti();int first=MAX_BARS;for(auto&s:snap){int dst=s.bar+span;if(dst<0||dst>=MAX_BARS)continue;if(dst>=activeBars)activeBars=dst+1;if(s.lane==0)drums[dst]=s.drum;else if(lanes[s.lane].type!=LaneType::Audio)noteForLane(s.lane,dst)=s.note;addMulti(s.lane,dst);first=std::min(first,dst);}if(first<MAX_BARS){selectedBar=first;ensureVisible(first);}layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void paintV6Selection(HDC d){for(auto&q:multiSelection){if(q.track<0||q.track>=(int)lanes.size()||q.bar<scrollBar||q.bar>=scrollBar+visibleBars)continue;RECT r=v6CellRect(q.track,q.bar-scrollBar);line(d,r.left+1,r.top+1,r.right-1,r.top+1,RGB(255,255,255),3);line(d,r.left+1,r.bottom-2,r.right-1,r.bottom-2,RGB(255,255,255),3);line(d,r.left+1,r.top+1,r.left+1,r.bottom-1,RGB(255,255,255),3);line(d,r.right-2,r.top+1,r.right-2,r.bottom-1,RGB(255,255,255),3);}if(selectingRange){RECT r{std::min(rangeStart.x,rangeNow.x),std::min(rangeStart.y,rangeNow.y),std::max(rangeStart.x,rangeNow.x),std::max(rangeStart.y,rangeNow.y)};line(d,r.left,r.top,r.right,r.top,RGB(210,210,210));line(d,r.left,r.bottom,r.right,r.bottom,RGB(210,210,210));line(d,r.left,r.top,r.left,r.bottom,RGB(210,210,210));line(d,r.right,r.top,r.right,r.bottom,RGB(210,210,210));}}
void drawClipGridForLane(HDC d,RECT c,int lane,RECT row){for(int v=0;v<visibleBars;v++){int b=scrollBar+v;if(b>=activeBars)break;RECT r=v6CellRect(lane,v);bool used=laneUsed(lane,b);COLORREF base=used?(lane==0?RGB(53,145,116):lane==1?RGB(68,112,184):RGB(191,118,72)):RGB(28,29,31);fill(d,r,base);line(d,r.left,r.top,r.left,r.bottom,grid);if(b==cursorBar)fill(d,{r.left,r.top,r.left+2,r.bottom},accent);if(b==selectedBar&&lane==laneSelected){line(d,r.left+1,r.top+1,r.right-1,r.top+1,RGB(245,245,245),2);line(d,r.left+1,r.bottom-2,r.right-1,r.bottom-2,RGB(245,245,245),2);}}}
void paintExtraEditor(HDC d){if(!editorOpen||laneSelected<3||laneSelected>=(int)lanes.size()||lanes[laneSelected].type==LaneType::Audio)return;auto&clip=noteForLane(laneSelected,selectedBar);for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)if(np[r][s].right>np[r][s].left)fill(d,np[r][s],clip[r][s]?orange:cell);}
void drawV6(HDC d,RECT c){paint(d,c);paintExtraEditor(d);fill(d,{0,82,c.right,126},RGB(24,25,27));button(d,addTrackR,L"+ PISTE");button(d,removeTrackR,L"SUPPR.");button(d,renameTrackR,L"RENOMMER");int top=128,bottom=editorOpen?std::max(455,(int)(c.bottom*.64)):c.bottom-45;fill(d,{0,top,c.right,bottom},RGB(25,26,28));for(int i=0;i<(int)lanes.size();i++){RECT hr=laneHeadR[i];if(hr.bottom<=hr.top)continue;fill(d,hr,i==laneSelected?RGB(49,50,54):RGB(39,40,43));if(i==laneSelected)fill(d,{4,hr.top,8,hr.bottom},accent);label(d,lanes[i].name.c_str(),14,hr.top+6,11,txt,FW_BOLD);label(d,typeLabel(lanes[i].type),14,hr.top+22,8,RGB(150,153,158));button(d,laneMuteR[i],L"M",lanes[i].mute);button(d,soloR[i],L"S",lanes[i].solo);fill(d,laneVolR[i],RGB(18,19,21));int vw=(laneVolR[i].right-laneVolR[i].left)*lanes[i].volume/100;fill(d,{laneVolR[i].left,laneVolR[i].top,laneVolR[i].left+vw,laneVolR[i].bottom},accent);drawClipGridForLane(d,c,i,hr);}paintV6Selection(d);label(d,L"PISTES",330,96,10,RGB(175,177,181),FW_BOLD);}
void beginV6Selection(HWND h,POINT p,int lane,int bar){bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0,shift=(GetKeyState(VK_SHIFT)&0x8000)!=0;if(ctrl){if(isSelectedMulti(lane,bar))multiSelection.erase(std::remove_if(multiSelection.begin(),multiSelection.end(),[&](const BlockRef&q){return q.track==lane&&q.bar==bar;}),multiSelection.end());else addMulti(lane,bar);laneSelected=lane;selectedTrack=std::min(TRACKS-1,lane);selectedBar=bar;InvalidateRect(h,nullptr,FALSE);return;}if(shift){int from=std::min(selectedBar,bar),to=std::max(selectedBar,bar);clearMulti();for(int x=from;x<=to;x++)addMulti(lane,x);laneSelected=lane;selectedTrack=std::min(TRACKS-1,lane);InvalidateRect(h,nullptr,FALSE);return;}clearMulti();addMulti(lane,bar);laneSelected=lane;selectedTrack=std::min(TRACKS-1,lane);selectedBar=bar;selectingRange=true;rangeStart=rangeNow=p;rangeStartTrack=lane;rangeStartBar=bar;SetCapture(h);InvalidateRect(h,nullptr,FALSE);}
enum{V6_CTX_COPY=63001,V6_CTX_PASTE,V6_CTX_DUP,V6_CTX_CLEAR,V6_CTX_CURSOR};
void clearV6Selection(){if(multiSelection.empty()){if(laneSelected==0)clearDrum(selectedBar);else if(laneSelected<(int)lanes.size()&&lanes[laneSelected].type!=LaneType::Audio)clearNote(noteForLane(laneSelected,selectedBar));}else for(auto&q:multiSelection){if(q.track==0)clearDrum(q.bar);else if(q.track<(int)lanes.size()&&lanes[q.track].type!=LaneType::Audio)clearNote(noteForLane(q.track,q.bar));}InvalidateRect(win,nullptr,FALSE);}
void showV6ClipMenu(HWND h,POINT client,int lane,int bar){if(!isSelectedMulti(lane,bar)){clearMulti();addMulti(lane,bar);}laneSelected=lane;selectedTrack=std::min(TRACKS-1,lane);selectedBar=bar;HMENU menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,V6_CTX_COPY,L"Copier\tCtrl+C");AppendMenuW(menu,MF_STRING,V6_CTX_PASTE,L"Coller\tCtrl+V");AppendMenuW(menu,MF_STRING,V6_CTX_DUP,L"Dupliquer\tCtrl+D");AppendMenuW(menu,MF_SEPARATOR,0,nullptr);AppendMenuW(menu,MF_STRING,V6_CTX_CURSOR,L"Placer le curseur de lecture ici");AppendMenuW(menu,MF_SEPARATOR,0,nullptr);AppendMenuW(menu,MF_STRING,V6_CTX_CLEAR,L"Vider ce bloc\tSuppr");POINT screen=client;ClientToScreen(h,&screen);int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_RIGHTBUTTON,screen.x,screen.y,0,h,nullptr);DestroyMenu(menu);switch(cmd){case V6_CTX_COPY:copyMulti();break;case V6_CTX_PASTE:pasteMulti();break;case V6_CTX_DUP:duplicateV6();break;case V6_CTX_CLEAR:clearV6Selection();break;case V6_CTX_CURSOR:cursorBar=bar;InvalidateRect(h,nullptr,FALSE);break;}}
void selectExtraCell(int lane,int bar){laneSelected=lane;selectedTrack=2;selectedBar=bar;clearMulti();InvalidateRect(win,nullptr,FALSE);}
bool editExtraAt(POINT p){if(laneSelected<3||laneSelected>=(int)lanes.size()||lanes[laneSelected].type==LaneType::Audio)return false;auto&clip=noteForLane(laneSelected,selectedBar);for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)if(inside(np[r][s],p)){clip[r][s]=!clip[r][s];InvalidateRect(win,nullptr,FALSE);return true;}return false;}
void v6Fresh(){freshEmpty();clearMulti();for(auto&a:extraNotes)for(auto&c:a)clearNote(c);lanes={{L"Drums",LaneType::Drums,false,false,85},{L"Bass",LaneType::Instrument,false,false,80},{L"Synth",LaneType::Instrument,false,false,80}};laneSelected=0;postTimelineLayoutHook=relayoutV6AfterTimelineEdit;timelineHitHook=hitLegacyLaneV6;timelineRectSelectHook=selectRectV6;contextDuplicateHook=duplicateV6;layoutV6(win);}
LRESULT CALLBACK proc_v6(HWND h,UINT m,WPARAM wp,LPARAM lp){if(m==WM_SIZE){proc_v5(h,m,wp,lp);layoutV6(h);InvalidateRect(h,nullptr,FALSE);return 0;}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);drawV6(mem,c);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_RBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};int lane,bar;if(hitLaneClip(p,lane,bar)){showV6ClipMenu(h,p,lane,bar);return 0;}}if(m==WM_KEYDOWN&&((GetKeyState(VK_CONTROL)&0x8000)!=0)&&wp=='D'){duplicateV6();return 0;}if(m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(inside(dupR,p)){duplicateV6();return 0;}if(inside(addTrackR,p)){addTrack(h);return 0;}if(inside(removeTrackR,p)){removeTrack();return 0;}if(inside(renameTrackR,p)){renameTrack();return 0;}for(int i=0;i<(int)lanes.size();i++){if(inside(laneMuteR[i],p)){lanes[i].mute=!lanes[i].mute;if(i<3)muted[i]=lanes[i].mute;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(soloR[i],p)){lanes[i].solo=!lanes[i].solo;InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(laneVolR[i],p)){int width=(int)(laneVolR[i].right-laneVolR[i].left),raw=(int)(p.x-laneVolR[i].left)*100/std::max(1,width);lanes[i].volume=std::clamp(raw,0,100);InvalidateRect(h,nullptr,FALSE);return 0;}}int lane,bar;if(hitLaneClip(p,lane,bar)){beginV6Selection(h,p,lane,bar);return 0;}if(editExtraAt(p))return 0;for(int i=0;i<(int)lanes.size();i++)if(inside(laneHeadR[i],p)){laneSelected=i;if(i<3)selectedTrack=i;InvalidateRect(h,nullptr,FALSE);return 0;}}if(m==WM_KEYDOWN&&wp==VK_UP&&laneSelected>3){moveLane(laneSelected,laneSelected-1);return 0;}if(m==WM_KEYDOWN&&wp==VK_DOWN&&laneSelected>=3&&laneSelected+1<(int)lanes.size()){moveLane(laneSelected,laneSelected+1);return 0;}return proc_v5(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v6;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV6";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 3 - Track Workspace",WS_OVERLAPPEDWINDOW,0,0,1500,920,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();layoutV6(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
