#include <windows.h>
#include <windowsx.h>
#include <mmsystem.h>
#include <commdlg.h>
#include <array>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <string>
#include <vector>
#pragma comment(lib,"winmm.lib")
#pragma comment(lib,"comdlg32.lib")

namespace {
constexpr int STEPS=16, DR=4, NOTES=12, TRACKS=3, VISIBLE=16, MAX_BARS=512, SR=44100;
using DrumClip=std::array<std::array<bool,STEPS>,DR>;
using NoteClip=std::array<std::array<bool,STEPS>,NOTES>;
std::array<DrumClip,MAX_BARS> drums{};
std::array<NoteClip,MAX_BARS> bass{},melody{};
int activeBars=16,selectedTrack=0,selectedBar=0,scrollBar=0,bpm=150,master=55;
bool copied=false; int copiedTrack=0; DrumClip copiedDrum{}; NoteClip copiedNote{};
HWND win{}; HWAVEOUT wave{}; WAVEHDR waveHdr{}; std::vector<int16_t> playBuffer; bool playing=false;
RECT newR{},openR{},saveR{},wavR{},addR{},prevR{},nextR{},playR{},minusR{},plusR{},volR{};
RECT trackR[TRACKS]{},clipR[TRACKS][VISIBLE]{},dp[DR][STEPS]{},np[NOTES][STEPS]{};
COLORREF bg=RGB(17,18,20),topc=RGB(34,35,37),panel=RGB(29,30,32),side=RGB(37,38,40),cell=RGB(43,44,47),grid=RGB(55,56,59),txt=RGB(224,225,228),mut=RGB(145,147,151),accent=RGB(211,104,76),orange=RGB(205,132,62),green=RGB(111,166,88);

void fill(HDC d,RECT r,COLORREF c){HBRUSH b=CreateSolidBrush(c);FillRect(d,&r,b);DeleteObject(b);} 
void line(HDC d,int x1,int y1,int x2,int y2,COLORREF c){HPEN p=CreatePen(PS_SOLID,1,c);auto o=SelectObject(d,p);MoveToEx(d,x1,y1,nullptr);LineTo(d,x2,y2);SelectObject(d,o);DeleteObject(p);} 
void label(HDC d,const wchar_t*s,int x,int y,int z,COLORREF c,int wt=FW_NORMAL){HFONT f=CreateFontW(-z,0,0,0,wt,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI");auto o=SelectObject(d,f);SetBkMode(d,TRANSPARENT);SetTextColor(d,c);TextOutW(d,x,y,s,(int)wcslen(s));SelectObject(d,o);DeleteObject(f);} 
void button(HDC d,RECT r,const wchar_t*s,bool on=false){fill(d,r,on?accent:panel);label(d,s,r.left+9,r.top+7,11,on?RGB(20,20,20):txt,FW_BOLD);} 
bool inside(RECT r,POINT p){return PtInRect(&r,p)!=0;}

void clearBar(int tr,int b){if(b<0||b>=activeBars)return;if(tr==0)for(auto&r:drums[b])r.fill(false);else if(tr==1)for(auto&r:bass[b])r.fill(false);else for(auto&r:melody[b])r.fill(false);} 
bool usedDrum(int b){for(auto&r:drums[b])for(bool x:r)if(x)return true;return false;} 
bool usedNote(const NoteClip&c){for(auto&r:c)for(bool x:r)if(x)return true;return false;}
void fresh(){for(int b=0;b<MAX_BARS;b++){clearBar(0,b);for(auto&r:bass[b])r.fill(false);for(auto&r:melody[b])r.fill(false);}activeBars=16;selectedTrack=selectedBar=scrollBar=0;bpm=150;master=55;copied=false;for(int s:{0,4,8,12})drums[0][0][s]=true;drums[0][1][4]=drums[0][1][12]=true;for(int s:{2,6,10,14})drums[0][3][s]=true;InvalidateRect(win,nullptr,FALSE);} 
void addBars(){activeBars=std::min(MAX_BARS,activeBars+8);InvalidateRect(win,nullptr,FALSE);} 
void copyClip(){if(selectedBar<0||selectedBar>=activeBars)return;copied=true;copiedTrack=selectedTrack;if(selectedTrack==0)copiedDrum=drums[selectedBar];else copiedNote=selectedTrack==1?bass[selectedBar]:melody[selectedBar];}
void pasteClip(){if(!copied||selectedBar<0||selectedBar>=activeBars)return;if(selectedTrack==0&&copiedTrack==0)drums[selectedBar]=copiedDrum;else if(selectedTrack>0&&copiedTrack>0)(selectedTrack==1?bass[selectedBar]:melody[selectedBar])=copiedNote;else return;InvalidateRect(win,nullptr,FALSE);} 

std::wstring dialog(bool save,const wchar_t*filter,const wchar_t*ext){wchar_t p[MAX_PATH]=L"";OPENFILENAMEW o{};o.lStructSize=sizeof(o);o.hwndOwner=win;o.lpstrFile=p;o.nMaxFile=MAX_PATH;o.lpstrFilter=filter;o.lpstrDefExt=ext;o.Flags=OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return(save?GetSaveFileNameW(&o):GetOpenFileNameW(&o))?p:L"";}
void saveProject(){auto p=dialog(true,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return;std::ofstream o(p);o<<"BOOMIFY8 "<<bpm<<' '<<master<<' '<<activeBars<<'\n';for(int b=0;b<activeBars;b++)for(auto&r:drums[b]){for(bool x:r)o<<(x?1:0);o<<'\n';}for(int b=0;b<activeBars;b++)for(auto&r:bass[b]){for(bool x:r)o<<(x?1:0);o<<'\n';}for(int b=0;b<activeBars;b++)for(auto&r:melody[b]){for(bool x:r)o<<(x?1:0);o<<'\n';}}
void openProject(){auto p=dialog(false,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return;std::ifstream i(p);std::string magic,row;int nb,bb,mm;if(!(i>>magic>>bb>>mm>>nb)||magic!="BOOMIFY8"||nb<1||nb>MAX_BARS){MessageBoxW(win,L"Projet incompatible ou endommage.",L"Boomify",MB_OK|MB_ICONWARNING);return;}fresh();activeBars=nb;bpm=std::clamp(bb,60,220);master=std::clamp(mm,0,100);for(int b=0;b<activeBars;b++)for(auto&r:drums[b]){i>>row;for(int s=0;s<STEPS;s++)r[s]=s<(int)row.size()&&row[s]=='1';}for(int b=0;b<activeBars;b++)for(auto&r:bass[b]){i>>row;for(int s=0;s<STEPS;s++)r[s]=s<(int)row.size()&&row[s]=='1';}for(int b=0;b<activeBars;b++)for(auto&r:melody[b]){i>>row;for(int s=0;s<STEPS;s++)r[s]=s<(int)row.size()&&row[s]=='1';}InvalidateRect(win,nullptr,FALSE);}

struct Voice{int kind,note,age=0;double ph=0;}; double hz(int n){return 440.0*pow(2.0,(n-69)/12.0);} double rnd(uint32_t x){x^=x<<13;x^=x>>17;x^=x<<5;return((x&65535)/32767.5)-1;}
double sample(Voice&v){double t=v.age/(double)SR,o=0;if(v.kind==0){double f=48+110*exp(-t*35);v.ph+=2*3.141592653589793*f/SR;o=sin(v.ph)*exp(-t*16);}else if(v.kind<4)o=.35*rnd(v.age*747796405u+v.kind*91)*exp(-t*(v.kind==3?55:22));else{v.ph+=hz(v.note)/SR;if(v.ph>=1)v.ph-=1;double s=sin(2*3.141592653589793*v.ph),saw=2*v.ph-1;o=(v.kind==4?saw*.65+s*.35:s*.72+saw*.28)*exp(-t*(v.kind==4?3.2:2.0));}v.age++;return o;} bool alive(const Voice&v){double q[]={.30,.22,.16,.10,.42,.62};return v.age<q[v.kind]*SR;}
void trigger(std::vector<Voice>&v,int b,int s){for(int r=0;r<DR;r++)if(drums[b][r][s])v.push_back({r,0});for(int r=0;r<NOTES;r++)if(bass[b][r][s])v.push_back({4,47-r});for(int r=0;r<NOTES;r++)if(melody[b][r][s])v.push_back({5,71-r});}
void render(std::vector<int16_t>&out){int step=std::max(1,(int)(SR*60.0/bpm/4.0));size_t frames=(size_t)step*STEPS*activeBars;out.assign(frames*2,0);std::vector<Voice>v;for(size_t f=0;f<frames;f++){if(f%step==0){int g=(int)(f/step);trigger(v,g/STEPS,g%STEPS);}double x=0;for(auto&q:v)x+=sample(q);v.erase(std::remove_if(v.begin(),v.end(),[](const Voice&q){return!alive(q);}),v.end());int16_t z=(int16_t)(std::clamp(x*.24*(master/100.0),-1.0,1.0)*32767);out[f*2]=out[f*2+1]=z;}}
void stopAudio(){if(!playing)return;waveOutReset(wave);waveOutUnprepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutClose(wave);wave=nullptr;playing=false;playBuffer.clear();InvalidateRect(win,nullptr,FALSE);} 
void playAudio(){if(playing){stopAudio();return;}render(playBuffer);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,0,0,CALLBACK_NULL)!=MMSYSERR_NOERROR){MessageBoxW(win,L"Sortie audio Windows indisponible.",L"Boomify",MB_OK|MB_ICONERROR);return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutWrite(wave,&waveHdr,sizeof(waveHdr));playing=true;InvalidateRect(win,nullptr,FALSE);} 
void exportWav(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;render(a);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,align=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&align,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);} 

void layout(HWND h){RECT c;GetClientRect(h,&c);int w=c.right,H=c.bottom;newR={20,35,78,65};openR={84,35,145,65};saveR={151,35,210,65};wavR={216,35,275,65};addR={290,35,365,65};prevR={375,35,410,65};nextR={415,35,450,65};playR={w/2-35,30,w/2+35,68};minusR={w/2+92,33,w/2+120,64};plusR={w/2+184,33,w/2+212,64};volR={w-180,43,w-65,54};int left=180,right=w-20,top=112,bottom=std::max(430,(int)(H*.61)),th=(bottom-top)/TRACKS,aw=std::max(1,(right-left)/VISIBLE);for(int r=0;r<TRACKS;r++){trackR[r]={10,top+r*th,left-8,top+(r+1)*th-2};for(int v=0;v<VISIBLE;v++)clipR[r][v]={left+v*aw,top+r*th+4,left+(v+1)*aw-2,top+(r+1)*th-5};}int et=bottom+62,eb=H-22,el=105,er=w-25,gap=2,dw=std::max(5,(er-el-gap*15)/16),dh=std::max(12,(eb-et)/DR);for(int r=0;r<DR;r++)for(int s=0;s<STEPS;s++)dp[r][s]={el+s*(dw+gap),et+r*dh,el+s*(dw+gap)+dw,et+(r+1)*dh-2};int nw=std::max(5,(er-el)/STEPS),nh=std::max(8,(eb-et)/NOTES);for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)np[r][s]={el+s*nw,et+r*nh,el+(s+1)*nw-1,et+(r+1)*nh-1};}
void paint(HDC d,RECT c){int w=c.right,H=c.bottom;fill(d,c,bg);fill(d,{0,0,w,82},topc);label(d,L"Boomify",20,7,17,txt,FW_BOLD);button(d,newR,L"NEW");button(d,openR,L"OPEN");button(d,saveR,L"SAVE");button(d,wavR,L"WAV");button(d,addR,L"+8 BAR");button(d,prevR,L"<");button(d,nextR,L">");button(d,playR,playing?L"STOP":L"PLAY",playing);label(d,L"BPM",w/2+48,40,11,mut,FW_BOLD);button(d,minusR,L"-");wchar_t z[128];swprintf_s(z,L"%d",bpm);label(d,z,w/2+137,37,17,txt,FW_BOLD);button(d,plusR,L"+");label(d,L"MASTER",w-250,39,10,mut,FW_BOLD);fill(d,volR,grid);fill(d,{volR.left,volR.top,volR.left+(volR.right-volR.left)*master/100,volR.bottom},accent);int left=180,top=112,bottom=std::max(430,(int)(H*.61)),th=(bottom-top)/TRACKS,aw=std::max(1,(w-20-left)/VISIBLE);fill(d,{0,82,w,bottom},RGB(23,24,26));swprintf_s(z,L"TIMELINE   %d mesures   |   Ctrl+C / Ctrl+V",activeBars);label(d,z,18,91,10,txt,FW_BOLD);for(int v=0;v<VISIBLE;v++){int b=scrollBar+v;if(b>=activeBars)break;int x=left+v*aw;line(d,x,106,x,bottom,grid);swprintf_s(z,L"%d",b+1);label(d,z,x+4,91,10,mut,FW_BOLD);}const wchar_t*tn[]={L"DRUMS",L"BASS",L"MELODY"};COLORREF tc[]={accent,orange,green};for(int r=0;r<TRACKS;r++){fill(d,trackR[r],selectedTrack==r?RGB(48,49,52):side);fill(d,{trackR[r].left,trackR[r].top,trackR[r].left+5,trackR[r].bottom},tc[r]);label(d,tn[r],24,trackR[r].top+18,13,txt,FW_BOLD);for(int v=0;v<VISIBLE;v++){int b=scrollBar+v;if(b>=activeBars)break;bool u=r==0?usedDrum(b):(r==1?usedNote(bass[b]):usedNote(melody[b]));bool sel=selectedTrack==r&&selectedBar==b;fill(d,clipR[r][v],u?tc[r]:(sel?RGB(65,66,69):RGB(29,30,32)));if(sel){line(d,clipR[r][v].left,clipR[r][v].top,clipR[r][v].right,clipR[r][v].top,RGB(245,245,245));line(d,clipR[r][v].left,clipR[r][v].bottom-1,clipR[r][v].right,clipR[r][v].bottom-1,RGB(245,245,245));}}}fill(d,{0,bottom,w,H},panel);line(d,0,bottom,w,bottom,grid);selectedBar=std::clamp(selectedBar,0,activeBars-1);swprintf_s(z,L"%s - MESURE %d",selectedTrack==0?L"DRUM EDITOR":L"PIANO ROLL",selectedBar+1);label(d,z,18,bottom+15,13,txt,FW_BOLD);label(d,L"Chaque case est independante. Copie-colle par valeur, jamais liee a l'original.",18,bottom+36,10,mut);if(selectedTrack==0){const wchar_t*n[]={L"KICK",L"SNARE",L"CLAP",L"HI-HAT"};for(int r=0;r<DR;r++){label(d,n[r],18,dp[r][0].top+5,10,mut,FW_BOLD);for(int s=0;s<STEPS;s++)fill(d,dp[r][s],drums[selectedBar][r][s]?accent:cell);}}else{const wchar_t*n[]={L"B",L"A#",L"A",L"G#",L"G",L"F#",L"F",L"E",L"D#",L"D",L"C#",L"C"};auto&g=selectedTrack==1?bass[selectedBar]:melody[selectedBar];COLORREF cc=selectedTrack==1?orange:green;for(int r=0;r<NOTES;r++){label(d,n[r],68,np[r][0].top,9,mut);for(int s=0;s<STEPS;s++)fill(d,np[r][s],g[r][s]?cc:cell);}}}

LRESULT CALLBACK proc(HWND h,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_ERASEBKGND:return 1;case WM_SIZE:layout(h);return 0;case WM_KEYDOWN:if((GetKeyState(VK_CONTROL)&0x8000)&&wp=='C'){copyClip();return 0;}if((GetKeyState(VK_CONTROL)&0x8000)&&wp=='V'){pasteClip();return 0;}if(wp==VK_SPACE){playAudio();return 0;}if(wp==VK_LEFT){scrollBar=std::max(0,scrollBar-8);InvalidateRect(h,nullptr,FALSE);return 0;}if(wp==VK_RIGHT){scrollBar=std::min(std::max(0,activeBars-VISIBLE),scrollBar+8);InvalidateRect(h,nullptr,FALSE);return 0;}break;case WM_LBUTTONDOWN:{POINT q{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(inside(newR,q)){fresh();return 0;}if(inside(openR,q)){openProject();return 0;}if(inside(saveR,q)){saveProject();return 0;}if(inside(wavR,q)){exportWav();return 0;}if(inside(addR,q)){addBars();return 0;}if(inside(prevR,q)){scrollBar=std::max(0,scrollBar-8);InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(nextR,q)){scrollBar=std::min(std::max(0,activeBars-VISIBLE),scrollBar+8);InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(playR,q)){playAudio();return 0;}if(inside(minusR,q)){bpm=std::max(60,bpm-1);InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(plusR,q)){bpm=std::min(220,bpm+1);InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(volR,q)){master=std::clamp((int)((q.x-volR.left)*100L/std::max(1L,volR.right-volR.left)),0,100);InvalidateRect(h,nullptr,FALSE);return 0;}for(int r=0;r<TRACKS;r++)for(int v=0;v<VISIBLE;v++)if(inside(clipR[r][v],q)){int b=scrollBar+v;if(b<activeBars){selectedTrack=r;selectedBar=b;InvalidateRect(h,nullptr,FALSE);}return 0;}if(selectedTrack==0){for(int r=0;r<DR;r++)for(int s=0;s<STEPS;s++)if(inside(dp[r][s],q)){drums[selectedBar][r][s]=!drums[selectedBar][r][s];InvalidateRect(h,nullptr,FALSE);return 0;}}else{auto&g=selectedTrack==1?bass[selectedBar]:melody[selectedBar];for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)if(inside(np[r][s],q)){g[r][s]=!g[r][s];InvalidateRect(h,nullptr,FALSE);return 0;}}return 0;}case WM_RBUTTONDOWN:{POINT q{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};for(int r=0;r<TRACKS;r++)for(int v=0;v<VISIBLE;v++)if(inside(clipR[r][v],q)){int b=scrollBar+v;if(b<activeBars){clearBar(r,b);InvalidateRect(h,nullptr,FALSE);}return 0;}return 0;}case WM_PAINT:{PAINTSTRUCT ps;HDC dc=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(dc);HBITMAP bm=CreateCompatibleBitmap(dc,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);paint(mem,c);BitBlt(dc,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}case WM_DESTROY:stopAudio();PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,wp,lp);} }

int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc;wc.hInstance=hi;wc.lpszClassName=L"BoomifySafe";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);if(!RegisterClassW(&wc))return 1;win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 2 - Safe Timeline",WS_OVERLAPPEDWINDOW,0,0,1500,920,nullptr,nullptr,hi,nullptr);if(!win)return 2;layout(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
