// Boomify V15 - Alpha 6 DAW expansion
#define BOOMIFY_V15_INCLUDE
#define proc_v14 proc_v14_base15
#include "main_v14.cpp"
#undef proc_v14
#undef BOOMIFY_V15_INCLUDE

#include <cmath>

namespace {
struct Sample15{std::wstring path;int bar=-1;std::vector<int16_t> pcm;};
struct Kick15{bool enabled=false;int pitch=42,decay=38,punch=42,drive=22;};
std::array<Sample15,V6_MAX_TRACKS> samples15{}; std::array<Kick15,V6_MAX_TRACKS> kicks15{}; std::array<COLORREF,V6_MAX_TRACKS> colors15{};
RECT import15{},boom15{},master15{}; std::array<RECT,V6_MAX_TRACKS> colorHit15{},nameHit15{}; RECT kpMinus15{},kpPlus15{},kdMinus15{},kdPlus15{},kuMinus15{},kuPlus15{},krMinus15{},krPlus15{}; bool masterOn15=true;
COLORREF defaultColor15(int i){static COLORREF c[]={RGB(220,96,69),RGB(69,132,210),RGB(162,93,205),RGB(62,169,126),RGB(220,154,55),RGB(205,76,118),RGB(70,170,181),RGB(130,139,151)};return c[i%8];}
bool loadWav15(const std::wstring&p,std::vector<int16_t>&out){std::ifstream f(p,std::ios::binary);if(!f)return false;char id[4];uint32_t n=0;f.read(id,4);f.read((char*)&n,4);f.read(id,4);if(!f||std::string(id,4)!="WAVE")return false;uint16_t fmt=0,ch=0,bits=0;uint32_t rate=0;std::vector<char> data;while(f.read(id,4)){uint32_t sz=0;f.read((char*)&sz,4);if(!f)break;if(std::string(id,4)=="fmt "){uint16_t al=0;uint32_t br=0;f.read((char*)&fmt,2);f.read((char*)&ch,2);f.read((char*)&rate,4);f.read((char*)&br,4);f.read((char*)&al,2);f.read((char*)&bits,2);if(sz>16)f.seekg(sz-16,std::ios::cur);}else if(std::string(id,4)=="data"){data.resize(sz);f.read(data.data(),sz);}else f.seekg(sz,std::ios::cur);if(sz&1)f.seekg(1,std::ios::cur);}if(fmt!=1||bits!=16||(ch!=1&&ch!=2)||rate!=SR||data.empty())return false;const int16_t*s=(const int16_t*)data.data();size_t frames=data.size()/(2*ch);out.resize(frames*2);for(size_t i=0;i<frames;i++){int16_t a=s[i*ch],b=ch==2?s[i*ch+1]:a;out[i*2]=a;out[i*2+1]=b;}return true;}
void mixSample15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);long long bf=(long long)(secBar*SR);for(int l=0;l<(int)lanes.size();l++){auto&s=samples15[l];if(s.bar<0||s.pcm.empty()||lanes[l].mute)continue;long long dst=((long long)s.bar-startBar)*bf;if(dst<0)continue;double g=lanes[l].volume/100.0;for(size_t k=0;k+1<s.pcm.size();k+=2){size_t j=(size_t)(dst+(long long)k/2)*2;if(j+1>=a.size())break;for(int c=0;c<2;c++)a[j+c]=(int16_t)std::clamp((int)a[j+c]+(int)(s.pcm[k+c]*g),-32768,32767);}}}
void mixBoom15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);long long bf=(long long)(secBar*SR),sf=bf/STEPS;for(int l=0;l<(int)lanes.size();l++){if(!kicks15[l].enabled||lanes[l].mute||lanes[l].type!=LaneType::Drums)continue;auto&k=kicks15[l];for(int b=startBar;b<activeBars;b++){auto&d=drumForLane11(l,b);for(int s=0;s<STEPS;s++)if(d[0][s]){long long st=((long long)b-startBar)*bf+(long long)s*sf,len=std::min<long long>((long long)(SR*(0.055+k.decay*0.0032)),sf);double ph=0;for(long long q=0;q<len;q++){double t=(double)q/SR;double env=std::exp(-t*(13.0+(100-k.decay)*0.11));double hz=38.0+k.pitch*0.95+(95.0*k.punch/100.0)*std::exp(-t*42.0);ph+=6.283185307179586*hz/SR;double body=std::sin(ph)*env*(0.48+0.20*k.punch/100.0);double click=(q<(long long)(SR*0.0025))?(1.0-(double)q/(SR*0.0025))*0.12*k.punch/100.0:0.0;double drv=1.0+k.drive/35.0;double x=std::tanh((body+click)*drv)/std::tanh(drv);size_t j=(size_t)(st+q)*2;if(j+1>=a.size())break;int add=(int)(x*10500.0*lanes[l].volume/100.0);for(int c=0;c<2;c++)a[j+c]=(int16_t)std::clamp((int)a[j+c]+add,-32768,32767);}}}}}
void masterBus15(std::vector<int16_t>&a){double outGain=std::clamp(master,0,100)/100.0;if(!masterOn15){for(auto&v:a)v=(int16_t)std::lrint(v*outGain);return;}double env=0;for(auto&v:a){double x=v/32768.0;env=std::max(std::abs(x),env*0.9993);double cg=env>0.55?std::pow(0.55/env,0.30):1.0;x*=cg*1.12;x=std::tanh(x*1.08)/std::tanh(1.08);x*=outGain;v=(int16_t)std::lrint(std::clamp(x,-0.94,0.94)*32767.0);}}
void render15(std::vector<int16_t>&a,int start){renderRange11(a,start);mixSample15(a,start);mixBoom15(a,start);masterBus15(a);}
void play15(){if(playing){stopAudio();return;}playStartBar=cursorBar;render15(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*2,0xFFFFFFFFu);waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutWrite(wave,&waveHdr,sizeof(waveHdr));playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export15(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;render15(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
std::wstring editText15(HWND owner,const std::wstring&initial){HINSTANCE hi=(HINSTANCE)GetWindowLongPtrW(owner,GWLP_HINSTANCE);static std::wstring result;result=initial;static HWND ed=nullptr;static bool reg=false;if(!reg){WNDCLASSW wc{};wc.hInstance=hi;wc.lpszClassName=L"BoomifyRename15";wc.lpfnWndProc=[](HWND h,UINT m,WPARAM w,LPARAM l)->LRESULT{if(m==WM_CREATE){ed=CreateWindowW(L"EDIT",result.c_str(),WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,14,14,280,26,h,(HMENU)1,nullptr,nullptr);CreateWindowW(L"BUTTON",L"OK",WS_CHILD|WS_VISIBLE,218,48,76,26,h,(HMENU)2,nullptr,nullptr);SetFocus(ed);SendMessageW(ed,EM_SETSEL,0,-1);return 0;}if(m==WM_COMMAND&&LOWORD(w)==2){wchar_t b[128]{};GetWindowTextW(ed,b,128);result=b;DestroyWindow(h);return 0;}if(m==WM_CLOSE){result.clear();DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);};RegisterClassW(&wc);reg=true;}HWND q=CreateWindowExW(WS_EX_TOPMOST,L"BoomifyRename15",L"Renommer la piste",WS_POPUP|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,325,115,owner,nullptr,hi,nullptr);EnableWindow(owner,FALSE);ShowWindow(q,SW_SHOW);MSG msg{};while(IsWindow(q)&&GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}EnableWindow(owner,TRUE);SetForegroundWindow(owner);return result;}
void renameLane15(int l){if(l<0||l>=(int)lanes.size())return;auto s=editText15(win,lanes[l].name);if(!s.empty())lanes[l].name=s;InvalidateRect(win,nullptr,FALSE);}
void cycleColorLane15(int l){if(l<0||l>=(int)lanes.size())return;static int ci[V6_MAX_TRACKS]{};colors15[l]=defaultColor15(++ci[l]+l);InvalidateRect(win,nullptr,FALSE);}
void importSample15(){if(laneSelected<0||laneSelected>=(int)lanes.size()||lanes[laneSelected].type!=LaneType::Audio){MessageBoxW(win,L"Ajoute ou selectionne une piste AUDIO.",L"Boomify Sample",MB_OK);return;}auto p=dialog(false,L"WAV PCM 16-bit 44.1 kHz\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t> pcm;if(!loadWav15(p,pcm)){MessageBoxW(win,L"WAV PCM 16-bit 44.1 kHz requis pour cette Alpha.",L"Boomify",MB_OK);return;}samples15[laneSelected]={p,selectedBar,std::move(pcm)};InvalidateRect(win,nullptr,FALSE);}
void addBoom15(){if((int)lanes.size()>=V6_MAX_TRACKS)return;lanes.push_back({L"BoomBox Kick",LaneType::Drums,false,false,82});laneSelected=(int)lanes.size()-1;kicks15[laneSelected].enabled=true;colors15[laneSelected]=RGB(225,88,62);layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void adj15(int&v,int d){v=std::clamp(v+d,0,100);InvalidateRect(win,nullptr,FALSE);}
void draw15(HDC d){
// Small per-track controls stay inside the existing left header, without painting over its name/M/S/volume UI.
for(int i=0;i<V6_MAX_TRACKS;i++){colorHit15[i]={0,0,0,0};nameHit15[i]={0,0,0,0};}
for(int i=0;i<(int)lanes.size();i++){if(!colors15[i])colors15[i]=defaultColor15(i);RECT h=laneHeadR[i];if(h.bottom<=h.top)continue;int cy=(int)(h.top+h.bottom)/2;colorHit15[i]={h.right-27,cy-8,h.right-11,cy+8};nameHit15[i]={h.left+8,h.top+3,h.right-34,h.top+27};fill(d,colorHit15[i],colors15[i]);line(d,colorHit15[i].left,colorHit15[i].top,colorHit15[i].right,colorHit15[i].top,RGB(230,230,235));}
int ix=(int)inspector10.left+18, iw=std::max(110,(int)inspector10.right-ix-18);import15={ix,150,ix+iw,180};boom15={ix,186,ix+iw,216};master15={ix,222,ix+iw,252};
if(inspector10.right>inspector10.left){button(d,import15,L"IMPORTER SAMPLE WAV");button(d,boom15,L"+ PISTE BOOMBOX");fill(d,master15,masterOn15?RGB(62,128,93):RGB(42,44,49));std::wstring mt=L"MASTER FX  |  VOLUME "+std::to_wstring(master)+L"%";label(d,mt.c_str(),master15.left+10,master15.top+10,7,RGB(235,237,241),FW_BOLD);label(d,L"Nom : double-clic sur le nom",ix,264,7,RGB(140,145,156));label(d,L"Couleur : carre a droite de la piste",ix,280,7,RGB(140,145,156));}
if(laneSelected>=0&&laneSelected<(int)lanes.size()&&kicks15[laneSelected].enabled&&inspector10.right>inspector10.left){auto&k=kicks15[laneSelected];int y=312;label(d,L"BOOMBOX / KICK DESIGNER",ix,y,8,RGB(235,126,99),FW_BOLD);auto row=[&](const wchar_t*n,int v,int yy,RECT&mn,RECT&pl){label(d,n,ix,yy+7,7,RGB(205,208,215),FW_BOLD);std::wstring z=std::to_wstring(v);label(d,z.c_str(),ix+86,yy+7,7,RGB(240,240,243),FW_BOLD);mn={ix+122,yy,ix+150,yy+26};pl={ix+156,yy,ix+184,yy+26};fill(d,mn,RGB(43,46,54));fill(d,pl,RGB(43,46,54));label(d,L"-",mn.left+10,mn.top+6,8,RGB(235,235,240),FW_BOLD);label(d,L"+",pl.left+9,pl.top+6,8,RGB(235,235,240),FW_BOLD);};row(L"PITCH",k.pitch,y+24,kpMinus15,kpPlus15);row(L"DECAY",k.decay,y+56,kdMinus15,kdPlus15);row(L"PUNCH",k.punch,y+88,kuMinus15,kuPlus15);row(L"DRIVE",k.drive,y+120,krMinus15,krPlus15);label(d,L"Kick plus propre : drive reduit par defaut",ix,y+158,7,RGB(145,150,160));}}
LRESULT CALLBACK proc_v15(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);overlay12(mem);drawV13Chrome(mem);drawV14(mem);draw15(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDBLCLK){for(int i=0;i<(int)lanes.size();i++)if(inside(nameHit15[i],p)){laneSelected=i;renameLane15(i);return 0;}}if(m==WM_LBUTTONDOWN){for(int i=0;i<(int)lanes.size();i++)if(inside(colorHit15[i],p)){laneSelected=i;cycleColorLane15(i);return 0;}if(inside(playR,p)){play15();return 0;}if(inside(wavR,p)){export15();return 0;}if(inside(import15,p)){importSample15();return 0;}if(inside(boom15,p)){addBoom15();return 0;}if(inside(master15,p)){masterOn15=!masterOn15;InvalidateRect(h,nullptr,FALSE);return 0;}if(laneSelected>=0&&laneSelected<(int)lanes.size()&&kicks15[laneSelected].enabled){auto&k=kicks15[laneSelected];if(inside(kpMinus15,p)){adj15(k.pitch,-2);return 0;}if(inside(kpPlus15,p)){adj15(k.pitch,2);return 0;}if(inside(kdMinus15,p)){adj15(k.decay,-5);return 0;}if(inside(kdPlus15,p)){adj15(k.decay,5);return 0;}if(inside(kuMinus15,p)){adj15(k.punch,-5);return 0;}if(inside(kuPlus15,p)){adj15(k.punch,5);return 0;}if(inside(krMinus15,p)){adj15(k.drive,-5);return 0;}if(inside(krPlus15,p)){adj15(k.drive,5);return 0;}}}return proc_v14_base15(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int){for(int i=0;i<V6_MAX_TRACKS;i++)colors15[i]=defaultColor15(i);editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;master=100;WNDCLASSW wc{};wc.lpfnWndProc=proc_v15;wc.hInstance=hi;wc.lpszClassName=L"BoomifyAlpha6";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);wc.style=CS_DBLCLKS;RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Studio - Alpha 6",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1440,900,nullptr,nullptr,hi,nullptr);if(!win)return 1;ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);layout11(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wParam;}
