#include <windows.h>
#include <windowsx.h>
#include <mmdeviceapi.h>
#include <audioclient.h>
#include <ksmedia.h>
#include <commdlg.h>
#include <array>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <thread>
#include <vector>
#include <algorithm>
#include <fstream>
#include <string>
#pragma comment(lib,"ole32.lib")
#pragma comment(lib,"uuid.lib")
#pragma comment(lib,"comdlg32.lib")
namespace{
constexpr int STEPS=16,D=4,NOTES=12;constexpr double PI=3.14159265358979323846;
std::array<std::array<std::atomic_bool,STEPS>,D>drums{};std::array<std::array<std::atomic_bool,STEPS>,NOTES>bass{},melody{};std::atomic_bool playing{false};std::atomic_int bpm{150},cur{-1},master{50};std::thread ath;HWND win{};int page=0;RECT playR{},minusR{},plusR{},volR{},newR{},openR{},saveR{},exportR{},tabs[4]{},dp[D][STEPS]{},np[NOTES][STEPS]{};
COLORREF bg=RGB(14,16,19),bar=RGB(21,24,28),panel=RGB(27,31,36),cell=RGB(38,43,49),line=RGB(52,58,65),txt=RGB(240,242,245),mut=RGB(135,143,153),lime=RGB(178,255,74),blue=RGB(92,174,255);
void fill(HDC d,RECT r,COLORREF c){HBRUSH b=CreateSolidBrush(c);FillRect(d,&r,b);DeleteObject(b);}void label(HDC d,const wchar_t*s,int x,int y,int z,COLORREF c,int wt=FW_NORMAL){HFONT f=CreateFontW(-z,0,0,0,wt,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI");auto o=SelectObject(d,f);SetBkMode(d,TRANSPARENT);SetTextColor(d,c);TextOutW(d,x,y,s,(int)wcslen(s));SelectObject(d,o);DeleteObject(f);}void button(HDC d,RECT r,const wchar_t*s,bool on=false){fill(d,r,on?lime:panel);label(d,s,r.left+12,r.top+8,13,on?bg:txt,FW_BOLD);}double hz(int n){return 440.0*pow(2.0,(n-69)/12.0);}double noise(uint32_t x){x^=x<<13;x^=x>>17;x^=x<<5;return((x&65535)/32767.5)-1;}
struct Voice{int k,n,a=0;double ph=0;};double smp(Voice&v,double sr){double t=v.a/sr,o=0;if(v.k<4){if(v.k==0){double f=48+110*exp(-t*35);v.ph+=2*PI*f/sr;o=sin(v.ph)*exp(-t*16)+.12*sin(2*PI*900*t)*exp(-t*90);}else if(v.k==1){o=.55*noise(v.a*747796405u+17)*exp(-t*18);v.ph+=2*PI*180/sr;o+=.28*sin(v.ph)*exp(-t*22);}else if(v.k==2)o=.55*noise(v.a*2891336453u+91)*exp(-t*30);else o=.32*noise(v.a*277803737u+41)*exp(-t*55);}else{v.ph+=hz(v.n)/sr;if(v.ph>=1)v.ph-=1;double saw=2*v.ph-1,sine=sin(2*PI*v.ph),a=std::min(1.0,t/.008),dec=exp(-t*(v.k==4?3.2:2.0));o=(v.k==4?(saw*.65+sine*.35):(sine*.72+saw*.28))*a*dec;}v.a++;return o;}bool alive(const Voice&v,double sr){double q[]={.30,.22,.16,.10,.42,.62};return v.a<q[v.k]*sr;}
bool floatFormat(WAVEFORMATEX*f){if(f->wFormatTag==WAVE_FORMAT_IEEE_FLOAT&&f->wBitsPerSample==32)return true;if(f->wFormatTag==WAVE_FORMAT_EXTENSIBLE&&f->cbSize>=22&&f->wBitsPerSample==32){auto*x=reinterpret_cast<WAVEFORMATEXTENSIBLE*>(f);return IsEqualGUID(x->SubFormat,KSDATAFORMAT_SUBTYPE_IEEE_FLOAT);}return false;}
void audio(){CoInitializeEx(nullptr,COINIT_MULTITHREADED);IMMDeviceEnumerator*en=nullptr;IMMDevice*dev=nullptr;IAudioClient*ac=nullptr;IAudioRenderClient*rc=nullptr;WAVEFORMATEX*f=nullptr;HANDLE ev=nullptr;HRESULT hr=CoCreateInstance(__uuidof(MMDeviceEnumerator),nullptr,CLSCTX_ALL,__uuidof(IMMDeviceEnumerator),(void**)&en);if(SUCCEEDED(hr))hr=en->GetDefaultAudioEndpoint(eRender,eConsole,&dev);if(SUCCEEDED(hr))hr=dev->Activate(__uuidof(IAudioClient),CLSCTX_ALL,nullptr,(void**)&ac);if(SUCCEEDED(hr))hr=ac->GetMixFormat(&f);if(SUCCEEDED(hr))hr=ac->Initialize(AUDCLNT_SHAREMODE_SHARED,AUDCLNT_STREAMFLAGS_EVENTCALLBACK,0,0,f,nullptr);if(SUCCEEDED(hr)){ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!ev)hr=E_FAIL;}if(SUCCEEDED(hr))hr=ac->SetEventHandle(ev);if(SUCCEEDED(hr))hr=ac->GetService(__uuidof(IAudioRenderClient),(void**)&rc);if(FAILED(hr)){playing=false;PostMessageW(win,WM_APP+2,(WPARAM)hr,0);if(rc)rc->Release();if(ac)ac->Release();if(f)CoTaskMemFree(f);if(dev)dev->Release();if(en)en->Release();if(ev)CloseHandle(ev);CoUninitialize();return;}UINT32 frames=0;ac->GetBufferSize(&frames);BYTE*p=nullptr;if(SUCCEEDED(rc->GetBuffer(frames,&p)))rc->ReleaseBuffer(frames,AUDCLNT_BUFFERFLAGS_SILENT);hr=ac->Start();if(FAILED(hr)){playing=false;PostMessageW(win,WM_APP+2,(WPARAM)hr,0);}double sr=f->nSamplesPerSec,left=0,ramp=0;int step=0,last=-1;std::vector<Voice>vs;bool isFloat=floatFormat(f);while(playing&&SUCCEEDED(hr)){if(WaitForSingleObject(ev,250)!=WAIT_OBJECT_0)continue;UINT32 pad=0;if(FAILED(ac->GetCurrentPadding(&pad)))break;UINT32 n=frames-pad;if(!n)continue;if(FAILED(rc->GetBuffer(n,&p)))continue;for(UINT32 i=0;i<n;i++){if(left<=0){cur=step;if(step!=last){last=step;PostMessageW(win,WM_APP+1,0,0);}for(int t=0;t<D;t++)if(drums[t][step])vs.push_back({t,0});for(int r=0;r<NOTES;r++){if(bass[r][step])vs.push_back({4,47-r});if(melody[r][step])vs.push_back({5,71-r});}step=(step+1)%STEPS;left+=sr*60.0/bpm.load()/4.0;}double x=0;for(auto&v:vs)x+=smp(v,sr);vs.erase(std::remove_if(vs.begin(),vs.end(),[&](const Voice&v){return!alive(v,sr);}),vs.end());ramp=std::min(1.0,ramp+1.0/(sr*.012));x=std::clamp(x*.24*(master.load()/100.0)*ramp,-1.0,1.0);if(isFloat){float*out=reinterpret_cast<float*>(p);for(int c=0;c<f->nChannels;c++)out[i*f->nChannels+c]=(float)x;}else if(f->wBitsPerSample==16){int16_t*out=reinterpret_cast<int16_t*>(p),q=(int16_t)(x*32767);for(int c=0;c<f->nChannels;c++)out[i*f->nChannels+c]=q;}else if(f->wBitsPerSample==32){int32_t*out=reinterpret_cast<int32_t*>(p),q=(int32_t)(x*2147483647.0);for(int c=0;c<f->nChannels;c++)out[i*f->nChannels+c]=q;}else ZeroMemory(p+i*f->nBlockAlign,f->nBlockAlign);left--;}rc->ReleaseBuffer(n,0);}if(ac)ac->Stop();cur=-1;PostMessageW(win,WM_APP+1,0,0);rc->Release();ac->Release();CoTaskMemFree(f);dev->Release();en->Release();CloseHandle(ev);CoUninitialize();}
void toggle(){if(playing){playing=false;if(ath.joinable())ath.join();}else{playing=true;ath=std::thread(audio);}InvalidateRect(win,nullptr,FALSE);}std::wstring dialog(bool save,const wchar_t*filter,const wchar_t*ext){wchar_t p[MAX_PATH]=L"";OPENFILENAMEW o{};o.lStructSize=sizeof(o);o.hwndOwner=win;o.lpstrFile=p;o.nMaxFile=MAX_PATH;o.lpstrFilter=filter;o.lpstrDefExt=ext;o.Flags=OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);return(save?GetSaveFileNameW(&o):GetOpenFileNameW(&o))?p:L"";}
void fresh(){if(playing)toggle();for(auto&t:drums)for(auto&s:t)s=false;for(auto&t:bass)for(auto&s:t)s=false;for(auto&t:melody)for(auto&s:t)s=false;bpm=150;master=50;page=0;InvalidateRect(win,nullptr,FALSE);}void saveProject(){auto p=dialog(true,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return;std::ofstream o(p);o<<"BOOMIFY3 "<<bpm.load()<<' '<<master.load()<<'\n';for(auto&t:drums){for(auto&s:t)o<<(s?1:0);o<<'\n';}for(auto&t:bass){for(auto&s:t)o<<(s?1:0);o<<'\n';}for(auto&t:melody){for(auto&s:t)o<<(s?1:0);o<<'\n';}}void openProject(){auto p=dialog(false,L"Boomify Project\0*.boom\0",L"boom");if(p.empty())return;std::ifstream i(p);std::string magic,row;int b,m;if(!(i>>magic>>b>>m)||magic!="BOOMIFY3")return;bpm=std::clamp(b,60,220);master=std::clamp(m,0,100);for(auto&t:drums){i>>row;for(int s=0;s<STEPS;s++)t[s]=s<(int)row.size()&&row[s]=='1';}for(auto&t:bass){i>>row;for(int s=0;s<STEPS;s++)t[s]=s<(int)row.size()&&row[s]=='1';}for(auto&t:melody){i>>row;for(int s=0;s<STEPS;s++)t[s]=s<(int)row.size()&&row[s]=='1';}InvalidateRect(win,nullptr,FALSE);}
void wav(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;constexpr int sr=44100;int sn=(int)(sr*60.0/bpm.load()/4.0),total=sn*STEPS;std::vector<int16_t>a(total*2);std::vector<Voice>v;for(int i=0;i<total;i++){if(i%sn==0){int s=i/sn;for(int t=0;t<D;t++)if(drums[t][s])v.push_back({t,0});for(int r=0;r<NOTES;r++){if(bass[r][s])v.push_back({4,47-r});if(melody[r][s])v.push_back({5,71-r});}}double x=0;for(auto&q:v)x+=smp(q,sr);v.erase(std::remove_if(v.begin(),v.end(),[&](const Voice&q){return!alive(q,sr);}),v.end());int16_t z=(int16_t)(std::clamp(x*.24*(master.load()/100.0),-1.0,1.0)*32767);a[i*2]=a[i*2+1]=z;}std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)a.size()*2,rs=36+ds,fs=16,rate=sr,br=sr*4;uint16_t pcm=1,ch=2,align=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&align,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
void layout(HWND h){RECT c;GetClientRect(h,&c);int w=c.right,H=c.bottom;newR={170,23,235,58};openR={240,23,305,58};saveR={310,23,395,58};exportR={400,23,485,58};playR={w/2-50,20,w/2+35,60};minusR={w/2+105,20,w/2+140,60};plusR={w/2+215,20,w/2+250,60};volR={w-300,34,w-170,46};int left=150,right=w-35,top=175,bottom=H-135,gap=4,dw=(right-left-gap*15)/16,dh=(bottom-top-18)/4;for(int r=0;r<D;r++)for(int s=0;s<STEPS;s++)dp[r][s]={left+s*(dw+gap),top+r*dh,left+s*(dw+gap)+dw,top+(r+1)*dh-8};int nw=(right-left)/STEPS,nh=(bottom-top)/NOTES;for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)np[r][s]={left+s*nw,top+r*nh,left+(s+1)*nw-1,top+(r+1)*nh-1};int y=H-105;tabs[0]={210,y,285,y+36};tabs[1]={292,y,352,y+36};tabs[2]={359,y,450,y+36};tabs[3]={457,y,575,y+36};}
void paint(HDC d,RECT c){int w=c.right,H=c.bottom;fill(d,c,bg);fill(d,{0,0,w,82},bar);label(d,L"Boomify",22,16,29,txt,FW_BOLD);button(d,newR,L"NEW");button(d,openR,L"OPEN");button(d,saveR,L"SAVE");button(d,exportR,L"WAV");button(d,playR,playing?L"STOP":L"PLAY",!playing);label(d,L"BPM",w/2+55,33,11,mut,FW_BOLD);button(d,minusR,L"-");wchar_t z[20];swprintf_s(z,L"%d",bpm.load());label(d,z,w/2+150,27,20,txt,FW_BOLD);button(d,plusR,L"+");label(d,L"MASTER",w-365,31,11,mut,FW_BOLD);fill(d,volR,line);fill(d,{volR.left,volR.top,volR.left+(volR.right-volR.left)*master.load()/100,volR.bottom},lime);swprintf_s(z,L"%d%%",master.load());label(d,z,w-155,28,14,txt,FW_BOLD);const wchar_t*titles[]={L"DRUMS",L"BASS",L"MELODIE",L"ARRANGEMENT"};label(d,titles[page],35,105,25,txt,FW_BOLD);if(page==0){label(d,L"Clique les cases pour construire le rythme",35,138,13,mut);const wchar_t*n[]={L"KICK",L"SNARE",L"CLAP",L"HI-HAT"};for(int r=0;r<D;r++){label(d,n[r],35,(dp[r][0].top+dp[r][0].bottom)/2-8,13,txt,FW_BOLD);for(int s=0;s<STEPS;s++){COLORREF cc=drums[r][s]?lime:cell;if(cur==s&&!drums[r][s])cc=RGB(67,74,82);fill(d,dp[r][s],cc);}}}else if(page==1||page==2){label(d,page==1?L"Synth Bass natif - clique une note dans la grille":L"Synth Lead natif - clique une note dans la grille",35,138,13,mut);const wchar_t*names[]={L"B",L"A#",L"A",L"G#",L"G",L"F#",L"F",L"E",L"D#",L"D",L"C#",L"C"};auto&g=page==1?bass:melody;for(int r=0;r<NOTES;r++){label(d,names[r],105,np[r][0].top+3,11,mut,FW_BOLD);for(int s=0;s<STEPS;s++){COLORREF cc=g[r][s]?(page==1?lime:blue):((r==1||r==3||r==5||r==8||r==10)?RGB(31,35,40):cell);if(cur==s&&!g[r][s])cc=RGB(58,64,71);fill(d,np[r][s],cc);}}}else{label(d,L"Arrangement complet arrive au prochain jalon",35,138,13,mut);fill(d,{35,175,w-35,H-135},bar);label(d,L"Drums + Bass + Melodie jouent ensemble sur le meme transport.",70,210,16,lime,FW_BOLD);}fill(d,{25,H-115,w-25,H-20},bar);for(int i=0;i<4;i++)button(d,tabs[i],titles[i],page==i);label(d,L"Espace = Play/Stop    Tout joue ensemble",35,H-55,12,mut);}
LRESULT CALLBACK proc(HWND h,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_ERASEBKGND:return 1;case WM_APP+1:InvalidateRect(h,nullptr,FALSE);return 0;case WM_APP+2:{wchar_t e[128];swprintf_s(e,L"La sortie audio Windows n'a pas pu demarrer. Code: 0x%08X",(unsigned)wp);MessageBoxW(h,e,L"Boomify audio",MB_OK|MB_ICONERROR);return 0;}case WM_SIZE:layout(h);return 0;case WM_KEYDOWN:if(wp==VK_SPACE){toggle();return 0;}break;case WM_LBUTTONDOWN:{POINT q{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(PtInRect(&newR,q)){fresh();return 0;}if(PtInRect(&openR,q)){openProject();return 0;}if(PtInRect(&saveR,q)){saveProject();return 0;}if(PtInRect(&exportR,q)){wav();return 0;}if(PtInRect(&playR,q)){toggle();return 0;}if(PtInRect(&minusR,q)){bpm=std::max(60,bpm.load()-1);InvalidateRect(h,nullptr,FALSE);return 0;}if(PtInRect(&plusR,q)){bpm=std::min(220,bpm.load()+1);InvalidateRect(h,nullptr,FALSE);return 0;}if(PtInRect(&volR,q)){int raw=(int)((q.x-volR.left)*100L/(volR.right-volR.left));master=std::max(0,std::min(100,raw));InvalidateRect(h,nullptr,FALSE);return 0;}for(int i=0;i<4;i++)if(PtInRect(&tabs[i],q)){page=i;InvalidateRect(h,nullptr,FALSE);return 0;}if(page==0)for(int r=0;r<D;r++)for(int s=0;s<STEPS;s++)if(PtInRect(&dp[r][s],q)){drums[r][s]=!drums[r][s].load();InvalidateRect(h,nullptr,FALSE);return 0;}if(page==1||page==2){auto&g=page==1?bass:melody;for(int r=0;r<NOTES;r++)for(int s=0;s<STEPS;s++)if(PtInRect(&np[r][s],q)){g[r][s]=!g[r][s].load();InvalidateRect(h,nullptr,FALSE);return 0;}}break;}case WM_PAINT:{PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,c.right,c.bottom);auto old=SelectObject(mem,bm);paint(mem,c);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}case WM_DESTROY:playing=false;if(ath.joinable())ath.join();PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,wp,lp);}}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){for(int s:{0,4,8,12})drums[0][s]=true;drums[1][4]=drums[1][12]=true;for(int s:{2,6,10,14})drums[3][s]=true;WNDCLASSW wc{};wc.lpfnWndProc=proc;wc.hInstance=hi;wc.lpszClassName=L"BoomifyAlpha";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 1",WS_OVERLAPPEDWINDOW,0,0,1450,900,nullptr,nullptr,hi,nullptr);ShowWindow(win,SW_MAXIMIZE);layout(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
