// Boomify Alpha 5 - instrument families + native FX
#define wWinMain wWinMain_v8_legacy
#include "main_v8.cpp"
#undef wWinMain

namespace {
enum class Family9{Bass,Synth,Keys,Pluck,Pad};
enum class Sound9{SubBass,ReeseBass,AcidBass,SawLead,SquareLead,SuperSaw,Piano,EPiano,Organ,DigitalPluck,Kalimba,Bell,WarmPad,AirPad,ChoirPad};
std::array<Sound9,V6_MAX_TRACKS> sound9={Sound9::SubBass,Sound9::SubBass,Sound9::SawLead};
std::array<bool,V6_MAX_TRACKS> dist9{};
std::array<bool,V6_MAX_TRACKS> delay9{};
std::array<int,V6_MAX_TRACKS> drive9{};
std::array<int,V6_MAX_TRACKS> delayMix9{};
RECT pluginR{},familyR{},soundR{};
Family9 familyOf(Sound9 s){int v=(int)s;if(v<=2)return Family9::Bass;if(v<=5)return Family9::Synth;if(v<=8)return Family9::Keys;if(v<=11)return Family9::Pluck;return Family9::Pad;}
const wchar_t* familyName9(Family9 f){switch(f){case Family9::Bass:return L"BASSES";case Family9::Synth:return L"SYNTHES";case Family9::Keys:return L"CLAVIERS";case Family9::Pluck:return L"PLUCKS";default:return L"PADS";}}
const wchar_t* soundName9(Sound9 s){switch(s){case Sound9::SubBass:return L"Sub Bass";case Sound9::ReeseBass:return L"Reese Bass";case Sound9::AcidBass:return L"Acid Bass";case Sound9::SawLead:return L"Saw Lead";case Sound9::SquareLead:return L"Square Lead";case Sound9::SuperSaw:return L"SuperSaw";case Sound9::Piano:return L"Piano";case Sound9::EPiano:return L"E-Piano";case Sound9::Organ:return L"Organ";case Sound9::DigitalPluck:return L"Digital Pluck";case Sound9::Kalimba:return L"Kalimba";case Sound9::Bell:return L"Bell";case Sound9::WarmPad:return L"Warm Pad";case Sound9::AirPad:return L"Air Pad";default:return L"Choir Pad";}}
struct Voice9{Sound9 sound;int lane=1,note=60,age=0;double ph=0;};
double wave9(double p,int mode){double si=sin(6.283185307179586*p),saw=2*p-1,sq=p<.5?1.0:-1.0,tri=1.0-4.0*std::abs(p-.5);switch(mode){case 1:return saw;case 2:return sq;case 3:return tri;default:return si;}}
double sample9(Voice9&v){double t=v.age/(double)SR,f=hz(v.note);v.ph+=f/SR;if(v.ph>=1)v.ph-=1;double p=v.ph,o=0;switch(v.sound){case Sound9::SubBass:o=wave9(p,0)*exp(-t*1.5);break;case Sound9::ReeseBass:o=(wave9(p,1)+wave9(fmod(p*1.006,1.0),1))*.45*exp(-t*1.3);break;case Sound9::AcidBass:o=(wave9(p,1)*.7+wave9(p,2)*.2)*exp(-t*3.0)*(0.7+0.3*sin(t*18));break;case Sound9::SawLead:o=(wave9(p,1)*.7+wave9(p,0)*.3)*exp(-t*1.1);break;case Sound9::SquareLead:o=(wave9(p,2)*.6+wave9(p,0)*.4)*exp(-t*1.0);break;case Sound9::SuperSaw:o=(wave9(p,1)+wave9(fmod(p*1.008,1.0),1)+wave9(fmod(p*.993,1.0),1))/3.0*exp(-t*.85);break;case Sound9::Piano:o=(wave9(p,0)+.45*wave9(fmod(p*2,1.0),0)+.2*wave9(fmod(p*3,1.0),0))*exp(-t*3.2);break;case Sound9::EPiano:o=(wave9(p,0)+.35*wave9(fmod(p*2,1.0),3))*exp(-t*2.0);break;case Sound9::Organ:o=(wave9(p,0)+.5*wave9(fmod(p*2,1.0),0)+.25*wave9(fmod(p*3,1.0),0))*.55*exp(-t*.35);break;case Sound9::DigitalPluck:o=(wave9(p,1)*.35+wave9(p,0)*.65)*exp(-t*8.5);break;case Sound9::Kalimba:o=(wave9(p,0)+.4*wave9(fmod(p*3,1.0),0))*exp(-t*9.5);break;case Sound9::Bell:o=(wave9(p,0)+.5*wave9(fmod(p*2.7,1.0),0))*exp(-t*5.0);break;case Sound9::WarmPad:o=(wave9(p,0)*.7+wave9(p,1)*.15)*std::min(1.0,t*5)*exp(-t*.45);break;case Sound9::AirPad:o=(wave9(p,0)*.55+wave9(fmod(p*2.01,1.0),0)*.25)*std::min(1.0,t*3)*exp(-t*.35);break;case Sound9::ChoirPad:o=(wave9(p,0)+.35*wave9(fmod(p*1.5,1.0),0))*std::min(1.0,t*4)*exp(-t*.4);break;}v.age++;return o;}
bool alive9(const Voice9&v){Family9 f=familyOf(v.sound);double sec=f==Family9::Pad?2.4:f==Family9::Pluck?0.8:f==Family9::Keys?1.6:1.2;return v.age<sec*SR;}
void renderRangeV9(std::vector<int16_t>&out,int start){start=std::clamp(start,0,activeBars-1);int step=std::max(1,(int)(SR*60.0/bpm/4.0));size_t frames=(size_t)step*STEPS*(activeBars-start);out.assign(frames*2,0);std::vector<Voice> dv;std::vector<Voice9> nv;std::array<double,V6_MAX_TRACKS> delayMem{};bool anySolo=false;for(auto&l:lanes)if(l.solo)anySolo=true;for(size_t f=0;f<frames;f++){if(f%step==0){int g=(int)(f/step),b=start+g/STEPS,s=g%STEPS;if(!lanes.empty()&&!lanes[0].mute&&(!anySolo||lanes[0].solo))for(int r=0;r<DR;r++)if(drums[b][r][s])dv.push_back({r,0});for(int lane=1;lane<(int)lanes.size();lane++){if(lanes[lane].type==LaneType::Audio||lanes[lane].mute||(anySolo&&!lanes[lane].solo))continue;auto&clip=noteForLane(lane,b);int base=familyOf(sound9[lane])==Family9::Bass?47:71;for(int r=0;r<NOTES;r++)if(clip[r][s])nv.push_back({sound9[lane],lane,base-r});}}double x=0,dg=lanes.empty()?1.0:lanes[0].volume/100.0;for(auto&q:dv)x+=sample(q)*dg;std::array<double,V6_MAX_TRACKS> laneMix{};for(auto&q:nv)if(q.lane>=0&&q.lane<(int)lanes.size())laneMix[q.lane]+=sample9(q);for(int lane=1;lane<(int)lanes.size();lane++){double y=laneMix[lane]*(lanes[lane].volume/100.0);if(dist9[lane]){double d=1.0+drive9[lane]/12.0;y=tanh(y*d);}if(delay9[lane]){double wet=delayMix9[lane]/100.0;double z=y+delayMem[lane]*wet;delayMem[lane]=delayMem[lane]*.9995+y*.0005;y=z;}x+=y;}dv.erase(std::remove_if(dv.begin(),dv.end(),[](const Voice&q){return!alive(q);}),dv.end());nv.erase(std::remove_if(nv.begin(),nv.end(),[](const Voice9&q){return!alive9(q);}),nv.end());int16_t z=(int16_t)(std::clamp(x*.20*(master/100.0),-1.0,1.0)*32767);out[f*2]=out[f*2+1]=z;}}
void playV9(){if(playing){stopAudio();return;}playStartBar=cursorBar;renderRangeV9(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr));waveOutWrite(wave,&waveHdr,sizeof(waveHdr));playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void exportV9(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderRangeV9(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,align=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&align,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
void chooseInstrument9(HWND h,int lane,POINT p){if(lane<=0||lane>=(int)lanes.size()||lanes[lane].type!=LaneType::Instrument)return;HMENU root=CreatePopupMenu(),bass=CreatePopupMenu(),synth=CreatePopupMenu(),keys=CreatePopupMenu(),pluck=CreatePopupMenu(),pad=CreatePopupMenu();for(int k=0;k<3;k++)AppendMenuW(bass,MF_STRING,65001+k,soundName9((Sound9)k));for(int k=3;k<6;k++)AppendMenuW(synth,MF_STRING,65001+k,soundName9((Sound9)k));for(int k=6;k<9;k++)AppendMenuW(keys,MF_STRING,65001+k,soundName9((Sound9)k));for(int k=9;k<12;k++)AppendMenuW(pluck,MF_STRING,65001+k,soundName9((Sound9)k));for(int k=12;k<15;k++)AppendMenuW(pad,MF_STRING,65001+k,soundName9((Sound9)k));AppendMenuW(root,MF_POPUP,(UINT_PTR)bass,L"Basses");AppendMenuW(root,MF_POPUP,(UINT_PTR)synth,L"Synthes / Leads");AppendMenuW(root,MF_POPUP,(UINT_PTR)keys,L"Claviers");AppendMenuW(root,MF_POPUP,(UINT_PTR)pluck,L"Plucks / Bells");AppendMenuW(root,MF_POPUP,(UINT_PTR)pad,L"Pads");ClientToScreen(h,&p);int cmd=TrackPopupMenu(root,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,h,nullptr);DestroyMenu(root);if(cmd>=65001&&cmd<65016){sound9[lane]=(Sound9)(cmd-65001);InvalidateRect(h,nullptr,FALSE);}}
void choosePlugin9(HWND h,int lane,POINT p){if(lane<=0||lane>=(int)lanes.size())return;HMENU m=CreatePopupMenu();AppendMenuW(m,MF_STRING|(dist9[lane]?MF_CHECKED:0),65101,L"Distortion native");AppendMenuW(m,MF_STRING|(delay9[lane]?MF_CHECKED:0),65102,L"Delay native");AppendMenuW(m,MF_SEPARATOR,0,nullptr);AppendMenuW(m,MF_STRING,65103,L"Drive +");AppendMenuW(m,MF_STRING,65104,L"Drive -");AppendMenuW(m,MF_STRING,65105,L"Delay Mix +");AppendMenuW(m,MF_STRING,65106,L"Delay Mix -");ClientToScreen(h,&p);int cmd=TrackPopupMenu(m,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,h,nullptr);DestroyMenu(m);if(cmd==65101)dist9[lane]=!dist9[lane];if(cmd==65102)delay9[lane]=!delay9[lane];if(cmd==65103)drive9[lane]=std::min(100,drive9[lane]+10);if(cmd==65104)drive9[lane]=std::max(0,drive9[lane]-10);if(cmd==65105)delayMix9[lane]=std::min(100,delayMix9[lane]+10);if(cmd==65106)delayMix9[lane]=std::max(0,delayMix9[lane]-10);InvalidateRect(h,nullptr,FALSE);}
void drawAlpha5(HDC d){for(int i=1;i<(int)lanes.size();i++)if(lanes[i].type==LaneType::Instrument){RECT r=laneHeadR[i];label(d,familyName9(familyOf(sound9[i])),74,r.top+22,8,RGB(142,148,158),FW_BOLD);label(d,soundName9(sound9[i]),14,r.top+38,8,RGB(211,104,76),FW_BOLD);std::wstring fx=L"FX ";if(dist9[i])fx+=L"DIST ";if(delay9[i])fx+=L"DELAY ";if(!dist9[i]&&!delay9[i])fx+=L"OFF";label(d,fx.c_str(),74,r.top+38,8,RGB(184,130,211),FW_BOLD);}}
LRESULT CALLBACK proc_v9(HWND h,UINT m,WPARAM wp,LPARAM lp){if(m==WM_RBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};for(int i=1;i<(int)lanes.size();i++)if(inside(laneHeadR[i],p)){if(p.x<105){chooseInstrument9(h,i,p);return 0;}choosePlugin9(h,i,p);return 0;}}if(m==WM_LBUTTONDOWN){POINT p{GET_X_LPARAM(lp),GET_Y_LPARAM(lp)};if(inside(playR,p)){playV9();return 0;}if(inside(wavR,p)){exportV9();return 0;}}if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1L,c.right),std::max(1L,c.bottom));auto old=SelectObject(mem,bm);drawV6(mem,c);drawAlpha5(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}return proc_v8(h,m,wp,lp);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,PWSTR,int){WNDCLASSW wc{};wc.lpfnWndProc=proc_v9;wc.hInstance=hi;wc.lpszClassName=L"BoomifyV9";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Alpha 5 - Instruments & Plugins",WS_OVERLAPPEDWINDOW,0,0,1500,920,nullptr,nullptr,hi,nullptr);if(!win)return 1;v6Fresh();sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;for(int i=0;i<V6_MAX_TRACKS;i++){drive9[i]=35;delayMix9[i]=25;}layoutV6(win);ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
