// Boomify V17 navigation/audio layer. Keeps V17 as the single application entry point.
#include <windows.h>
LRESULT CALLBACK proc_v17_nav(HWND,UINT,WPARAM,LPARAM);
static ATOM RegisterClassW_nav(const WNDCLASSW* src){WNDCLASSW wc=*src;wc.lpfnWndProc=proc_v17_nav;return ::RegisterClassW(&wc);}
#define RegisterClassW RegisterClassW_nav
#include "main_v17.cpp"
#undef RegisterClassW

namespace {
RECT zoomOutNavR{},zoomInNavR{},fitNavR{},loopNavR{},setLoopNavR{};
bool loopOnNav=false;int loopStartNav=0,loopEndNav=3;

void relayoutNav(){layout11(win);sync16(win);InvalidateRect(win,nullptr,FALSE);}
void scrollTimelineNav(int dir){if(!dir)return;int step=std::max(1,visibleBars/4);if(dir>0){int wanted=scrollBar+step,needed=std::min(MAX_BARS,wanted+visibleBars);if(needed>activeBars)activeBars=needed;scrollBar=std::min(wanted,std::max(0,MAX_BARS-visibleBars));}else scrollBar=std::max(0,scrollBar-step);cursorBar=std::clamp(cursorBar,scrollBar,std::min(MAX_BARS-1,scrollBar+visibleBars-1));relayoutNav();}
void zoomNav(int dir){int old=visibleBars;if(dir>0)visibleBars=std::max(4,visibleBars/2);else visibleBars=std::min(MAX_BARS,std::max(visibleBars+1,visibleBars*2));if(dir<0&&visibleBars>activeBars)visibleBars=std::min(MAX_BARS,std::max(activeBars,4));if(old==visibleBars)return;scrollBar=std::clamp(scrollBar,0,std::max(0,MAX_BARS-visibleBars));if(cursorBar<scrollBar)scrollBar=cursorBar;if(cursorBar>=scrollBar+visibleBars)scrollBar=std::max(0,cursorBar-visibleBars+1);relayoutNav();}
void fitTimelineNav(){visibleBars=std::clamp(activeBars,4,MAX_BARS);scrollBar=0;relayoutNav();}
void setLoopNavFromSelection(){int lo=MAX_BARS,hi=-1;for(auto&q:multiSelection){lo=std::min(lo,q.bar);hi=std::max(hi,q.bar);}if(hi<0){lo=std::clamp(selectedBar,0,std::max(0,activeBars-1));hi=std::min(activeBars-1,lo+3);}loopStartNav=std::clamp(lo,0,std::max(0,activeBars-1));loopEndNav=std::clamp(std::max(loopStartNav,hi),loopStartNav,std::max(loopStartNav,activeBars-1));loopOnNav=true;InvalidateRect(win,nullptr,FALSE);}
void drawNavTools(HDC d){RECT p=panels15.timeline;LONG y=p.top+13;setLoopNavR={p.right-350,y,p.right-275,y+27};loopNavR={p.right-269,y,p.right-205,y+27};fitNavR={p.right-199,y,p.right-145,y+27};zoomOutNavR={p.right-139,y,p.right-97,y+27};zoomInNavR={p.right-91,y,p.right-49,y+27};pill16(d,setLoopNavR,L"SET LOOP",CYAN16);pill16(d,loopNavR,L"LOOP",PINK16,loopOnNav);pill16(d,fitNavR,L"FIT",PURPLE16);pill16(d,zoomOutNavR,L"-",PURPLE16);pill16(d,zoomInNavR,L"+",PURPLE16);if(loopOnNav){int left=(int)p.left+15,right=(int)p.right-15,width=std::max(1,right-left),a=loopStartNav-scrollBar,b=loopEndNav-scrollBar+1;if(b>0&&a<visibleBars){a=std::clamp(a,0,visibleBars);b=std::clamp(b,0,visibleBars);LONG x0=left+(LONG)((long long)a*width/std::max(1,visibleBars)),x1=left+(LONG)((long long)b*width/std::max(1,visibleBars));RECT r{x0,p.top+38,x1,p.top+43};fill(d,r,PINK16);}}}

void smoothKickTailsNav(std::vector<int16_t>&a,int startBar){if(a.empty())return;const int bpmNow=std::max(60,(int)bpm);const double secBar=240.0/(double)bpmNow;const long long barFrames=(long long)(secBar*SR),stepFrames=std::max<long long>(1,barFrames/STEPS),tail=(long long)(0.30*SR),half=96;for(int lane=0;lane<(int)lanes.size();++lane){if(lanes[lane].type!=LaneType::Drums||kicks15[lane].enabled||lanes[lane].mute)continue;for(int bar=std::max(0,startBar);bar<activeBars;++bar){auto&dr=drumForLane11(lane,bar);for(int step=0;step<STEPS;++step){if(!dr[0][step])continue;long long center=((long long)bar-startBar)*barFrames+(long long)step*stepFrames+tail,a0=center-half,a1=center+half;if(a0<0||(size_t)(a1*2+1)>=a.size())continue;for(int ch=0;ch<2;++ch){double left=a[(size_t)a0*2+ch],right=a[(size_t)a1*2+ch];for(long long q=0;q<=2*half;++q){double u=(double)q/(2.0*half),sm=u*u*(3.0-2.0*u);a[(size_t)(a0+q)*2+ch]=(int16_t)std::lrint(left+(right-left)*sm);}}}}}}
void renderNav(std::vector<int16_t>&a,int start){render16(a,start);smoothKickTailsNav(a,start);}
void playNav(){if(playing){stopAudio();return;}int start=loopOnNav?loopStartNav:cursorBar;start=std::clamp(start,0,std::max(0,activeBars-1));playStartBar=start;renderNav(playBuffer,start);if(loopOnNav){int bpmNow=std::max(60,(int)bpm);double secBar=240.0/(double)bpmNow;size_t frames=(size_t)(secBar*SR)*std::max(1,loopEndNav-loopStartNav+1),samples=frames*2;if(playBuffer.size()>samples)playBuffer.resize(samples);}WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*sizeof(int16_t),0xFFFFFFFFu);if(loopOnNav){waveHdr.dwFlags=WHDR_BEGINLOOP|WHDR_ENDLOOP;waveHdr.dwLoops=0xFFFFFFFFu;}if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}

void exportNav(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;renderNav(a,0);if(a.empty()){MessageBoxW(win,L"Rien a exporter.",L"Boomify",MB_OK|MB_ICONWARNING);return;}std::ofstream o(p,std::ios::binary);if(!o){MessageBoxW(win,L"Impossible de creer le WAV.",L"Boomify",MB_OK|MB_ICONERROR);return;}uint32_t ds=(uint32_t)(a.size()*sizeof(int16_t)),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);o.close();MessageBoxW(win,L"Export WAV termine.",L"Boomify",MB_OK|MB_ICONINFORMATION);}
}

LRESULT CALLBACK proc_v17_nav(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_PAINT){LRESULT r=proc_v17(h,m,w,l);HDC d=GetDC(h);if(d){drawNavTools(d);ReleaseDC(h,d);}return r;}if(m==WM_MOUSEWHEEL||m==WM_MOUSEHWHEEL){POINT q{GET_X_LPARAM(l),GET_Y_LPARAM(l)};ScreenToClient(h,&q);if(inside(timeline10,q)){short delta=GET_WHEEL_DELTA_WPARAM(w);bool ctrl=(GET_KEYSTATE_WPARAM(w)&MK_CONTROL)!=0;if(ctrl)zoomNav(delta>0?1:-1);else scrollTimelineNav(delta<0?1:-1);return 0;}}if(m==WM_LBUTTONDOWN){if(inside(playR,p)){playNav();return 0;}if(inside(wavR,p)){exportNav();return 0;}if(inside(setLoopNavR,p)){setLoopNavFromSelection();return 0;}if(inside(loopNavR,p)){if(loopOnNav)loopOnNav=false;else setLoopNavFromSelection();InvalidateRect(h,nullptr,FALSE);return 0;}if(inside(fitNavR,p)){fitTimelineNav();return 0;}if(inside(zoomOutNavR,p)){zoomNav(-1);return 0;}if(inside(zoomInNavR,p)){zoomNav(1);return 0;}}if(m==WM_KEYDOWN){bool ctrl=(GetKeyState(VK_CONTROL)&0x8000)!=0;if(w==VK_SPACE){playNav();return 0;}if(ctrl&&w=='L'){if(loopOnNav)loopOnNav=false;else setLoopNavFromSelection();InvalidateRect(h,nullptr,FALSE);return 0;}if(ctrl&&(w==VK_OEM_PLUS||w==VK_ADD)){zoomNav(1);return 0;}if(ctrl&&(w==VK_OEM_MINUS||w==VK_SUBTRACT)){zoomNav(-1);return 0;}}return proc_v17(h,m,w,l);}
