// Boomify V15 - Alpha 6 DAW expansion
#define BOOMIFY_V15_INCLUDE
#define proc_v14 proc_v14_base15
#include "main_v14.cpp"
#undef proc_v14
#undef BOOMIFY_V15_INCLUDE

#include <commctrl.h>
#include <cmath>

namespace {
struct Sample15{std::wstring path;int bar=-1;std::vector<int16_t> pcm;};
struct Kick15{bool enabled=false;int pitch=48,decay=42,punch=65,drive=58;};
std::array<Sample15,V6_MAX_TRACKS> samples15{};
std::array<Kick15,V6_MAX_TRACKS> kicks15{};
std::array<COLORREF,V6_MAX_TRACKS> colors15{};
RECT import15{},boom15{},color15{},master15{};bool masterOn15=true;
COLORREF defaultColor15(int i){static COLORREF c[]={RGB(220,96,69),RGB(69,132,210),RGB(162,93,205),RGB(62,169,126),RGB(220,154,55),RGB(205,76,118),RGB(70,170,181),RGB(130,139,151)};return c[i%8];}
bool loadWav15(const std::wstring&p,std::vector<int16_t>&out){std::ifstream f(p,std::ios::binary);if(!f)return false;char id[4];uint32_t n=0;f.read(id,4);f.read((char*)&n,4);f.read(id,4);if(!f||std::string(id,4)!="WAVE")return false;uint16_t fmt=0,ch=0,bits=0;uint32_t rate=0;std::vector<char> data;while(f.read(id,4)){uint32_t sz=0;f.read((char*)&sz,4);if(!f)break;if(std::string(id,4)=="fmt "){uint16_t align=0;uint32_t br=0;f.read((char*)&fmt,2);f.read((char*)&ch,2);f.read((char*)&rate,4);f.read((char*)&br,4);f.read((char*)&align,2);f.read((char*)&bits,2);if(sz>16)f.seekg(sz-16,std::ios::cur);}else if(std::string(id,4)=="data"){data.resize(sz);f.read(data.data(),sz);}else f.seekg(sz,std::ios::cur);if(sz&1)f.seekg(1,std::ios::cur);}if(fmt!=1||bits!=16||(ch!=1&&ch!=2)||rate!=SR||data.empty())return false;const int16_t*s=(const int16_t*)data.data();size_t frames=data.size()/(2*ch);out.resize(frames*2);for(size_t i=0;i<frames;i++){int16_t a=s[i*ch],b=ch==2?s[i*ch+1]:a;out[i*2]=a;out[i*2+1]=b;}return true;}
void mixSample15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);long long barFrames=(long long)(secBar*SR);for(int l=0;l<(int)lanes.size();l++){auto&s=samples15[l];if(s.bar<0||s.pcm.empty()||lanes[l].mute)continue;long long dst=((long long)s.bar-startBar)*barFrames;if(dst<0)continue;double g=lanes[l].volume/100.0;for(size_t k=0;k+1<s.pcm.size();k+=2){long long fr=dst+(long long)k/2;size_t j=(size_t)fr*2;if(j+1>=a.size())break;for(int c=0;c<2;c++){int v=a[j+c]+(int)(s.pcm[k+c]*g);a[j+c]=(int16_t)std::clamp(v,-32768,32767);}}}}
void mixBoom15(std::vector<int16_t>&a,int startBar){double secBar=240.0/std::max(60,bpm);long long barFrames=(long long)(secBar*SR),stepFrames=barFrames/STEPS;for(int l=0;l<(int)lanes.size();l++){if(!kicks15[l].enabled||lanes[l].mute||lanes[l].type!=LaneType::Drums)continue;auto&k=kicks15[l];for(int b=startBar;b<activeBars;b++){auto&d=drumForLane11(l,b);for(int s=0;s<STEPS;s++)if(d[0][s]){long long st=((long long)b-startBar)*barFrames+(long long)s*stepFrames;long long len=std::min<long long>((long long)(SR*(0.08+k.decay*0.0045)),stepFrames*2);double ph=0;for(long long q=0;q<len;q++){double t=(double)q/SR,env=std::exp(-t*(8.0+(100-k.decay)*0.09));double hz=45.0+k.pitch*1.25+(150.0*k.punch/100.0)*std::exp(-t*35.0);ph+=6.283185307179586*hz/SR;double x=std::sin(ph)*env*(0.55+0.35*k.punch/100.0),drv=1.0+k.drive/18.0;x=std::tanh(x*drv)/std::tanh(drv);size_t j=(size_t)(st+q)*2;if(j+1>=a.size())break;int add=(int)(x*15000.0*lanes[l].volume/100.0);for(int c=0;c<2;c++)a[j+c]=(int16_t)std::clamp((int)a[j+c]+add,-32768,32767);}}}}}
void masterBus15(std::vector<int16_t>&a){if(!masterOn15)return;double env=0;for(auto&v:a){double x=v/32768.0;env=std::max(std::abs(x),env*0.9993);double gain=env>0.28?std::pow(0.28/env,0.42):1.0;x*=gain*1.65;x=std::tanh(x*1.35)/std::tanh(1.35);x=std::clamp(x,-0.96,0.96);v=(int16_t)std::lrint(x*32767.0);}}
void render15(std::vector<int16_t>&a,int start){renderRange11(a,start);mixSample15(a,start);mixBoom15(a,start);masterBus15(a);}
void play15(){if(playing){stopAudio();return;}playStartBar=cursorBar;render15(playBuffer,playStartBar);WAVEFORMATEX f{};f.wFormatTag=WAVE_FORMAT_PCM;f.nChannels=2;f.nSamplesPerSec=SR;f.wBitsPerSample=16;f.nBlockAlign=4;f.nAvgBytesPerSec=SR*4;if(waveOutOpen(&wave,WAVE_MAPPER,&f,(DWORD_PTR)win,0,CALLBACK_WINDOW)!=MMSYSERR_NOERROR){wave=nullptr;MessageBoxW(win,L"Sortie audio Windows indisponible.",L"Boomify",MB_OK|MB_ICONERROR);return;}waveHdr={};waveHdr.lpData=(LPSTR)playBuffer.data();waveHdr.dwBufferLength=(DWORD)std::min<size_t>(playBuffer.size()*2,0xFFFFFFFFu);if(waveOutPrepareHeader(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR||waveOutWrite(wave,&waveHdr,sizeof(waveHdr))!=MMSYSERR_NOERROR){stopAudio();return;}playing=true;SetTimer(win,1,33,nullptr);InvalidateRect(win,nullptr,FALSE);}
void export15(){auto p=dialog(true,L"WAV Audio\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t>a;render15(a,0);std::ofstream o(p,std::ios::binary);uint32_t ds=(uint32_t)(a.size()*2),rs=36+ds,fs=16,rate=SR,br=SR*4;uint16_t pcm=1,ch=2,al=4,bits=16;o.write("RIFF",4);o.write((char*)&rs,4);o.write("WAVEfmt ",8);o.write((char*)&fs,4);o.write((char*)&pcm,2);o.write((char*)&ch,2);o.write((char*)&rate,4);o.write((char*)&br,4);o.write((char*)&al,2);o.write((char*)&bits,2);o.write("data",4);o.write((char*)&ds,4);o.write((char*)a.data(),ds);}
std::wstring editText15(HWND owner,const std::wstring&initial){static std::wstring result;result=initial;HINSTANCE hi=(HINSTANCE)GetWindowLongPtrW(owner,GWLP_HINSTANCE);static bool reg=false;static HWND ed=nullptr;if(!reg){WNDCLASSW wc{};wc.hInstance=hi;wc.lpszClassName=L"BoomifyName15";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.lpfnWndProc=[](HWND h,UINT m,WPARAM w,LPARAM l)->LRESULT{if(m==WM_CREATE){ed=CreateWindowW(L"EDIT",result.c_str(),WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,18,22,300,28,h,(HMENU)1,nullptr,nullptr);CreateWindowW(L"BUTTON",L"OK",WS_CHILD|WS_VISIBLE,168,62,72,28,h,(HMENU)2,nullptr,nullptr);CreateWindowW(L"BUTTON",L"Annuler",WS_CHILD|WS_VISIBLE,246,62,72,28,h,(HMENU)3,nullptr,nullptr);SetFocus(ed);SendMessageW(ed,EM_SETSEL,0,-1);return 0;}if(m==WM_COMMAND){if(LOWORD(w)==2){wchar_t b[128]{};GetWindowTextW(ed,b,128);result=b;DestroyWindow(h);return 0;}if(LOWORD(w)==3){result.clear();DestroyWindow(h);return 0;}}if(m==WM_CLOSE){result.clear();DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);};RegisterClassW(&wc);reg=true;}HWND h=CreateWindowExW(WS_EX_TOPMOST,L"BoomifyName15",L"Nom de la piste",WS_POPUP|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,350,135,owner,nullptr,hi,nullptr);EnableWindow(owner,FALSE);ShowWindow(h,SW_SHOW);MSG msg{};while(IsWindow(h)&&GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}EnableWindow(owner,TRUE);SetForegroundWindow(owner);return result;}
void rename15(){if(laneSelected<0||laneSelected>=(int)lanes.size())return;auto s=editText15(win,lanes[laneSelected].name);if(!s.empty()){lanes[laneSelected].name=s;InvalidateRect(win,nullptr,FALSE);}}
void cycleColor15(){if(laneSelected<0)return;static int ci=0;colors15[laneSelected]=defaultColor15(++ci);InvalidateRect(win,nullptr,FALSE);}
void importSample15(){if(laneSelected<0||laneSelected>=(int)lanes.size())return;if(lanes[laneSelected].type!=LaneType::Audio){MessageBoxW(win,L"Selectionne d'abord une piste AUDIO.",L"Boomify Sample",MB_OK|MB_ICONINFORMATION);return;}auto p=dialog(false,L"WAV PCM 16-bit 44.1 kHz\0*.wav\0",L"wav");if(p.empty())return;std::vector<int16_t> pcm;if(!loadWav15(p,pcm)){MessageBoxW(win,L"Pour cette Alpha : WAV PCM 16-bit, 44.1 kHz, mono ou stereo.",L"Format audio non supporte",MB_OK|MB_ICONWARNING);return;}samples15[laneSelected]={p,selectedBar,std::move(pcm)};InvalidateRect(win,nullptr,FALSE);}
void addBoom15(){if((int)lanes.size()>=V6_MAX_TRACKS)return;lanes.push_back({L"BoomBox Kick",LaneType::Drums,false,false,90});laneSelected=(int)lanes.size()-1;kicks15[laneSelected].enabled=true;colors15[laneSelected]=RGB(225,88,62);layoutV6(win);InvalidateRect(win,nullptr,FALSE);}
void draw15(HDC d){for(int i=0;i<(int)lanes.size();i++){if(colors15[i]==0)colors15[i]=defaultColor15(i);if(laneHeadR[i].bottom>laneHeadR[i].top)fill(d,{laneHeadR[i].left,laneHeadR[i].top,laneHeadR[i].left+5,laneHeadR[i].bottom},colors15[i]);}import15={318,88,410,118};boom15={416,88,516,118};color15={522,88,612,118};master15={618,88,716,118};button(d,import15,L"+ SAMPLE");button(d,boom15,L"+ BOOMBOX");button(d,color15,L"COULEUR");fill(d,master15,masterOn15?RGB(62,128,93):RGB(42,44,49));label(d,masterOn15?L"MASTER ON":L"MASTER OFF",master15.left+12,master15.top+10,7,RGB(235,237,241),FW_BOLD);if(laneSelected>=0&&laneSelected<(int)lanes.size()&&samples15[laneSelected].bar>=0)label(d,L"Sample charge sur cette piste",(int)inspector10.left+18,146,7,RGB(126,190,165),FW_BOLD);if(laneSelected>=0&&kicks15[laneSelected].enabled)label(d,L"BOOMBOX : kick synthetise + drive",(int)inspector10.left+18,146,7,RGB(235,126,99),FW_BOLD);}
LRESULT CALLBACK proc_v15(HWND h,UINT m,WPARAM w,LPARAM l){POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(m==WM_PAINT){PAINTSTRUCT ps;HDC s=BeginPaint(h,&ps);RECT c;GetClientRect(h,&c);HDC mem=CreateCompatibleDC(s);HBITMAP bm=CreateCompatibleBitmap(s,std::max(1,(int)c.right),std::max(1,(int)c.bottom));auto old=SelectObject(mem,bm);draw11(mem,c);overlay12(mem);drawV13Chrome(mem);drawV14(mem);draw15(mem);BitBlt(s,0,0,c.right,c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject(bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_LBUTTONDOWN){if(inside(playR,p)){play15();return 0;}if(inside(wavR,p)){export15();return 0;}if(inside(renameTrackR,p)){rename15();return 0;}if(inside(import15,p)){importSample15();return 0;}if(inside(boom15,p)){addBoom15();return 0;}if(inside(color15,p)){cycleColor15();return 0;}if(inside(master15,p)){masterOn15=!masterOn15;InvalidateRect(h,nullptr,FALSE);return 0;}}return proc_v14_base15(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE,LPWSTR,int){for(int i=0;i<V6_MAX_TRACKS;i++)colors15[i]=defaultColor15(i);editorOpen=true;sound9[1]=Sound9::SubBass;sound9[2]=Sound9::SawLead;master=100;WNDCLASSW wc{};wc.lpfnWndProc=proc_v15;wc.hInstance=hi;wc.lpszClassName=L"BoomifyAlpha6";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);win=CreateWindowExW(0,wc.lpszClassName,L"Boomify Studio - Alpha 6",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1440,900,nullptr,nullptr,hi,nullptr);if(!win)return 1;ShowWindow(win,SW_MAXIMIZE);UpdateWindow(win);layout11(win);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return(int)msg.wParam;}
